### ISSUE TITLE
[API DESIGN REVIEW] sample weight in ImageDataGenerator.flow

### ISSUE THREAD

**Issue by wdobbels** [keras-team/keras#10036]
https://docs.google.com/document/d/14anankKROhliJCpInQH-pITatdjO9UzSN6Iz0MwcDHw/edit?usp=sharing

Makes it easy to use data augmentation when sample weights are available.

**Comment by wouterdobbels** [comment]
I'm sending the pull request. However, it is worth pointing out that since commit [a1d544f](https://github.com/keras-team/keras/commit/a1d544f4a156373b1c9e72d3af0bf87e4d81d90c) (adding passthrough arguments to `ImageDataGenerator.flow`) the integration between model.fit_generator and ImageDataGenerator.flow was already possible (this commit happened after the API design review request).

This is how sample weighted data augmentation is possible with passthrough arguments:

`model.fit_generator(datagen.flow((x_train, [y_train, w_train])))`

This is how sample weights work with the newly proposed API (the y values can now be passed as an argument instead of passthrough, which is the more common case):

`model.fit_generator(datagen.flow(x_train, y=y_train, sample_weight=w_train))`

**Comment by aPToul** [comment]
Was this added in?

**Comment by wouterdobbels** [comment]
Yes, the `sample_weight` argument is available in ImageDataGenerator.flow (as can be seen from the keras documentation). The implementation seems to have moved to the [keras-preprocessing](https://github.com/keras-team/keras-preprocessing) repo.
