### ISSUE TITLE
how to use multicore cpu to do prediction?

### ISSUE THREAD

**Issue by loveJasmine** [keras-team/keras#10232]

**Comment by mrTsjolder** [comment]
I suspect this should be done automatically. If not, then you'll probably have better chances finding a solution when getting in touch with the developers of the backend (i.e. tensorflow, theano, ...) that you are using. 

Also, have you considered to get some help through help-sites like [stackoverflow](https://stackoverflow.com)? I have a suspicion that your question might belong there, rather than in these issue-sections of the projects you are using (unless it would indeed turn out to be a bug).
