### ISSUE TITLE
_preprocess_numpy_input in keras.applications.imagenet_utils should not be in place

### ISSUE THREAD

**Issue by bottydim** [keras-team/keras#10240]
give the signiture of 
```
def _preprocess_numpy_input(x, data_format, mode):
....
    return x
```
it should either not return anything, or have an extra optional parameter in_place.

**Comment by vkk800** [comment]
We had a discussion about this recently here: https://github.com/keras-team/keras/pull/10153 .

The conclusion was:

* In-place copying makes sense, because always creating a new array can lead to large performance decrease with large images.

* If the user wants to create a new image instead of copying in-place, they should use np.copy(x) as the argument.
