### ISSUE TITLE
'preprocess_input' defaults to 'caffe' rather than 'tf'

### ISSUE THREAD

**Issue by ialhashim** [keras-team/keras#10279]
I was very confused when my 'cat' pictures where predicted as 'lampshade'. Shouldn't Tensorflow be the default?

https://github.com/keras-team/keras/blob/b0f1bb9c7c68e24137a9dc284dc210eb0050a6b4/keras/applications/imagenet_utils.py#L151

**Comment by fchouteau** [comment]
Hi,

Preprocess input default to caffe because it is imported straight in `keras.applications.vgg16` and  `keras.applications.resnet50` where those models were trained using caffe2 preprocessing. I suppose this was put in imagenet_utils to have sane defaults for those classic networks.

For more recent models such as Xception and MobileNet (where the training was under tf preprocessing), the preprocess_input function is actually redefined see: https://github.com/keras-team/keras/blob/master/keras/applications/xception.py#L267 for tf and https://github.com/keras-team/keras/blob/master/keras/applications/densenet.py#L325 for torch

**Comment by ialhashim** [comment]
I see, I was testing Densenet so actually I should be using 'torch' or better yet import the corresponding preprocessing function and the model definition from 'densenet' (or other trained models).

**Comment by swghosh** [comment]
I had the same question. Thanks, @ialhasim @fchouteau for the clarification.

Does that mean the recommended way of using preprocessing_input from models like vgg16 and resnet50 be mode='caffe' (the default one) itself for getting correct predictions on a Tensorflow backend too?
