### ISSUE TITLE
ValueError when using load_model or load_weights

### ISSUE THREAD

**Issue by Mastush** [keras-team/keras#10447]
Hi. I built a simple lenet model:

```
def get_lenet():
    kernel_size = (5, 5)
    model = Sequential()  # each image is 28x28
    model.add(Conv2D(32, kernel_size, activation='relu'))  # now 24x24
    model.add(MaxPool2D())  # 12x12
    model.add(Conv2D(64, kernel_size, activation='relu'))  # 8x8
    model.add(MaxPool2D())  # 4x4
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(10, activation='softmax'))
    return mode
```

Compiling and training all go well, then I save the model:
`model.save_weights('w.h5')
with open('model_architecture.json', 'w') as f:
    f.write(model.to_json())`

Later, when trying to load it:
```
with open('model_architecture.json', 'r') as f:
    model = model_from_json(f.read())
model.load_weights('w.h5')
```

I get the following error:
`ValueError: You are trying to load a weight file containing 4 layers into a model with 0 layers.`

The same error arrises when using save_model.
Does anyone have an idea?

**Comment by pavithrasv** [comment]
@Mastush with `save_weights` you are just the saving the model weights. This does not save the model architecture which is why when you try to load_weights onto the model you see the error that the model has 0 layers.

Can you try saving the model using model.save('my_model.h5')
Please find detailed doc about saving model [here](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model).

**Comment by AEDWIP** [comment]
FYI

I had the same bug using 2.2.4. downgrading to 2.1.6 solved the problem
