### ISSUE TITLE
ValueError: Cannot feed value of shape , Using Stateful LSTM

### ISSUE THREAD

**Issue by behdadahmadi** [keras-team/keras#10445]
I am using stateful LSTM network, I got this error:

`ValueError: Cannot feed value of shape (2, 5, 7) for Tensor u'lstm_1_input:0', which has shape '(5, 5, 7)'`

```
epo_num= 20
model = Sequential()
model.add(LSTM(128,batch_input_shape=(5,5,7),return_sequences=True,stateful=True))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(LSTM(32,stateful=True))
model.add(Activation('relu'))
model.add(Dense(2))
model.add(Activation('softmax'))
checkpoint = ModelCheckpoint('./model30-{epoch:02d}.h5')
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())
for i in range(epo_num):
    print('Epochs {:d}/{:d}'.format(i+1,epo_num))
    model.fit(trainX,trainY,batch_size=5,epochs=1,validation_split=0.2,shuffle=False)
    model.reset_states()

```

What's the problem with network? Thank you

**Comment by pavithrasv** [comment]
@behdadahmadi it seems like the shape of trainX is incorrect. Can you verify that it is (5, 7) ?

**Comment by Elb5465** [comment]
Try changing Dense(2) to Dense(5) since that is the only 2 you have in your code and its expecting a 5 based on your error.

**Comment by behdadahmadi** [comment]
@Elb5465 I use it for Binary classification. `Dense(2)` its the last layer with `softmax` to classify. So it should be only 2 neurons. Am I right?

**Comment by behdadahmadi** [comment]
@pavithrasv  I'm sure its (5,7) by `print trainX.shape`

**Comment by HughKu** [comment]
@behdadahmadi 

Based on my experience, stateful LSTM needs to specify `BATCH_SIZE`, in `batch_input_shape=(BATCH_SIZE, TIME_STEPS, INPUT_SIZE)`, which MUST divide the total sample size in `train set` or `val set`.

In your case, valid input should be `trainX.shape = (N, 5, 7)` and since you specify `validation_split=0.2`  the following must be true:
- `(N*0.8) % BATCH_SIZE == 0` -> This is `train set`
- `(N*0.2) % BATCH_SIZE == 0` -> This is `val set`

Please correct me if I am wrong, thanks.
