### ISSUE TITLE
wrongly handled empty KERAS_BACKEND value

### ISSUE THREAD

**Issue by kvechera** [keras-team/keras#10516]
If environment variable KERAS_BACKEND is set, but empty, keras assumes that it has a valid value and tries to load undefined backend.

**Comment by lucasdavid** [comment]
My two cents on this is that adding silent error handling everywhere tend to make it really hard for inexperienced users to debug their programs.

If the envvar was set, then there's the chance the user wanted to change the backend for that specific execution, and we shouldn't silently ignore this and fall back to the default configuration.

In this particular case, I think we'd be better off if keras halted because the backend is invalid and informed the user how to fix it.

**Comment by kvechera** [comment]
It's not a silent error handling. It's making the behavior be more main stream. If the envvar is set to empty, for most unix apps and scripts it means the same like value is not set - the value is not present. The common pattern to check the value: '[ -n "$VAR" ]' works the same for both empty and unset VAR.

And, for example, inexperienced users rather assign empty value 'VAR=' instead of doing 'unset VAR'
