### ISSUE TITLE
Please provide object detection example (feature request)

### ISSUE THREAD

**Issue by mosheliv** [keras-team/keras#10596]
Hi,
Love keras! However, examples on training object detection are few and not canonical. Especially training mobilenet ssd, which is great for weaker older computers.

Regards,
Moshe

**Comment by msprengholz** [comment]
I'd like to see this too. There are a few object detectors, but all of them seem to use specific backend code (i.e. TensorFlow). Is it even possible to write something like this that only uses the Keras abstraction layer? I'm interested in extending MobileNetV2 (which is included in Keras since version 2.2.0) by adding a SSDLite feature extractor. Any ideas on how to do this?
