### ISSUE TITLE
Why tokenizer work only for chars? Bugreport probably

### ISSUE THREAD

**Issue by hadaev8** [keras-team/keras#10768]
Last keras, testing code:

```
text = open(os.path.join(work_dir, 'train_text_en.txt'), 'r', encoding='utf-8').read()
tokenizer = Tokenizer(char_level=False)
tokenizer.fit_on_texts(text)
print(tokenizer.word_index)
```

in output get chars
`{'e': 1, 't': 2, 'a': 3, 'o': 4, 'i': 5, 'n': 6, 's': 7, 'r': 8, 'h': 9, 'l': 10, 'd': 11, 'm': 12, 'c': 13, 'u': 14, 'f': 15, 'p': 16, 'g': 17, 'y': 18, 'w': 19, 'b': 20, 'v': 21, 'k': 22, 'x': 23, '—': 24, "'": 25, 'z': 26, 'j': 27, 'q': 28, '0': 29, '1': 30, '5': 31, '2': 32, '3': 33, '4': 34, '6': 35, '7': 36, '9': 37, '8': 38, '…': 39, 'с': 40}`

**Comment by tRosenflanz** [comment]
This is happening because text is not a list of text and is just 1 string. This loop here separates the string into chars and processes each separately:
https://github.com/keras-team/keras-preprocessing/blob/e002ebd40e888965686e8946acefe02f5a910576/keras_preprocessing/text.py#L205
You might want to split you text into a list of texts or if this is not what you are looking for you can just put `tokenizer.fit_on_texts([text])` to process the string as a list of texts

**Comment by hadaev8** [comment]
Thanks
