### ISSUE TITLE
Tensorflow / CNTK compatibility issue for index selection

### ISSUE THREAD

**Issue by christopher5106** [keras-team/keras#11177]
The simple code

```
from keras import backend as K

var = K.ones(shape=(3, 4, 5))

print(var[...,1].shape)
```
gives (3, 4) under Tensorflow backend
gives (3,4,1) under CNTK backend.

**Comment by gabrieldemarmiesse** [comment]
Can you use `K.int_shape(var)` instead of `x.shape`  and report if the bug is still there? `x.shape` is not a backend function. Thus you cannot expect it to be compatible across backend.

**Comment by christopher5106** [comment]
What else than the shape do you expect it to print ?

**Comment by christopher5106** [comment]
I tried with K.int_shape and I confirm.
But I'm surprised by the question.

**Comment by gabrieldemarmiesse** [comment]
Keras garantees (as much as possible) that all keras backend function behave the same across backends. If you call, let's say tf.clip_by_value and C.clip_by_value (I don't even know if it exist), keras doesn't have any control on those calls. x.shape in TF calls a tensorflow function. x.shape in CNTK calls a CNTK function. Keras doesn't have any control in this. This is because a keras tensor is a tensorflow tensor in the tensorflow backend. And a keras tensor is a CNTK tensor in the CNTK backend. Keras doesn't control their attributes (to allow users to call tf.shape(x) for example directly on the tensor).

**Comment by gabrieldemarmiesse** [comment]
Thanks for the report. I'll now note the bug that we should fix:
```python
from keras import backend as K

var = K.ones(shape=(3, 4, 5))

print(K.int_shape(var[...,1]))
```
Returns (3,4,1) in the CNTK backend. Which may lead to bugs in the keras codebase (because unexpected behavior). I would say that this is a bug. Maybe an issue should be opened in CNTK directly rather than keras actually.

**Comment by gabrieldemarmiesse** [comment]
Maybe @souptc can help us on this.

**Comment by christopher5106** [comment]
This bug has lots of consequences inside the code. I added an "expand_dims" in my code depending on the backend but this is should not be in the code.

I think that a shape is a shape, if you see it written (3,4) it is not (3,4,1).

**Comment by gabrieldemarmiesse** [comment]
It should follow the numpy conventions. So the right answer is (3, 4).

**Comment by christopher5106** [comment]
Great thanks
