### ISSUE TITLE
[API DESIGN REVIEW] Add random crop support to ImageDataGenerator

### ISSUE THREAD

**Issue by datumbox** [keras-team/keras#11237]
Producing Random Crops during training is a standard data-augmentation technique used by most important CNN papers. Along with avoiding over-fitting, it can be used to handle images of variable size and to avoid stretching the pictures to a fixed input.

Adding support to the `ImageDataGenerator` class requires passing a new `random_crop=False` argument to its constructor and modifying the logic of its functions `flow_from_directory()` and `flow_from_dataframe()`. The logic of the aforementioned methods needs to be updated since currently their mandatory `target_size` is passed to the `load_img()` method (optional argument), so effectively the images are resized/stretched before we get the chance to do any crops. 

The new logic should avoid the resize in `load_img()` if the `random_crop=True` (obviously if `random_crop=False` we will still do it). The Image will be loaded in memory and later cropped to the requested `target_size`. I believe the best place to do this is on the top of the `apply_transform()` method just before any other operation takes place.

I have not implemented the feature but I believe that the above description implements it in a backwards compatible way. One potential caveat that I see is that the `flow()` cannot support `random_crop=True`. The images are already loaded on a numpy array and have a fixed size. If one invokes `flow()` after passing `random_crop=True` to the constructor, he/she should receive an exception or warning. Another potential thing to keep in mind (perhaps add it in the documentation) is that while using this feature, you can't pass images of extremely different sizes. It is recommended to "fix" the smallest dimension of every image to a specific size (slightly larger than `target_size`) and then do the random crops.

I would love to hear your views on whether you want this feature, how the API would look like etc. If you agree, I'm happy to implement it.

cc @fchollet @Dref360

**EDIT:**
See Keras API Design Review at https://docs.google.com/document/d/1zdSsPCxbrCedQgOYqc-Ne6gWzYqIqIqDgExHyThxl1o/edit?usp=sharing

**Comment by tedyu** [comment]
```
to the constractor
```
There was a typo above.
```
to "fix" the smallest dimension of every image to a specific size 
```
Is there any restriction on the other dimensions ?

Thanks

**Comment by datumbox** [comment]
@tedyu thanks, fixed the typo.

Concerning how you resize, it depends on the problem that you have, the data, the input of your network etc. Let's assume that your networks input is 224x224x3. Krizhevsky et al [suggested](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf) to downsample the original images to 256x256 and then apply random 224x224 crops to them; that was a common approach adopted by lots of other researchers. If you want to avoid image stretching (typically for problems beyond image classification), another option is to downsample the the smallest dimension of the image (height or width) to 256 and allow the other dimension to be larger (by maintaining the aspect ratio). Then your input dataset will have images of variable size. The proposed update will allow you to produced fixed size images by applying random 224x224 crops on the original 256xA or Bx256 images.

**Comment by rohit-gupta** [comment]
Maybe `flow()` can support `random_crop=True` if the input is list of images instead of numpy array ?

**Comment by datumbox** [comment]
@rohit-gupta Thanks for the suggestion; that is true. 

I had a brief look at `NumpyArrayIterator` and it seems it supports receiving a list of arrays but it currently requires all of the image arrays to be of [equal size](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py#L1584). Moreover later on it converts the list of arrays in a [single array](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py#L1628) and I'm not sure how drastically it needs to be refactored to avoid this.

Since `keras-processing` was moved out of `keras` it's a bit hard to trace the original author(s) of the `NumpyArrayIterator`. I would love to hear from other maintainers on whether such feature is wanted and perhaps their input on whether the `flow()` should support the `random_crop=True` flag before I start digging into the technical details of `NumpyArrayIterator`. 

@gabrieldemarmiesse I also just noticed that "Keras API Design Reviews" require an accompanying document that describes the changes. I believe I describe all the details on this issue but if the doc is required I'm happy to draft one. Let me know. :)

**Comment by gabrieldemarmiesse** [comment]
I think it's better if you make a google doc if you don't mind. Maintainers can afford very little time to each task since they are so many of them. Everything that can reduce cognitive workload is very appreciated. API design changes are usually in form of a google doc, so let's go with that.

FYI, I don't think i'll review the document, I have other things in my TODO list, and API changes reviews are mostly the job of @fchollet.

Also, in the keras repo, there is a lot of freedom to change and refecactor things as long as you don't modify the API. So no worries about the internal consequences of the implementation.

I think that a random crop is a good thing to have, it's common, so +1 from me.

**Comment by rohit-gupta** [comment]
One thing I am concerned by is that a single `random_crop=True` option is too inflexible. There should be some way to specify the cropping strategy, i.e. size of smallest dimension, desired crop size, etc

**Comment by theceday** [comment]
I think those pre-process operations should be a list, i am not exactly a cv guy but order of operations should matter as you concern where to add it exactly. Adding a new parameter for each operation is kinda confusing and not very good in the long term. And this is probably obvious for everyone. If something has to be broken, it is better to broke it sooner rather than later. (this is not exactly issue for this PR but a general one)

**Comment by gabrieldemarmiesse** [comment]
Sorry about that. Pinging @fchollet again just in case. Also, can you open the same issue (with the google doc) in https://github.com/keras-team/keras-preprocessing/issues. This will give your issue more visibility since there are already many issues in the keras main repo. You will likely get more success. Keep this issue open just in case.

**Comment by datumbox** [comment]
@gabrieldemarmiesse Thanks for the prompt reply. I opened it also on keras-preprocessing as you suggested. If you believe that the change will overburden the API of `ImageDataGenerator` feel free to close the tickets.
