### ISSUE TITLE
AttributeError when attempting to set batch_input_shape using setattr

### ISSUE THREAD

**Issue by ericbhanson** [keras-team/keras#11311]
Keras 2.2.4; TensorFlow 1.11.0; Python 3.6.6.

I'm trying to set up a test harness for an LSTM RNN. As a part of this, I want to test the effectiveness of statefulness. Since the LSTM is the first layer and using statefulness requires using batch_input_shape attribute rather than the input_shape attribute, I am attempting to define the layer first, then set the correct attributes. When I run the function below, I get an AttributeError: "'LSTM' object has no attribute 'dtype'." I've traced this specifically to adding the batch_input_shape attribute.

```
def build_lstm_layer(batch_size, stateful, units, X_shape):
    lstm = keras.layers.LSTM(units)

    if stateful:
        setattr(lstm, 'stateful', stateful)
        setattr(lstm, 'batch_input_shape', (batch_size, X_shape[1], X_shape[2]))

    else:
        setattr(lstm, 'input_shape', (X_shape[1], X_shape[2]))

    return lstm
```

**Comment by gabrieldemarmiesse** [comment]
You shouldn't set attribute manually. This is not supported by keras.

**Comment by gabrieldemarmiesse** [comment]
It would make the keras codebase more complicated because it would mean that we need to store the input arguments somewhere, and only do all the logic later on. You can look into de codebase to see how layers are implemented, and you'll see it would be very verbose to defer the execution of the logic in a lazy way. 

You can consider that the attributes are read-only in keras (it's also the case in many other python libraries).

**Comment by ericbhanson** [comment]
Understood - thank you for the explanation!
