### ISSUE TITLE
Time series regression with temporal sample weights

### ISSUE THREAD

**Issue by doccosmos** [keras-team/keras#11324]
Hi,

I'm trying to fit a model to a set of time series X with shape (100, 40, 2) to an output y (100, ) with sample weights (100, 40) - note that the output is a floating value and not a class label so this is regression not classification:

model_input = Input(shape = (X.shape[1], X.shape[-1]))
encode = LSTM(model_input, size = 48)(model_input) # this is not the issue
out = Dense(48, activation = 'relu')(encode)
out_y = Dense(1, activation = 'linear')(out)
model = Model(model_input, out_y)

model.compile(optimizer = 'Adam', loss = 'mse', sample_weight_mode = 'temporal')

model.fit(X, y, sample_weight = sample_weight)

then gives:

ValueError: Found a sample_weight array for an input with shape (100, 1). Timestep-wise sample weighting (use of sample_weight_mode="temporal") is restricted to outputs that are at least 3D, i.e. that have a time dimension.

I've tried forcing y to be: y.reshape(1, len(y)) which then gives:

ValueError: Error when checking target: expected lt to have shape (1,) but got array with shape (100,)

I'm using Keras 2.2.4 and Tensorflow 1.11.0 on a Mac (10.12.6) with Python 3.6.4.

-- Matthew

**Comment by tRosenflanz** [comment]
In future please open StackOverflow questions - this place is not an appropriate place for implementation questions.
You are misunderstanding what sample weight does:
It weights outputs (specifically their losses) not inputs. So when you say sample weights have shape `(100,40)` they are actually supposed to be `(100,1)` since you are using `sample_weight_mode = 'temporal'` and would be (100,) if you didn't use it.

**Comment by doccosmos** [comment]
My understanding is that sample_weight contains weights that are applied to the model's loss for each sample and in the case of time series, a 2D array with shape (samples, sequence_length) will apply a different weight to every timestep of every sample. This means that (100, 40) is the appropriate shape here since there are 100 time series, each of length 40 time steps.

**Comment by tRosenflanz** [comment]
This is correct but there is a minor nitpick which might make it clearer: 
 "will apply a different weight to every timestep of every sample" is supposed to be "will apply a different weight to every **_output_** timestep of every sample". As it currently stands your NN has output shape of (batch_size,) so there isn't any timesteps to apply the sample weights to. If you are trying to make a prediction for every timestep you input the networks should look like this:
```
model_input = Input(shape = (X.shape[1], X.shape[-1]))
encode = LSTM(model_input, size = 48,return_sequences=True)(model_input) # this is not the issue
out = TimeDistributed(Dense(48, activation = 'relu'))(encode)
out_y = TimeDistributed(Dense(1, activation = 'linear'))(out)
model = Model(model_input, out_y)
```
Notice the `return_sequences=True` flag on LSTM which causes it to output a value per each timestep rather than just the final state.

Now your output will actually have shape (batch_size,40,1,) (make sure to repeat your target variable to appropriate size) and you can use sample_weights they way you are describing.

**Comment by doccosmos** [comment]
Thanks - however, I am specifically not trying to predict the timeseries (which is what all RNN examples seem to show) but perform regression from the time series to (model) values associated with them.

**Comment by tRosenflanz** [comment]
So your output is supposed to be just 1 value per sample? Then you have no output timesteps to weight since each output is just 1 value. If not, would you mind writing just a simple description with mock numbers of how you see this working. For instance this is what I feel like you are describing currently: 
```
1. Based on sequence 1 2 3 4 5     i.e. shape (1,5,1)
2. I want to predict 6                       i.e. shape (1,)
3. My predicted value is 6.6           i.e. shape (1,)
4. Thus my loss .36 (mse)              i.e. shape (1,)
5. I want to weight .36 by (1,5)  (how? shape mismatch)
```
I am probably off of course, just trying to understand what you are trying to achieve.

**Comment by georgekibirige** [comment]
@doccosmos how do you compute the sample weight with that shape of (100,40).I am using train_on_batch and test_on_batch, I want to calculate sample_weight for every batch
