### ISSUE TITLE
get output of a layer in every epochs?

### ISSUE THREAD

**Issue by realSaeedHassani** [keras-team/keras#11485]
I implemented a keras model as follow:
```
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.2, random_state=np.random.seed(7), shuffle=True)

train_X = np.reshape(train_X, (train_X.shape[0], 1, train_X.shape[1]))
test_X = np.reshape(test_X, (test_X.shape[0], 1, test_X.shape[1]))

model = Sequential()
model.add(LSTM(100, return_sequences=False, input_shape=(train_X.shape[1], train_X.shape[2])))
model.add(Dense(train_Y.shape[1], activation='softmax'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

model.fit(train_X, train_Y, validation_split=.20,
                        epochs=1000, batch_size=50)
```
I want to give support vector machine(SVM) the output of the penultimate layer (LSTM), in any epoch(that is 1000) to svm also be trained.

But I do not know how to do this?

Any idea?

**Comment by MoyanZitto** [comment]
So you want to fit your svm with LSTM outputs after some epochs of training. Absolutely you should implement such a callback.
- check epoch number at the end of each epoch, to see if it's the right time to fit SVM
- if epoch=1000, collect training data.
- Since you want the output of an intermediate layer, build a new model with self.model.input and self.model.get_layer("layername".output.
- call self.model.predict on training data, now you've collected all LSTM output feature.
- fit your SVM and save your SVM model.
