### ISSUE TITLE
Add Trainable Swish Layer to Keras

### ISSUE THREAD

**Issue by aghoshpub** [keras-team/keras#11600]
I use a custom layer for a trainable Swish Activation function : https://arxiv.org/abs/1710.05941. It can be set to non-trainable with any beta value, so it's quite general. I'd like to add it to Keras so that it can be part of the next release. It's quite popular. Or I can add it to keras contrib. 

Where should I add the my code for Swish before making a pull request?

**Comment by gabrieldemarmiesse** [comment]
Please see the guide: https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md#pull-requests. Thanks!

Also you can check if somebody didn't already try to make a PR for this layer and was closed. https://github.com/keras-team/keras/pulls?q=is%3Apr+swish+is%3Aclosed . Maybe you can try again. @fchollet  will decide if it goes in keras or not.

Just know that in general, you can make a library out of your layer on your repo, so that users can do `pip install swish` (for example). And it should be as easy to use as if it was in core keras. Just the import will differ. `from swish import Swish` instead of `from keras.layers import Swish`.
