### ISSUE TITLE
load_model error with Lambda and custom loss function 

### ISSUE THREAD

**Issue by world4jason** [keras-team/keras#11821]
keras 2.0.8, tf1.4

my loss is written something like this:

def segnet_loss_graph(y_true, y_pred):
    return K.categorical_crossentropy(y_true, y_pred)

and the code is:
segnet_loss = KL.Lambda(
                    lambda x: segnet_loss_graph(*x), name="segnet_loss")(
                        [input_gt_segmap,seg_score_map])
outputs = [segnet_loss]
model = KM.Model(inputs, outputs, name='multi_task_segment')

and loss is adding like this

keras_model.add_loss(loss)

=======
cuz i save the weights and structure, i load model directly
keras.callbacks.ModelCheckpoint(checkpoint_path, verbose=0, save_weights_only=False)
...
...
here is the inference code
from keras.models import load_model
import tensorflow as tf
import keras
import keras.losses
 keras.losses.custom_loss ="segnet_loss"
custom_objects= {
    "backend":keras.backend,
    "tf": tf,
    "segnet_loss_graph": segnet_loss_graph
}

model = load_model(model_path,custom_objects=custom_objects)

it's no use if i change "segnet_loss_graph": segnet_loss_graph to any of the following stuff
"segnet_loss": segnet_loss_graph
"segnet_loss": lambda x: segnet_loss_graph(**x)
"segnet_loss_graph": lambda x: segnet_loss_graph(**x)

the error will be following appears with different parameter i pass

1.ValueError: The model cannot be compiled because it has no loss to optimize.
2.NameError: name 'segnet_loss_graph' is not defined
3.TypeError: 'NoneType' object is not callable

is there any hints to solve this problem????

**Comment by asuiu** [comment]
@world4jason 
It looks like that's expected behavior as replacing the  `segnet_loss_graph` with `segnet_loss` in `custom_objects` dict means removing  the `segnet_loss_graph` - that wouldn't let Keras properly find and deserialize the loss function.
The 3rd replacement, though having the `"segnet_loss_graph": lambda x: segnet_loss_graph(**x)`, receives a malformed lambda function, as the loss expects two arguments and the lambda function can receive just one.
So, it looks like there's no problem here, or at least no properly formulated problem - i.e. why replacing the `segnet_loss_graph` by other key shouldn't throw exception.
@gabrieldemarmiesse  this issue probably can be closed.
