### ISSUE TITLE
Parameterize threshold for class prediction in Sequential model

### ISSUE THREAD

**Issue by yagotome** [keras-team/keras#11968]
Hi there!

I wonder if it is possible to parameterize this threshold (hardcoded as `0.5`):

https://github.com/keras-team/keras/blob/e11c48d9ce3ee47bb8a966549b14cbd5b10ee70d/keras/engine/sequential.py#L271

Sometimes we intend to try different thresholds than common `0.5`. I suppose this would be the case in which that value could be the default for a possible `threshold` param.

**Comment by gabrieldemarmiesse** [comment]
I believe that the function is small enough so that you can rewrite it yourself. I understand the use case and it's valid, but we can't accept every request or it would bloat the API. I suggest that, since the workaround is writing a 4 lines function, we go with this solution rather than changing the API.

**Comment by yagotome** [comment]
@gabrieldemarmiesse I understand your point. However, following that logic, the function should not even exist. Right? If the function remains, I think it'd be better it supports threshold pass. Wouldn't it?

Anyway, it's not a big deal writing that function on my projects.
Thank you!
