### ISSUE TITLE
Feature Request: Check for `_keras_dir` (`.keras`) in current working directory

### ISSUE THREAD

**Issue by loisaidasam** [keras-team/keras#12063]
Currently, if `KERAS_HOME` is explicitly set, `_keras_dir` will use that value.

Otherwise, it defaults to the user's home directory (`~`) with a fallback to `/tmp`.

What I'm proposing is checking for a `.keras` directory in the current working directory before defaulting to `~` or falling back to `/tmp`.

This change would make switching between backends and other specific configs for different projects much simpler!

Here is the current workflow:

https://github.com/keras-team/keras/blob/3fa96cf36f049efd6cf077f2812ba67ef8736d56/keras/backend/__init__.py#L16-L24

If this ticket gets approved I'm happy to submit a PR.

**Comment by gabrieldemarmiesse** [comment]
What is the use case for this? If you want to quickly change the config (and directories) what prevents you from using the environement variable?

**Comment by dimitry-ishenko** [comment]
What's the proper way to access `_keras_dir` from within user code, since it can either be `~`, `/tmp` or `$KERAS_HOME`?

I am asking because this is where `keras.utils.get_file()` saves/extracts files to. Even if I pass absolute path in `fname` with `extract = True` the file is extracted inside `_keras_dir + "/datasets"`.

**Comment by RoyiAvital** [comment]
Any way to control it on the Python script itself and not by a system variable?
How does it work on Windows?
