### ISSUE TITLE
Enhancement : Add ipython notebooks to examples folder

### ISSUE THREAD

**Issue by SriRangaTarun** [keras-team/keras#12129]
I think notebook versions of the current Keras examples, with the outputs and visualizations, should be included. I think it will help Keras newcomers a lot in understanding exactly what's happening.
I have almost all the examples on my local machine as .ipynb files (I had to copy paste parts of the code into notebooks manually). I can organize them into folders like "sequence-modeling-examples", "vision-models-examples" etc and add them to the current examples folder, if the people concerned approve of this idea.

- [y] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [y] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [n] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gabrieldemarmiesse** [comment]
I would be agains this because git / github doesn't play nicely with notebooks. It would be really hard to maintain. Plus, we cannot use checks like Pytest-pep8. Git diff and git blame are not usable with notebooks. I like notebooks, but since we don't have a lot of manpower in the keras-team, we need to work with tools which make this repo easy to maintain.
