### ISSUE TITLE
What is the relationship between this keras and the tf.kreas of TensorFlow2.0?

### ISSUE THREAD

**Issue by becauseofAI** [keras-team/keras#12143]

**Comment by gabrieldemarmiesse** [comment]
tf.keras appeared way before tensorflow 2.0. I think it was there since TF1.9 if I remember correctly.

The two codebases are different. tf.keras is made by the tensorflow team (and François Chollet) and maintained by the tensorflow team. Keras is made by François Chollet and maintained by the keras team. tf.keras can handle only one backend (TF) but keras-team/keras can handle abitrary backends (TF, theano, CNTK, mxnet, numpy...) It's easy to implement a new backend for it. The API are supposed to be compatible. tf.keras has more tf specific features I would say. Model saved with keras can be loaded with tf.keras and the other way around too.

**Comment by wangyexiang** [comment]
numpy backend？ @gabrieldemarmiesse

**Comment by gabrieldemarmiesse** [comment]
See https://github.com/keras-team/keras/issues/11068
