### ISSUE TITLE
Feature Request : Add automatic PEP8 formatter to travis.yml

### ISSUE THREAD

**Issue by SriRangaTarun** [keras-team/keras#12141]
I propose that the Travis CI Build should automatically format the files changed or added based on PEP8 guidelines before starting. Does this make sense ? Is it possible ?

Thank you!

- [y] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [y] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [n] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gabrieldemarmiesse** [comment]
This is not possible because travis cannot commit and push. That would be very hacky and autopep8 cannot handle all cases. It's going to confuse contributors if they see code modifications which are not their own. With a decent text editor/IDE, it's very easy to catch pep8 errors as you write your python code.
