### ISSUE TITLE
Understanding LSTM timesteps

### ISSUE THREAD

**Issue by Mark531** [keras-team/keras#12325]
I know this question is recurrent (no pun intended), but I still can't find a clear and definitive answer on github, blogs or stackoverflow.

There is much misconception about the timesteps dimension. So, my question will be very simple: if I have an univariate time series, is it right or wrong to use a LSTM layer with a timestep of 1?

Behind this question, there is also much misconception about the units parameter. From what I read here and there, in LSTM schemas (for instance http://colah.github.io/posts/2015-08-Understanding-LSTMs/img/LSTM3-chain.png), the number of inputs represents the timesteps dimension. But what would be the number of units then? A schema in keras documentation would make everything clear.

**Comment by tranvohuy** [comment]
I believe that I had the same questions as you. Now, I think I understand it.

> if I have an univariate time series, is it right or wrong to use a LSTM layer with a timestep of 1?
You can either take timestep = 1 or any other numbers.

If I understand correctly, the definition of univariate time series is as follows
> Definition. A univariate time series is a sequence of measurements of the same variable collected over time.  Most often, the measurements are made at regular time intervals.

If you take timestep = 4, it means you use 4 consecutive measurement to predict next measurement(s).

> But what would be the number of units then? A schema in keras documentation would make everything clear.

- `units` is the dimension of `h_t`, `h_{t-1}`, etc.  
- If we set `state_ful = True` in `keras.layers.lstm`, we have to set `units=` the dimension of `x_t`,`x_{t-1}`,`x_{t-2}`,... which is `=input_dim`.
  - [Because](https://keras.io/layers/recurrent/#lstm) `stateful: Boolean (default False). If True, the last state for each sample at index i in a batch will be used as initial state for the sample of index i in the following batch.`

**Comment by Mark531** [comment]
Thanks for your reply, but a schema would make things clearer. From what I understand, timesteps are rather used to model sequences (for instance sentences made of words), not univariate time series.

**Comment by tranvohuy** [comment]
I agree that the document is hard to understand for beginners/ self-learners.
