### ISSUE TITLE
implement adabound in keras

### ISSUE THREAD

**Issue by fayeshine** [keras-team/keras#12352]
could anyone implement a keras version of adabound?
https://github.com/Luolc/AdaBound

**Comment by zachmayer** [comment]
Check out https://github.com/titu1994/keras-adabound/issues/new

**Comment by zachmayer** [comment]
https://github.com/titu1994/keras-adabound/issues/1

**Comment by titu1994** [comment]
@zachmayer  This cant be pushed here just yet. A major issue persists, such as the clipping portion using Tensorflow directly instead of Keras backend clip function.

Once Keras clip function stops doing the "python float" checks and instead allows Tensors for the Tensorflow backend, then it can probably be merged.

**Comment by zachmayer** [comment]
That makes sense, thanks for the info!

**Comment by iperov** [comment]
currently titu1994's version is wrong implementation
https://github.com/titu1994/keras-adabound/issues/4

**Comment by titu1994** [comment]
There was a serialization bug which affects retraining, which has been corrected in https://github.com/titu1994/keras-adabound/commit/09fc73ebdc976f260554caa39234e81a6cf4e167

**Comment by iperov** [comment]
no, all works fine, my bad =(

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
