### ISSUE TITLE
How to design a many-to-many LSTM?

### ISSUE THREAD

**Issue by bestazad** [keras-team/keras#12395]
I have an input array of shape (1000,20, 4) and output(labels) of shape (1000,25,1). But don't know how to use Keras LSTM library to build a sequential model for this!

Can someone help me design a simple LSTM for doing that? (I tried to use `RepeatVector()` and `TimeDistributed(Dense())` in several ways but I get errors like the following:

    model = Sequential()
    model.add(LSTM(units = un , input_shape = (20, 4), return_sequences = False)) 
    model.add(RepeatVector(25))  
    model.add(LSTM(un , return_sequences=True))
    model.add(TimeDistributed(Dense(20))) 
     

> ValueError: Error when checking target: expected lstm_419 to have
> shape (25, 20) but got array with shape (25, 1)

**Comment by tranvohuy** [comment]
I hope I can answer your question. To put things in a context, suppose the output shape after an LSTM is 
`(None,  it, id)`. 

Then we add `model.add(TimeDistributed(Dense(n))`. If you type `model.summary()`, you will see that 
 - the number of extra-parameters is `(id+1) * n`. 
   - This is because we have `n` vectors of dimension `id` plus a bias number for each vector.
  - Each of these vectors is multiplied with `your_input[ sample_index, time_step_index, :]` plus a bias number with `time_step_index` from 1 to `it`.
 - The output shape after TimeDistributed(Dense(n)) is `(None, it, n)`

In your case, the final output shape  is `(None, 25, 20)` whereas your expected output shape is `(None, 25,1)`. That gives a contradition.

Depending on your purpose, you may change your network to
```
model = Sequential()
model.add(LSTM(units = un , input_shape = (20, 4), return_sequences = False)) 
model.add(RepeatVector(25))  
model.add(LSTM(un , return_sequences=True))
model.add(TimeDistributed(Dense(1))) 
```
It seems that you are doing 'Encoder-Deconder' network, doesn't it?
