### ISSUE TITLE
Celery with keras hangs in execution

### ISSUE THREAD

**Issue by Narzhan** [keras-team/keras#12531]
### Setup:
Keras 2.2.4, Tensorflow 1.13.1, Celery 4.2.2 running in Docker on Python 3.6

### Scenario
I'm running a Celery worker which handless ml requests for prediction using LSTM NN. I'm loading the model in a main worker which passes it to the worker tasks so that the model is not loaded all the time in a concurrent setup. 

### Problem
When the request comes the execution hangs indefinitely.  I've searched for a solution and found that the sessions cannot be shared across process which is the cause of the hang. I've tried several solutions which are mentioned lower. However none of the worked for me. Is there any other solution for this issue or I have to keep loading model in worker who uses it for prediction? Or I am doing something wrong?  

### Code (Simplified)
```
main.py

from keras.models import load_model
from celery import Celery, states
from celery import Task
class DomainAnalyzer(Task):
    ignore_result = True
    def __init__(self):
        self.model = load_model("lstm_model.h5")

    def run(self, data):
        try:
            preprocessor = Preprocessor(data, self.model)
            data = preprocessor.predict_data()
            return data 
        except Exception as e:
            self.update_state(
                state=states.FAILURE,
                meta=e
            )

app = Celery('worker', broker="broker")
app.register_task(DomainAnalyzer())

if __name__ == '__main__':
    app.start()
```
```
worker.py

class Preprocessor:

    def __init__(self, data: str, model):
        self.data= data
        self.model = model

    def data_analysis(self):
        return self.model.predict(self.data)
```

### Tried solution 1.
I've specified the multiprocessing start method. 
`multiprocessing.set_start_method('spawn', force=True)`

### Tried solution 2.
Passing graph object in worker
```
import tensorflow as tf
self.model = load_model("lstm_model.h5")
self.model._make_predict_function()
self.graph = tf.get_default_graph()
preprocessor = Preprocessor(data, self.model, self.graph)
```

In worker:
```
def data_analysis(self):
     with self.graph.as_default():
         return self.model.predict(self.data)

```

**Comment by alexwwang** [comment]
I tried solution 2, and made model, graph as global vars, which seemed work.

**Comment by Narzhan** [comment]
@alexwwang Did you use the same minimal example or have you made any changes. It seems quite strange that it should work for you when for me it didn't

**Comment by alexwwang** [comment]
@Narzhan Indeed there're some changes I made. 

I borrowed your thought to pre-build the predict function and split out the default graph. And then, which I think are the changes I made, I claimed the model and the graph as global vars and defined a customer process with `worker_init` decorator imported from `celery.signals` so that celery would load these vars into each worker.  The only shortage of this implementation is that the model takes up n times memory than a single one (n = number of workers).

And in case the worker init process timeout because usually it takes a longer time to load deep model into memory than other init tasks, you should also import `asynpool` from `celery.concurrency` and then set `asynpool.PROC_ALIVE_TIMEOUT` to a larger number, say 100,  which default value is 4 as for 4 seconds.

I checked below SO question as reference, which may be much helpful to you:
[No response from celery worker with TensorFlow](https://stackoverflow.com/questions/41734275/no-response-from-celery-worker-with-tensorflow)
