### ISSUE TITLE
Buffered data was truncated after reaching the output size limit.

### ISSUE THREAD

**Issue by sauronpy** [keras-team/keras#12549]
when training process is going forward, suddenly this error appears.

can anyone tell me what is the problem??

i have 12gig graphic memory (VRAM) and this problem is not related to graphic hardware.

this problem, one time appears in epoch 120 and another time appears in epoch 50, and one time do not appears at all.
`17024/50000 [=========>....................] - ETA: 1:50 - loss: 0.1026 - acc: 0.9705 - top3_acc: 0.9991Buffered data was truncated after reaching the output size limit.
`

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/keras-team/keras/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. Thank you for your cooperation.
