### ISSUE TITLE
model.fit_generator faied with unsupported operand type(s) for *: 'Dimension' and 'float'

### ISSUE THREAD

**Issue by TianLin0509** [keras-team/keras#12578]
I'm troubled with a strange problem while using keras.
I have succeesfully used model.fit() to trian my model. Then, I want to speed up it and thus I use model.fit_generator(). However, I faild and the error is listed as follows:
```
Traceback (most recent call last):
  File "E:/deepmodel/main.py", line 100, in <module>
    model.fit_generator(generator=next_batch(), steps_per_epoch=50, verbose=1, epochs=10)
  File "C:\Users\17210\AppData\Local\conda\conda\envs\GPUDL\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\17210\AppData\Local\conda\conda\envs\GPUDL\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 183, in fit_generator
    callbacks.on_batch_end(batch_index, batch_logs)
  File "C:\Users\17210\AppData\Local\conda\conda\envs\GPUDL\lib\site-packages\tensorflow\python\keras\callbacks.py", line 249, in on_batch_end
    callback.on_batch_end(batch, logs)
  File "C:\Users\17210\AppData\Local\conda\conda\envs\GPUDL\lib\site-packages\tensorflow\python\keras\callbacks.py", line 375, in on_batch_end
    self.totals[k] = v * batch_size
  File "C:\Users\17210\AppData\Local\conda\conda\envs\GPUDL\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 260, in __rmul__
    return self * other
TypeError: unsupported operand type(s) for *: 'Dimension' and 'float'
```

I'm really puzzled and when I go to callbacks.py, actually 
```
  def on_batch_end(self, batch, logs=None):
    logs = logs or {}
    batch_size = logs.get('size', 0)
    # In case of distribution strategy we can potentially run multiple steps
    # at the same time, we should account for that in the `seen` calculation.
    num_steps = logs.get('num_steps', 1)
    self.seen += batch_size * num_steps

    for k, v in logs.items():
      if k in self.stateful_metrics:
        self.totals[k] = v
      else:
        if k in self.totals:
          self.totals[k] += v * batch_size
        else:
          self.totals[k] = v * batch_size
```
The problem is that batch_size is Dimension(2048) (as in the generator I use batch_size 2048). I think it leads to the TypeError, however, I don't know what cause it and how to avoid it.

Besides, I also debug with using model.fit(), and then the batch_size in the function ```on_batch_end``` is equal to 1, thus nothing unexpected happend.

**Comment by benoitkoenig** [comment]
Hi,
I face the same issue: when calling model.fit, I have no error - when calling model.fit_generator, I get "TypeError: unsupported operand type(s) for *: 'Dimension' and 'float'"
In the method on_batch_end in keras.callbacks -> BaseLogger (copied in @TianLin0509 post), upon printing (k, v), I have the following values:
batch 0
size 1
loss 1.4004756
Upon calling print(type(batch_size)), it turns out that batch_size is of type <class 'int'> when calling model.fit, and of type <class 'tensorflow.python.framework.tensor_shape.Dimension'> when calling model.fit_generator. Hence the error when trying to multiply the loss (float) by the batch_size (Dimension)
Let's take a look at the definition of batch_size in keras.engine.train_generator.py, line 201-210:
`
if x is None or len(x) == 0:
    # Handle data tensors support when no input given
    # step-size = 1 for data tensors
    batch_size = 1
elif isinstance(x, list):
    batch_size = x[0].shape[0]
elif isinstance(x, dict):
    batch_size = list(x.values())[0].shape[0]
else:
    batch_size = x.shape[0]
`
Aaaaaand here is the error. batch_size is, depending on the case, either an int or a Dimension. The right fix is to cast the shapes as int:
`
if x is None or len(x) == 0:
    # Handle data tensors support when no input given
    # step-size = 1 for data tensors
    batch_size = 1
elif isinstance(x, list):
    batch_size = int(x[0].shape[0])
elif isinstance(x, dict):
    batch_size = int(list(x.values())[0].shape[0])
else:
    batch_size = int(x.shape[0])
`

After this edition, I could run fit_generator in local
Can anybody please double-check that this is the right fix, and create the pull request? Thanks =)

**Comment by benoitkoenig** [comment]
Hi,
The label here should be updated to bug. Can anyone confirm and do it please?

**Comment by saketrule** [comment]
I'm getting a similar error.
