### ISSUE TITLE
I wonder why there is no '==' or '!=' operand among tensor, but exists '>=', '<=', '>' etc, which is not so harmonious.

### ISSUE THREAD

**Issue by codingpy** [keras-team/keras#12687]
**System information**  
- Have I written custom code:  `no`
- OS Platform and Distribution:  `Linux Centos 7`
- TensorFlow backend:  `yes`
- TensorFlow version:  `1.13.1`
- Keras version:  `2.2.4`
- Python version:  `3.7.2`
- CUDA/cuDNN version:  `no`
- GPU model and memory:  `no`

```python
import numpy as np
from tensorflow.keras import backend as K

x = K.variable(np.arange(9).reshape(3, 3))
y = x - 1

z = x >=y     # yes, it returns tf.Tensor object
z = x == y    # it doesn't return tf.Tensor which is what I want, but returns False
z = x != y     # ditto
``` 

I know that, there exists K.equal and K.not_equal.
However, what I am concerned about is the disharmony ...

**Comment by ziyigogogo** [comment]
python language "x==y" means compare the value, "x is y" means compare the object.
java language "x==y" means compare the object and "x.equals(y)" means compare the value

However, as your test, in tensorflow, seems that "==" means compare the object which is more like a java way.
I dont know why this happen, maybe there are some hidden thoughts about the multi-platform support.
So, in case some misunderstanding, you'd better use tf.equal()/not_equal for better code readability.

Correct me if i was wrong.

**Comment by xunnv** [comment]
Thanks for your reply, but that isn't what I want, maybe I didn't make it clear.

In NumPy, I can do these:
```python
>>> import numpy as np
>>> x = np.array([1, 2, 3])
>>> x
array([1, 2, 3])
>>> y = np.array([2, 3, 5])
>>> x == y
array([False, False, False])
```

But in Keras I couldn't, maybe this is because the underlying limit. However, I think it is would be nice to add these features into Keras or TensorFlow, whithout specifically calling the `equal` or `not_equal`.

Moreover, I think override the `__eq__` and `__ne__` can fix this, isn't it right?
