### ISSUE TITLE
No documentation for array_to_img, img_to_array and save_img under preprocessing.image 

### ISSUE THREAD

**Issue by siddheshsathe** [keras-team/keras#12711]
There's no documentation for functions mentioned below in keras repo. It's there under keras pre-processing repo.
Find the below functions under `keras/preprocessing/image.py`

1. `array_to_img`
2. `img_to_array`
3. `save_img`

Thank you!

**Comment by mathemage** [comment]
Hi!

@siddheshsathe @jvishnuvardhan Is this PR still open? I'd love to join the Keras and contribute but I have hard times to orient myself in [Good first issues page](https://github.com/keras-team/keras/contribute).

I can start with this PR on `docs/` if it's still relevant. Please let me know in both cases so that I can start working on it. Thanks!

**Comment by siddheshsathe** [comment]
Sure @mathemage , you can go ahead.

Thanks

**Comment by mani2106** [comment]
The last three lines in `keras/preprocessing/image.py` copies the docstrings from the parent method right?

`array_to_img.__doc__ = image.array_to_img.__doc__`
`img_to_array.__doc__ = image.img_to_array.__doc__`
`save_img.__doc__ = image.save_img.__doc__`

**Comment by mathemage** [comment]
> Sure @mathemage , you can go ahead.
> 
> Thanks

Hi @siddheshsathe ! 
Thanks! I will get back to this in 2 weeks. I have a hard exam now.
Thanks for understanding!

**Comment by siddheshsathe** [comment]
@mani2106 , @mathemage 
FYI:
Keras have moved their pre-processing repo from this [keras](https://github.com/keras-team/keras) to [keras-preprocessing](https://github.com/keras-team/keras-preprocessing).
I guess, they already have a documentation at keras-preprocessing repo. We (probably) just need to add the same here.

**Comment by mani2106** [comment]
@mathemage Is your exam over?
Do you need more time to take this on?

**Comment by mathemage** [comment]
@mani2106 Yes, my exam is over. I can get back to it on Thursday if that's okay. I still have some things to finish first, but then I'd have time. ^_^ -> Is it alright like this?

Thanks for remembering me!

**Comment by mani2106** [comment]
Ok man, No worries.

**Comment by mathemage** [comment]
Hi @mani2106 and @siddheshsathe 

I've started to look into and currently working on this. Today I was struggling with the setup: right Python env, my GH fork got behind -> some syncing troubles etc. I will continue in the following days.

Is there any convention on how to create forks/pull requests? And how to name the branches/reference issues? I.e. anything procedural that needs to be done before the work on the issue itself?

Thanks,
@mathemage

**Comment by mathemage** [comment]
> I've started to look into and currently working on this. Today I was struggling with the setup: right Python env, my GH fork got behind -> some syncing troubles etc. I will continue in the following days.

Is it alright if I use (virtualenv) with Python 3.7?
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
```
I can't find an easy way to install Python 3.6 on Ubuntu 19.04. :-1:

**Comment by mani2106** [comment]
> Is there any convention on how to create forks/pull requests? And how to name the branches/reference issues? I.e. anything procedural that needs to be done before the work on the issue itself?

You can refer to the [Contributing README](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for these.

And regarding the addition of documentation as @siddheshsathe suggested, you can find the needed docstrings [here](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/utils.py)

- `save_img`: [Permalink](https://github.com/keras-team/keras-preprocessing/blob/095aea9a029d52af618f3b1e8a4f93ef83f51d91/keras_preprocessing/image/utils.py#L50)

- 'img_to_array': [Permalink](https://github.com/keras-team/keras-preprocessing/blob/095aea9a029d52af618f3b1e8a4f93ef83f51d91/keras_preprocessing/image/utils.py#L279)

- 'array_to_img': [Permalink](https://github.com/keras-team/keras-preprocessing/blob/095aea9a029d52af618f3b1e8a4f93ef83f51d91/keras_preprocessing/image/utils.py#L226)

I do not know if you really need to set up the development environment for adding docstrings, because you can just copy-paste the docstrings from the specified locations in your fork

**Comment by mathemage** [comment]
Hi @siddheshsathe and @mani2106 !

I've added the docstrings and created the PR #13252 . You can check it out there.

What's the next step?

Thanks for your support and help,
Karel

**Comment by siddheshsathe** [comment]
Closing the issue.
#13252
