### ISSUE TITLE
Input np.array as input layer

### ISSUE THREAD

**Issue by karanpareek96** [keras-team/keras#12735]
Hi,

I'm currently using two models, one that takes in a Numpy array and generates an audio file using Tensorflow and the other that inputs these audio files for further processing. I tried using _z -= Input(shape=(1, 100))_ but I get an error stating that I cannot input a tf.object into a given Tensorflow graph.

Is there any way that I can transform my input layers in Keras into a numpy array?

Thanks!

**Comment by psschand** [comment]
Hi, your problem looks similar to [this](https://github.com/tensorflow/tensorflow/issues/4842) Were you able to solve it?

**Comment by jvishnuvardhan** [comment]
Please fill the issue [template](https://github.com/keras-team/keras/issues/new?template=a--tensorflow-backend-users.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by karanpareek96** [comment]
@jvishnuvardhan I think the issue is solved now. I must have made some typo. The link provided by @psschand really helped me. Thanks a lot!
