### ISSUE TITLE
Fully featured AugmentLayer

### ISSUE THREAD

**Issue by rohit-gupta** [keras-team/keras#12772]
It is noted in [this example using CIFAR10](https://keras.io/examples/cifar10_cnn_tfaugment2d/) that the AugmentLayer defined here has an order of magnitude better performance than ImageDataGenerator. However the layer only defines flips and rotation, and I was wondering that a fully featured ImageAugmentLayer would be a very useful addition to Keras.

**Comment by jvishnuvardhan** [comment]
Please fill the issue template[here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by rohit-gupta** [comment]
Hi @jvishnuvardhan this is more of a feature request than an issue !

**Comment by hr21** [comment]
@rohit-gupta I agree to your point mentioned abouve that augmented layer would give better results but don't you think it could even scale up problems like more training time and more problems in designing custom neural network architechture if someone moves towards tasks like segmantation. I guess we still need to think about this issue
