### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by strivehub** [keras-team/keras#12908]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Mr.Wang\\.keras\\datasets\\cifar-10-batches-py\\data_batch_1'

I‘m using this code "cifar10.load_data()"
but when I run get this error

**Comment by RohitMidha23** [comment]
[This](https://github.com/keras-team/keras/issues/1425) might help you.

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/keras-team/keras/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
