### ISSUE TITLE
keys of custom_objects in load_model

### ISSUE THREAD

**Issue by PythonImageDeveloper** [keras-team/keras#12934]
Hi
Suppose we have this structure:
```
model = load_model(model_path, custom_objects={'AnchorBoxes': AnchorBoxes,
                                               'L2Normalization': L2Normalization,
                                               'DecodeDetections': DecodeDetections})
```
The name of keys of custom_objects are arbitrary or they are the name of custom_objects are defined before in the model structure?

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/keras-team/keras/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
