### ISSUE TITLE
Having problem to use the Reshape in Keras

### ISSUE THREAD

**Issue by Ray322417** [keras-team/keras#12964]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.24-tf
- Python version:  3.6.8
- CUDA/cuDNN version:  10.0
- GPU model and memory:  GeForce GTX 750 Ti

**Describe the current behavior**  
When using Reshape layer of Keras and -1 is used to infer the shape, the output shape is incorrect.
**Describe the expected behavior**  

**Code to reproduce the issue**  
`from tensorflow.python.keras.layers import Input, Lambda, Conv2D, Reshape, TimeDistributed`
`from tensorflow.python.keras.models import *`
`import tensorflow.keras as keras`

`a = Input(shape=(12,), dtype = 'int32')`
`# a.shape == (None, 12)`
`d = Reshape((-1, 2, 2))(a)`
`# actual result： d.shape == (None, None, 2, 2)`
`# expected result： d.shape == (None, 3, 2, 2)`

**Comment by jvishnuvardhan** [comment]
I was able to reproduce the issue. GitHub gist is [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/fc8e025632d4dfc55f343a256a166a05/keras_shape_inference_issue12964.ipynb). I have tried the same with TF2.0-beta also and the result is same. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/b551a74b2025da01a761880c5b991b5e/untitled251.ipynb) . Thanks!

**Comment by vineetred** [comment]
Issue seems to persist even after using K.reshape.
``` from tensorflow.python.keras.layers import Input, Lambda, Conv2D, Reshape, TimeDistributed
from tensorflow.python.keras.models import *
import tensorflow.keras as keras
from keras import backend as K

a = Input(shape=(12,), dtype = 'int32')
d = K.reshape(a,(-1, 2, 2))
```

**Comment by Xiadalei** [comment]
Reshape layer use `tf.reshape()` when using tensorflow backend and `tf.reshape()` won't deduce the shape when two undetermined dims are presented. 
That's what happened when you use -1 in reshape because the batch channel is also undetermined.
 (Code)[https://github.com/keras-team/keras/blob/9080613dbc6f0840d7544bccc416121f0864a7fd/keras/layers/core.py#L402] here indicate that they already put batch channel in the reshape so adding another -1 for shape prediction is impossible.
