### ISSUE TITLE
Conver Keras Model to ONNX

### ISSUE THREAD

**Issue by alijalali81** [keras-team/keras#12962]
<em>I am trying to use onnx convertor to convert a kears model. When I try to import keras2onnx I get this message:

AttributeError: module 'keras.layers' has no attribute 'DepthwiseConv2D'

Any idea how to deal with this?

**Comment by jvishnuvardhan** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
