### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamidmumtaz** [keras-team/keras#12996]
i'm training a model like so:

model = Sequential()

model.add(LSTM(32, input_shape=(100, 20), unroll= False, return_sequences=True))

#model.add(LSTM(n_units, input_shape=(time_steps,n_inputs))) #model.add(Dense(3, activation='softmax')) model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

model.summary()

model.fit(x,y, nb_epoch=50, batch_size=32, verbose = 2)

this error get how to solve please #150 images size is 100*20 and 3 class labels

ValueError: Error when checking target: expected lstm_27 to have 3 dimensions, but got array with shape (150, 1)

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/keras-team/keras/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your coop
