### ISSUE TITLE
different result with same code,same data when run dssm model

### ISSUE THREAD

**Issue by liumilan** [keras-team/keras#13015]
different result with same code,same data when run dssm model using keras.How could it perhas happen? Using the incorrect model to predict,the output value is all the same

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/keras-team/keras/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
