### ISSUE TITLE
is it possible for continues training in keras for multiclass classification for new class?

### ISSUE THREAD

**Issue by MuruganR96** [keras-team/keras#13024]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- Linux Ubuntu 16.04  
- TensorFlow backend yes
- TensorFlow version:  ''v1.13.1-0-g6612da8951' 1.13.1
- Keras version:  2.2.4
- Python version: 3.6.8
- CUDA/cuDNN version:  CUDA 10.0
- GPU model and memory:  4 GB

i was tried continues training in keras.
because i was build keras multiclass classification model, after i have new labels, and values. so i want to build new model without retraining. that is why i tried continuous train in keras. 

```
    model.add(Dense(10, activation='sigmoid'))

    model.compile(optimizer='rmsprop',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])
    
    
    model.fit(training_data, labels, epochs=20, batch_size=1)

    model.save("keras_model.h5")
```
after completing save the model , i want to do continues training. so i tried,

```

    model1 = load_model("keras_model.h5")
    model1.fit(new_input, new_label, epochs=20, batch_size=1)
    model1.save("keras_model.h5")
```
i tried this. but it was thrown error.like previously 10 classes. 

but now we add new class means error occurred.

so what is my question is, **is it possible for continues training in keras for multiclass classification for new class?**
```

tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of 10 which is outside the valid range of [0, 9).  Label values: 10
	 [[{{node loss/dense_7_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
```

Thank you :)

**Comment by dabasajay** [comment]
Hello Murugan R, in your case the model was trained to classify only 10 classes (i.e. the number of units in the output layer is 10). Now that you've added a new class, you have 11 classes so you've to change the output units of the last layer to 11 and then you can maybe load the same weights for all layers except output layer and freeze the weights but use new weights for output layer and retrain the network. Note that this may or may not work because earlier layers may not know how to interpret features for the newly added label.
Further reading on this topic: https://developer.amazon.com/blogs/alexa/post/6058f7e9-1de8-4e51-8f50-aee56e29f3ce/updating-neural-networks-to-recognize-new-categories-with-minimal-retraining

**Comment by jvishnuvardhan** [comment]
@MuruganR96 Adding on top of @dabasajay , if the original model was trained for classifying 10 different classes of images of dog breeds, you can add one more class in the end (11 breeds instead of 10) and train with your data to update weights for the last layer. But, if you want to use the original model  (classifying 10 dog breeds) for classifying X-ray images (entirely different from the actual purpose of the original model) of 11 classes, then you need to train few more layers in the end and then train with your data. Please check the [resource here](https://machinelearningmastery.com/how-to-use-transfer-learning-when-developing-convolutional-neural-network-models/).  There are several other great resources if you need any more help. thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
