### ISSUE TITLE
model.layers.pop() fails to pop the input layer

### ISSUE THREAD

**Issue by dsouzinator** [keras-team/keras#13702]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   google colab
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.1.0-rc1
- Keras version:  2.2.5
- Python version:  
- CUDA/cuDNN version:  
- GPU model and memory:  

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
The code `model.layers.pop(0)`
doesn't pop the input layer as expected, it still shows the input layer in summary

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 450, 450, 3) 0                                            
__________________________________________________________________________________________________

**Describe the expected behavior**  
This issue is not present in Tensorflow 1.x with keras,  that works as expected

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

```
%tensorflow_version 2.x
from tensorflow.keras.applications.inception_v3 import InceptionV3
base_model = InceptionV3(weights= 'imagenet', include_top=False, input_shape= (450,450,3))
base_model.layers.pop(0)
base_model.summary()

```

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by work-mohit** [comment]
just use base_model.layers.pop()
Instead of base_model.layers.pop(0)

**Comment by anerirana** [comment]
There have been changes in keras v2.x 

`model.layers` gives you an array of layers and pop() will just return you the element popped from the array at the specified index.

You have to use `model.pop() `to remove the last layer. I am not aware of any method to pop the intermediate layer in a sequential model. But, you can use this Functional API method to construct a new model. This will eliminate the input layer.

new_model = Model(inputs=base_model.layers[1].input, outputs= base_model.layers[-1].output)

**NOTE:** Unfortunately, creating a new model using functional API from layers of a sequential model is not actually supported. So you will not be able to see any layers in `summary()`. However the model does function as expected. Not sure if it is a different issue or the incompatibility between sequential model and functional model methods is intentional.
