### ISSUE TITLE
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build

### ISSUE THREAD

**Issue by Dhananjay201** [keras-team/keras#14230]
model = tf.keras.Sequential([
  layers.DenseFeatures(feature_columns),
  layers.Dense(128,activation='relu'),
  layers.Dropout(0.2),
  layers.Dense(512,activation='relu'),
  layers.Dropout(0.2),
  layers.Dense(512, activation='relu'),  
  layers.Dense(31,activation='softmax')
])

This is my model.How do i solve this issue or add input shape to the first layer? Please help

**Comment by ritika-singh2000** [comment]
@Dhananjay201 , I am new to open source and DL .I think I can work on this .Could you please assign me this?

**Comment by darthdaenerys** [comment]
T

> model = tf.keras.Sequential([ layers.DenseFeatures(feature_columns), layers.Dense(128,activation='relu'), layers.Dropout(0.2), layers.Dense(512,activation='relu'), layers.Dropout(0.2), layers.Dense(512, activation='relu'), layers.Dense(31,activation='softmax') ])
> 
> This is my model.How do i solve this issue or add input shape to the first layer? Please help

This error generates because the model doesn't know the shape of the inputs. To resolve this you can specify an input_shape parameter for the first layer DenseFeatures.

**Comment by heetkadia369** [comment]
model = tf.keras.Sequential([ layers.DenseFeatures(feature_columns), model.add(tf.keras.Input(shape(16,))),
layers.Dense(128,activation='relu'), 
layers.Dropout(0.2), 
layers.Dense(512,activation='relu'), 
layers.Dropout(0.2), 
layers.Dense(512, activation='relu'), 
layers.Dense(31,activation='softmax') ])

Check this now..... This error is common because model's input shape is sometimes undefine so there will be undefine output shape.
