### ISSUE TITLE
Keras configuration json and application model (cache) files folder needs to be parsed correctly on Windows in a worker process (such as IIS WSGI)

### ISSUE THREAD

**Issue by sunshinejnjn** [keras-team/keras#14288]
When running in a flask app using WSGI on IIS in a windows system, the keras config file and cache file directory parsed from the function "os.path.expanduser(os.path.join('~', '.keras'))" may expends to something like "C:\WINDOWS\system32\config\systemprofile\.keras" which is not quite a usual practice. Maybe a detection of platform and a temp folder such as from the system TEMP variable (usually expends to "C:\Windows\TEMP" would be a better idea?

**Comment by sushreebarsa** [comment]
@sunshinejnjn Is this still an issue?
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Please refer to this [link](https://keras.io/guides/serialization_and_saving/) and try with the latest TF versions(2.4 or later ) .Please let us know if it helps?Thanks!
