### ISSUE TITLE
Changing channel orientation of trained model

### ISSUE THREAD

**Issue by ardamavi** [keras-team/keras#14329]
I have a trained keras model (TF V2), which has a channel first orientation. How do I change this model to channel last orientation.

**Comment by sushreebarsa** [comment]
@ardamavi Is this still an issue?
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Could you please refer to this similar [issue](https://stackoverflow.com/questions/62482416/change-pre-trained-model-to-expect-channel-first-in-tensorflow) and try with the latest TF versions?
Thanks!
