### ISSUE TITLE
Problem in Keras metrics for true/false positives/negatives when using floats as input

### ISSUE THREAD

**Issue by FriedChips** [keras-team/keras#14399]
It seems to me that the Keras metrics for true/false positives do not work correctly with float inputs. Example:

`m = tf.keras.metrics.TruePositives(thresholds=0.5)`
`m.update_state([0.1], [0.9])`
`m.result().numpy()`

leads to the output:

`1.0`

This should be 0.0. Similar problems exist with the other positive/negative metrics.

Also, only input values in the range [-1,1] are supported. This restriction should not be necessary since the threshold removes all ambiguity.

**Comment by embattle12** [comment]
hey i would like to work on this project. i am new at this can anyone guide me through it, i would be greatful.

**Comment by sushreebarsa** [comment]
@FriedChips Sorry for the late response!
Could you please let us know if it is still an issue ?
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Please refer to the similar [issue](https://stackoverflow.com/questions/59305514/tensorflow-how-to-use-tf-keras-metrics-in-multiclass-classification) , Classification [metrics](https://keras.io/api/metrics/classification_metrics/#truepositives-class), [TF metrics ](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/TruePositives?hl=en) and try with latest TF v2.7.0 . Please let us know if it helps?Thanks!
