### ISSUE TITLE
resnext preprocess input using with lamda

### ISSUE THREAD

**Issue by nedimmuzoglu** [keras-team/keras#14439]
I want to use nesnext 50 .My problem is while using lamda function with defined -as process_resnext-preporcess input I get the error "data_format = backend.image_data_format() AttributeError: 'NoneType' object has no attribute 'image_data_format'"

My code is...

from keras_applications import resnext from keras_applications.resnext import preprocess_input as process_resnext rnx50 = resnext.ResNeXt50(weights = 'imagenet', include_top = False, input_shape = SHAPE)

inp = Input((224,224,3))

resnext50_process = Lambda(process_resnext)(inp)

data_format = backend.image_data_format() AttributeError: 'NoneType' object has no attribute 'image_data_format'

using keras 2.4.3 tf. 2.3.1 python 3.7.9

I am using spyder and there is no specific resnext module for resnext50 and also no specific preprocess input also for resnext50 in anaconda editor.I think problem is starting from here.(from keras_applications.resnext)

Also how to using resnext preprocesing input with lamda can be helpful for me.thanks.

**Comment by sushreebarsa** [comment]
@nedimmuzoglu We see that you're using old version of TF (2.3.1).TF 2.3 does not really contain all the changes to prevent code using invalid shapes from crashing the interpreter via CHECK-failures.  TF 2.3 is no longer supported.Its unlikely for TF 2.3 version to receive any bug fixes except when we have security patches. There is a high possibility that this was fixed with later TF versions. Perhaps you can use latest tf version **2.7.0** for your case and let us know if it helps? Thanks!
