### ISSUE TITLE
ValueError: Could not interpret optimizer identifier: <rl.util.AdditionalUpdatesOptimizer object at 0x0000026DBDBD5748>

### ISSUE THREAD

**Issue by kranthiakssy** [keras-team/keras#14646]
I tried running the keras reinforcement learning DDPG example at 
https://github.com/keras-rl/keras-rl/blob/master/examples/ddpg_pendulum.py.
When I run this code I'm getting the following error.
![Keras-rl_DDPG](https://user-images.githubusercontent.com/64199276/118388369-aad2c000-b641-11eb-9d15-50f621b9c7d6.png)
Kindly help me out to resolve the issue.

**Comment by ymodak** [comment]
You may want to raise this issue on https://github.com/keras-rl/keras-rl/issues for better support.
I suspect the error arises due to keras-rl dependency on keras. Its possible that latest keras packages are not compatible. Perhaps you want to stick last known supported version and try.
https://github.com/keras-rl/keras-rl/blob/216c3145f3dc4d17877be26ca2185ce7db462bad/setup.py#L12
Thanks!
