### ISSUE TITLE
Tree LSTM in Keras

### ISSUE THREAD

**Issue by nashid** [keras-team/keras#14643]
Tree-LSTM is implemented by Torch https://github.com/stanfordnlp/treelstm

Any update on developing Tree LSTM in keras?

I saw an old thread here https://github.com/keras-team/keras/issues/352.

**Comment by mattdangerw** [comment]
There's no one working on Tree LSTM in keras right now, but this would be a great spot for a contribution.

The place to start would probably be contributing this as an example on keras.io. Thanks!

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
