### ISSUE TITLE
Multiple generic_utils modules were used when loading model, which caused problems like "Unknown optimizer"

### ISSUE THREAD

**Issue by CyberZHG** [keras-team/keras#14724]
To reproduce:

* `Keras==2.4.3`
* `tensorflow==2.5.0`

```python
import keras


class RenamedOpt(keras.optimizers.Adam):
    pass
  
  
inputs = keras.Input(shape=(3,))
outputs = keras.layers.Dense(5)(inputs)
model = keras.models.Model(inputs, outputs)
model.compile(optimizer=RenamedOpt(), loss='mse')
keras.models.load_model('temp.h5', custom_objects={'RenamedOpt': RenamedOpt})
```

It will raise:

`ValueError: Unknown optimizer: RenamedOpt.`

When loading the optimizer, the custom objects were passed to the global dict in `keras.utils.generic_utils`:

https://github.com/keras-team/keras/blob/95c2966d9dd8b5ba67c9473bb1099a407f3b9bd7/keras/saving/saving_utils.py#L204-L206

But then it used the `deserialize` method in `tensorflow.python.keras`, which tried to find the global custom objects from `tensorflow.python.keras.utils.generic_utils`.

One possible quick fix is to explicitly pass the `custom_objects` argument to `deserialize` in line 206. 

For keras users, one workaround is to explicitly invoke the function in `tensorflow.python.keras`:

```python
from tensorflow.python.keras.utils.generic_utils import CustomObjectScope
    with CustomObjectScope({'RenamedOpt': RenamedOpt}):
        keras.models.load_model('temp.h5')
```

**Comment by sushreebarsa** [comment]
@CyberZHG Sorry for the late response! Could you please let us know if it is still an issue in TF latest version 2.7.0 ? Please try to use Use tf.keras.optimizers.Adam(learning_rate) instead of keras.optimizers.Adam(learning_rate) and refer to the [link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/optimizers/Optimizer) .Please let us know if it helps? Thanks!
