### ISSUE TITLE
Convert model with  `tensorflow.keras.layers.experimental.preprocessing` to TFLite

### ISSUE THREAD

**Issue by CaptainDario** [keras-team/keras#14872]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
It would be awesome if layers from `tensorflow.keras.layers.experimental.preprocessing` like `Resizing` would be convertable to TF Lite without implementing custom ops.

Currently a custom op definition is needed for (some of) them to work.
Especially Lanczos3 for Resizing would be nice.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
It would be very easy to add preprocessing inside a model. Therefore people who want to use those models do not need information about what input format should be used.

**Comment by sachinprasadhs** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from `keras-team/keras-core` to `keras-team/keras`.
Consequently, This issue may not be relevant to the `Keras 3` code base . After the migration is successfully completed, feel free to reopen this Issue at `keras-team/keras` if you believe it remains relevant to the `Keras 3` code base. If instead this Issue is a bug or security issue in legacy` tf.keras`, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the `TensorFlow-only`, legacy version of Keras.

To know more about `Keras 3`, please read https://keras.io/keras_core/announcement/
