### ISSUE TITLE
Saved model performance discrepancies for models with equivalent behavior

### ISSUE THREAD

**Issue by jg-lopes** [keras-team/keras#14888]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GPU model and memory: 
- Exact command to reproduce:

**Describe the problem**.

While loading similar models on Keras, we see significantly different RAM and timing performance given the structure of the Keras code defining the model. 

To test it, we decided to write a simple but heavy model with 250 Dense layers in order to showcase the overhead for each layer. The variations tested were as follows, with the top RAM consumption as well as time of execution:

1. 250 Dense layers w/o Activation (BASELINE) => 600 MB, 9s
2. 250 Dense layers w/ activation set as a parameter inside of the Dense call => 600MB, 9s
3. 250 Dense layers using Functional API, each layer followed by another activation layer => 710MB, 12s
4. One custom layer with one sequential layer containing all 250 Denses => 790MB, 12.2s
5. One custom layer w/ list of Dense layers as attributes, called using a for loop over the list (equivalent to Baseline) => 550MB, 7.5s

Notice that **1** has equivalent behavior to **4** and **5**. And **2** has equivalent behavior to **3**.

**Describe the current behavior**.

We noticed a considerable difference for equivalent models depending on the underlying structure of the Keras code. Notice that equivalent models have considerably different performances depending on how the calls to Keras were structured.

Notably regarding **1** and **5**, a model that was more sophisticated (with a Custom layer) actually caused a smaller memory and time consumption.

It should be noted that the size of the weights is equal between all of the models. Our expectation is that on loading it would be the weights that would dominate consumption (especially on memory), where experimentally that wasn't the case.

**Describe the expected behavior**.

We expected to have the equivalent/same order of magnitude performance for all equivalent models. Instead, there's significant performance differences.

In our use case, we do not control the runtime consumption constraints and we need to reduce memory footprint as much as possible.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): ?
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Colab code reproducing the tests describing the issue: https://colab.research.google.com/gist/tanguycdls/fee7c221484cf4ee0e3273faa8e270b0/memory-overhead-tests.ipynb

**Source code / logs**.

Source code can be accessed in the Colab notebook shared above.

cc @tanguycdls @maxime-gautre

**Comment by tanguycdls** [comment]
@haifeng-jin Do you have any idea on why we see that behavior: our models have a lot of inputs and so a lot of layers and currently the loading memory consumption is very large for what it is. We tried reducing the dtype quality but it does not reduce the ram enough.

**Comment by haifeng-jin** [comment]
@tanguycdls Do you have a notebook or something for me to reproduce this? I am not aware of this issue.

**Comment by tanguycdls** [comment]
@haifeng-jin thanks the colab is here: https://colab.research.google.com/gist/tanguycdls/fee7c221484cf4ee0e3273faa8e270b0/memory-overhead-tests.ipynb

In the test we can see that memory usage at loading time is not correlated to the dtype and the weights (all are similar) but to the actual structure of the code.
```
To test it, we decided to write a simple but heavy model with 250 Dense layers in order to showcase the overhead for each layer. The variations tested were as follows, with the top RAM consumption as well as time of execution:

1. 250 Dense layers w/o Activation (BASELINE) => 600 MB, 9s
2. 250 Dense layers w/ activation set as a parameter inside of the Dense call => 600MB, 9s
3. 250 Dense layers using Functional API, each layer followed by another activation layer => 710MB, 12s
4. One custom layer with one sequential layer containing all 250 Denses => 790MB, 12.2s
5. One custom layer w/ list of Dense layers as attributes, called using a for loop over the list (equivalent to Baseline) => 550MB, 7.5s

```

Here all the patterns are the same only the code writing is different, we clearly see that having layers in layers increase memory usage (1 vs 4 are strictly equivalent). Our hypothesis was that since each layer is wrapped into a tf function we have a bigger graph since each just calls the graph underneath while in option 4 we only have 1 Tf function. 


We worked more on the subject and for now the fix was to convert our model to constants using low level TF api convert_to_constants_v2 and then save again the model as a savedmodel: then the graph is inlined and smaller and the memory usage is improved (in our real model that i cannot share we divided the memory usage by two 1.4Gb --> 0.6Gb). 

However its unfortunate that we need this and we would prefer to stay in the high level api of Tensorflow/ keras.

feel free to tell us if you need more repro !
