### ISSUE TITLE
Overriding `__add__` on `KerasTensor` class

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#14910]
When doing `z = x + y` with KerasTensors, right now, the generate node in the Functional graph is a TFOpLayer wrapping `tf.add`. Instead, it would be nicer if the generated node was a Keras `Add` layer. This would keep the graph more readable and would simplify serialization.

Like this:

```
from tensorflow import keras
x = keras.Input(shape=(1,))
y = keras.Input(shape=(1,))
z = x + y
model = keras.Model([x, y], z)
model.summary()
```

This can be achieved by overriding `__add__` on the KerasTensor class. Likewise we should do this for other operators when possible.

**Comment by MaanasArora** [comment]
Hi @fchollet, unless I'm missing something, will referencing the Keras Add layer on the KerasTensor class cause a circular import? Do you think we should make the changes in the Functional class instead? Thanks

**Comment by tomerk** [comment]
[Copying notes from the candidate PR: I don't think this is a feasible change to make at this point in time]

Okay, I've checked the comprehensive internal google tests of Keras users. This causes around ~100 internal test failures.

This is because the Keras add layer (which is built on the Keras merge layer) and the `+` tensor operator have fundamentally different behaviors.

There appear to be at least two main differences:
1. Supported shapes:
The Keras add layer will only add tensors of the exact same shape. The tensor `+` operator will broadcast scalars/tensors w/ fewer dimensions.

E.g.
```
tf.ones(shape=(3, 4)) + 2.0
```
Outputs:
```
<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>
```

While:
```
tf.keras.layers.Add()([tf.ones(shape=(3, 4)), 2.0])
```
Raises:
```
InvalidArgumentError: Tried to expand dim index 1 for tensor with 0 dimensions. [Op:ExpandDims]
```

2. The Keras layer introduces autocasting semantics.
E.g. adding two float64 tensors directly outputs a float64 tensor:
```
tf.ones(shape=(3, 4), dtype=tf.float64) + tf.ones(shape=(3, 4), dtype=tf.float64)
```
```
<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])>
```

But using the add layer autocasts to a float32 tensor:
```
tf.keras.layers.Add()([tf.ones(shape=(3, 4), dtype=tf.float64), tf.ones(shape=(3, 4), dtype=tf.float64)])
```

```
<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)>
```

----------------------
All in all, this change breaks backwards compatibility and I don't think is worth the slightly-nicer model representation it would provide (of an Add layer instead of a tf.__add__ tfoplayer)

Perhaps we can revisit the semantics of `Add` layers in the future and make them more consistent with the `+` binary operator. At that point we could apply this change.
