### ISSUE TITLE
Add track_times=False to Model.save_weights('.h5')

### ISSUE THREAD

**Issue by josefondrej** [keras-team/keras#15143]
**System information**
- TensorFlow version: 2.4.1
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state.**
Currently, when calling `keras.models.Model.save_weights()` in hdf5 format, the weights are saved using `h5py.Group.create_dataset` with the argument `track_times` set to the default value `True`. The effect of this is following: even when the weights are exactly the same, the resulting saved files will not be the same (see for example this [stack overflow question](https://stackoverflow.com/questions/16019656/hdf5-file-h5py-with-version-control-hash-changes-on-every-save)). This is a problem when one has a replicable model pipeline and uses some version control system (like [DVC](https://dvc.org/)). 
The proposed feature is adding `h5_track_times` argument to the `Model.save_weights()` function and pass it down to h5py. 

**Will this change the current api? How?**
Yes, the `Model.save_weights()` would get an additional optional `h5_track_times` argument. 

**Who will benefit with this feature?**
Everyone who needs to have replicable model pipeline and needs to version the model weights in hdf5 format.

**Comment by josefondrej** [comment]
Original issue: [https://github.com/tensorflow/tensorflow/issues/51405](https://github.com/tensorflow/tensorflow/issues/51405)

**Comment by qlzh727** [comment]
@fchollet and @k-w-w, I think we should actually not putting the timestep into the h5 and its checksum at all. Only the weight itself should be saved, and the metadata shouldn't affect the artifacts.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
