### ISSUE TITLE
A model with TextVectorization layer can not be uploaded 

### ISSUE THREAD

**Issue by kmkarakaya** [keras-team/keras#15443]
In https://keras.io/examples/nlp/text_classification_from_scratch/ example, after I saved the end_to_end_model, can not upload it due to the issue in the Text Vectorization layer (even I use the decorator "@tf.keras.utils.register_keras_serializable()" before the
def custom_standardization(input_data) function. The error message is below.

Actually, I received a similar error message, when save & upload the Text Vectorization layer alone or in a Keras model due to the fact that after uploading the Text Vectorization layer does not generate tensors anymore but ragged tensors! 

Thank you
KMK

TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("model/dropout/Identity:0", shape=(None, 16), dtype=float32), row_splits=Tensor("model/dropout/Identity_1:0", shape=(None,), dtype=int64)), row_splits=Tensor("model/conv1d/conv1d/RaggedExpandDims/RaggedFromUniformRowLength/RowPartitionFromUniformRowLength/mul:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type. 

![image](https://user-images.githubusercontent.com/41159849/135624005-e8a80194-0214-4599-8f0e-eb3be924577d.png)

**Comment by mattdangerw** [comment]
It looks like there's a couple issue going on.

 - The main stack trace you posted (about ragged tensors) is only reproduced on stable and not on nightly.
 - On nightly we see a different error, related to saving a custom standardization function.

Both worth looking at, just wanted to clarify that things do not look the same stable/nightly. Thanks for filing!

**Comment by mattdangerw** [comment]
So the second error is actually expected (though the error message is bad, and something we need to fix). The issue is that the custom callable for standardization needs to be passed as a custom_object on `models_load`.

If you do the following
`loaded_model = tf.keras.models.load_model('MyModel', custom_objects={"custom_standardization": custom_standardization})`

The example works on nightly. So the issue to fix here is that this is failing on stable, not nightly.
