### ISSUE TITLE
Improvement for tf.keras.utils.get_file

### ISSUE THREAD

**Issue by bizzyvinci** [keras-team/keras#15540]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): Yes

This is a duplicate of an issue I posted on [tensorflow](https://github.com/tensorflow/tensorflow/issues/49926). I brought it here because I discovered that keras is developed separately now and I just made a [notebook for illustration](https://colab.research.google.com/drive/1f_DlOgz4DL9_6xFOmsC71kaE4axEeQxo).

**Describe the feature and the current behavior/state.**
tf.keras.utils.get_file only works with `GET` request. It can work for `POST` request too if the `data` argument is utilized in [urlretrieve](https://github.com/tensorflow/tensorflow/blob/ecc0010f151cabb0a4730777790631fd6fff8f6f/tensorflow/python/keras/utils/data_utils.py#L259). 

**Will this change the current api? How?**
Yes, get_file would take in one other parameter (don't know which name and type would be best) to pass into the retrieve function.

**Who will benefit with this feature?**
Whoever wants to get file that's accessed through post method, such as files that require tokens or authorization.

**Simplified version of GET vs POST**
I've been able to make illustration with [jsonplaceholder](https://jsonplaceholder.typicode.com/guide/) and it can be found in this [notebook](https://colab.research.google.com/drive/1f_DlOgz4DL9_6xFOmsC71kaE4axEeQxo?usp=sharing). 

**Side note on documentation.**
In [get_file documentation](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file), `untar` and `md5_hash` arguments have been depreciated in favor of `extract` and `file_hash`. I thought about some changes but I don't know if they would add value.
* Change [example](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file#example) argument from `untar=True` to `extract=True`
* Rearrange arguments in documentation and function to show `extract` and `file_hash` before `untar` and `md5_hash`.

**Comment by jvishnuvardhan** [comment]
@bizzyvinci Can you please respond to the above comment? Thanks!

**Comment by bizzyvinci** [comment]
I don't really understand the question. 

If you meant using `requests.post` method. No, we can't use that because a response object is returned instead of downloading the file like `urlretrieve`.

`urllib.request.urlretrieve` method is currently used in `keras.utils.get_file`. `urllib.request.urlretrieve` has a `data` parameter which turns the request type from GET to POST and that parameter is not utilized.

**Comment by sanatmpa1** [comment]
Reopening the issue, as the bot has mistakenly closed this issue even after the user has commented.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
