### ISSUE TITLE
TensorFlow Keras SavedModel with custom layers throws a TypeError after being saved and loaded twice

### ISSUE THREAD

**Issue by jamesmishra** [keras-team/keras#15565]
### System information.
- Have I written custom code:
  - **Yes**
- OS Platform and Distribution:
  - **Ubuntu 20.04 Docker image with NVIDIA/CUDA libraries**
- TensorFlow installed from:
  - **Binary from PyPI**
- TensorFlow version:
  - **2.6.0**
- Python version:
  - **3.8.10**
- GPU model and memory:
  - **2 NVIDIA RTX 3090s with 24 GB of memory each**

### Describe the problem.

TensorFlow/Keras throws a TypeError when:
1. I create a Keras model with at least one custom layer and save it to the filesystem as a SavedModel.
2. I load the SavedModel from the filesystem.
3. I save the model loaded in Step 2.
4. I try to load the model saved in Step 3.

The exact TypeError stack trace ends in:
```
/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py in canonicalize_function_inputs(self, *args, **kwargs)
   2760         missing_args = [self._arg_names[i] for i in sorted(missing_arg_indices)]
   2761         if len(missing_args) == 1:
-> 2762           raise TypeError("{} missing 1 required argument: {}".format(
   2763               self.signature_summary(), missing_args[0]))
   2764         else:

TypeError: f(inputs, training, training, training, training, *, training, training) missing 1 required argument: training
```

### Standalone code to reproduce the issue.
The following code throws a TypeError when trying to load `model3`.

```python
import tensorflow as tf

class CustomLayer(tf.keras.layers.Layer):
    def call(self, inputs, *args, **kwargs):
        return inputs

model1 = tf.keras.Sequential([
    CustomLayer()
])
model1.build((None, 1))
model1.compile()
model1.save("model1")

model2 = tf.keras.models.load_model("model1")
model2.save("model2")

# This line should raise a TypeError.
model3 = tf.keras.models.load_model("model2")
```

But the above code works perfectly if the `CustomLayer.call()` signature is either:
```python
def call(self, inputs):
```
or
```python
def call(self, inputs, training=None):
```

The bug also goes away if Keras becomes aware of the layer by:
* passing it in the `custom_objects` dictionary passed to [`tf.keras.models.load_model()`](https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model).
* adding the layer to the Keras registry with the [`@tf.keras.utils.register_keras_serializable`](https://www.tensorflow.org/api_docs/python/tf/keras/utils/register_keras_serializable) decorator.
* installing the layer with the [`tf.keras.utils.custom_object_scope()`](https://www.tensorflow.org/api_docs/python/tf/keras/utils/custom_object_scope) context manager.

I describe these solutions in detail in [a StackOverflow answer I wrote](https://stackoverflow.com/questions/69762318/tensorflow-keras-savedmodel-throws-a-typeerror-after-being-saved-and-loaded-twic). If my answer is wrong, or if this error is patched, I'm happy to update my answer.

### Related issues.
I believe the following issues may describe the same underlying bug:
* https://github.com/tensorflow/tensorflow/issues/40342
* https://github.com/keras-team/keras/issues/14808

**Comment by MrinalTyagi** [comment]
I would like to work on this issue if no one else is currently working on it.

**Comment by chenmoneygithub** [comment]
Thanks MrinalTyagi! Let us know if you need any help from our side. Also cc'ed a crew member in Keras.

**Comment by chenmoneygithub** [comment]
@k-w-w

**Comment by adam-kral** [comment]
Is there an easy way to make it work for an existing saved model?

**Comment by jvishnuvardhan** [comment]
@adam-kral Easy and recommended approach is to pass `custom_objects` dictionary.

`model3 = tf.keras.models.load_model("model2", custom_objects={'CustomLayer': CustomLayer)`

Without that `custom_objects`, `load_model` is able to load the model with custom_layer once. Second time, loading the saved model (that was loaded and saved from original model1) is throwing an error because it is missing one of the `training` argument. 

Check https://www.tensorflow.org/guide/keras/save_and_serialize for more details on saving and loading a model with custom objects. Thanks

**Comment by adam-kral** [comment]
@jvishnuvardhan Thank you, but that didn't work for me. (Hope I'm doing it right). Probably because my saved model is already saved, loaded and saved again (indeed `"model2"` file as you write). So as jamesmishra writes in his [SO answer](https://stackoverflow.com/questions/69762318/tensorflow-keras-savedmodel-throws-a-typeerror-after-being-saved-and-loaded-twic) when I implement `to_config`, it has no effect on `model2` as it was already saved (without `to_config`). 

So I get the same error even when I implement both `from_config`, `to_config` and use the line you provided. 

It is nothing important, a model for school assignment, but I wonder if there is a simple way to load it (add `training` argument to the saved model bytecode), for me, or others that stumble upon this.

**Comment by jvishnuvardhan** [comment]
@adam-kral I am not sure about adding another `training` argument to the save model. 

@k-w-w is the expert and would wait for a response from @k-w-w

**Comment by MrinalTyagi** [comment]
@adam-kral @jvishnuvardhan @chenmoneygithub Just a suggestion, while creating model with custom layer, shouldn't adding these as warnings would be helpful for users.

1. passing it in the `custom_objects` dictionary passed to `tf.keras.models.load_model()`.
2. adding the layer to the Keras registry with the `@tf.keras.utils.register_keras_serializable` decorator.
3. installing the layer with the `tf.keras.utils.custom_object_scope()` context manager.

**Comment by cbjs** [comment]
same.
It's ok on tf2.4

**Comment by wangfuzhou110** [comment]
The same issue was encountered on TF 2.7.0

**Comment by gowthamkpr** [comment]
@jamesmishra The reason why this is throwing an error is clearly explained [here](https://stackoverflow.com/questions/69762318/tensorflow-keras-savedmodel-throws-a-typeerror-after-being-saved-and-loaded-twic) and also the workarounds are mentioned there. 

This has been fixed in the latest version of tf-nightly 

> (2.10.0-dev20220713)

. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/8a925352cf801134becccfd55df85d58/untitled376.ipynb)
