### ISSUE TITLE
flow_from_directory detects subdirectories but can't load images

### ISSUE THREAD

**Issue by harshitjaitly** [keras-team/keras#15575]
```
imgPath = "./categories"
batchSize = 64 
desiredSize = (228,228)

dataGen = image.ImageDataGenerator()

generator = dataGen.flow_from_directory( imgPath ,
                               target_size = desiredSize,
                               batch_size = batchSize,
                               class_mode = None,
                               shuffle = false)

return generator
```
Returns : Found 0 images belonging to 24 classes.

I just wish to get a generator object to load the images.
Directory Structure is as follows :
   categories/
                class1/
                        image1
                        image2
                        ..............
                class2/
                        image1
                        image2
                        ..............
               ....
               ....
               class24/
                        image1
                        image2
                        ..............

**Comment by chunduriv** [comment]
@harshitjaitly, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. I tried it on  sample `Dogs_Vs_Cats` data and it is working as expected. Please check the [gist here](https://colab.research.google.com/gist/chunduriv/8d8c1b8e468b2fe59d239ebd2bc17733/15575.ipynb). Thanks!
