### ISSUE TITLE
layers.LocallyConnected2D takes a lot of time to get initialized

### ISSUE THREAD

**Issue by old-school-kid** [keras-team/keras#15668]
Tensorflow version: 2.7.0
layers.LocallyConnected2D takes an awful amount of time to build. The time taken to build increases dramatically with increasing size of input. 

> LocallyConnected2D in mode 1 takes 11.0303 seconds which is 43.0397 times Normal Conv2D
> LocallyConnected2D in mode 2 takes 6.6656 seconds which is 26.0089 times Normal Conv2D
> LocallyConnected2D in mode 3 takes 4.1878 seconds which is 16.3407 times Normal Conv2D

Here mode means implementation. 
Sample code to generate the problem can be found in this [notebook](https://colab.research.google.com/drive/1r--vgfn9_6UD-ff7pIYSRfNoZlXQN0gk?usp=sharing)

Moreover the sparse tensor generated in implementation mode 2 uses sparse_mat_mul which is deprecated.

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to replicate the issue on colab using TF v2.7.0 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/981d08cb49afc05de1daa3192bc54d35/locally-connected-2d.ipynb#scrollTo=6-FC8XtrjMCu) for reference.Thanks!

**Comment by sachinprasadhs** [comment]
It may be due to the different approach as mentioned [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LocallyConnected2D).
`The LocallyConnected2D layer works similarly to the Conv2D layer, except that weights are unshared, that is, a different set of filters is applied at each different patch of the input.
`
