### ISSUE TITLE
Why is there a slight difference between extracting feature values from VGG16 model alone and as a pre-training model?

### ISSUE THREAD

**Issue by 945226956** [keras-team/keras#15682]
I want to use VGG16 model to extract N image features, and then carry out the fusion of multiple image features for video recognition. I found that the image features predicted by THE VGG16 model alone were not the same as the image feature values predicted as part of the pre-training model, and there was a slight difference, which made me very confused. I did not know whether there was a problem with my network structure or the prediction of the VGG16 model itself.

See the attachment for my code  [code url ](https://github.com/945226956/vgg16-test/blob/main/%E6%B5%8B%E8%AF%95%E8%9E%8D%E5%90%88vgg%E6%8A%BD%E5%8F%96%E8%A7%86%E9%A2%91%E7%89%B9%E5%BE%81%E6%A8%A1%E5%9E%8B%E7%BB%93%E6%9E%84.ipynb)

 Please check it for me.

**Comment by sachinprasadhs** [comment]
Could you please elaborate your issue and also what is the difference in prediction you are getting.

**Comment by 945226956** [comment]
@sachinprasadhs  hey，look for my detail code , [https://github.com/945226956/vgg16-test/blob/main/%E6%B5%8B%E8%AF%95%E8%9E%8D%E5%90%88vgg%E6%8A%BD%E5%8F%96%E8%A7%86%E9%A2%91%E7%89%B9%E5%BE%81%E6%A8%A1%E5%9E%8B%E7%BB%93%E6%9E%84.ipynb](https://github.com/945226956/vgg16-test/blob/main/%E6%B5%8B%E8%AF%95%E8%9E%8D%E5%90%88vgg%E6%8A%BD%E5%8F%96%E8%A7%86%E9%A2%91%E7%89%B9%E5%BE%81%E6%A8%A1%E5%9E%8B%E7%BB%93%E6%9E%84.ipynb)

**Comment by old-school-kid** [comment]
Hi @945226956 
The code is correct and everything, The thing is when you create a model of your own which uses a keras application it loses precision since the computation are too expensive. On the other hand the output of the keras.application model when uses as-is doesnt have to go through that problem. You can see there is a microscopic difference in the results though. You can still decrease the number by changing the [mixed precision policy](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/set_global_policy). You can set precision at `float64` to decrease the difference. Also please note that doin so will decrease the speed significantly.
Hope this helps!
