### ISSUE TITLE
[Feature Request] Be able to checkpoint optimizer state in mixed precision.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras#15709]
**System information**.

TensorFlow version (you are using): 2.7.0
Are you willing to contribute it (Yes/No) : Yes, if given some guidance.

**Describe the feature and the current behavior/state**.
I would like to train the model in mixed precision and by the end of the training, save optimizer state and model variables inside a `tf.train.Checkpoint`. This is not possible, as such operation throws a `NotImplementedError`.

[Colab Notebook](https://colab.research.google.com/drive/16keHGJAafRKYqRAWLkFmGkr_7HxFy6jl?usp=sharing) with code.

Code summary:
```python
policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)

optimizer = tf.keras.optimizers.Adam(1e-3)
model = ...
model.compile(...
model.fit(...

checkpoint = tf.train.Checkpoint(model=model, optimizer=optimizer)
checkpoint.save("tmp/checkpoint")
```
The above will raise `NotImplementedError`:
```python
NotImplementedError: A slot variable was re-used as a dependency of a Trackable object: <tf.Variable 'cond_1/Adam/dense/kernel/m:0' shape=(1280, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)>. This is not currently allowed. File a feature request if this limitation bothers you.
```

**Will this change the current api? How?**
It will be possible to save optimizer state at the end of the training in mixed precision.

**Who will benefit from this feature?**
Keras user's who train models in mixed precision.

**Comment by chunduriv** [comment]
@sachinprasadhs, Was able to replicate the issue on Colab using TF v2.7.0 and tf-nightly, please find the [gist here](https://colab.research.google.com/gist/chunduriv/5381dbf8b2933210bd49a80be730ce85/15709.ipynb) for reference.Thanks!

**Comment by reedwm** [comment]
As a workaround, on the second-to-last line, replace `optimizer=optimizer` with `optimizer=model.optimizer`:

```python
ckpt = tf.train.Checkpoint(model=model, optimizer=model.optimizer)
```

The reason this issue occurs is that Keras models automatically wrap the optimizer with a [LossScaleOptimizer](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/LossScaleOptimizer) if it isn't already wrapped with one. Due to various technical reasons, trying to save the original optimizer after it is already wrapped with a LossScaleOptimizer does not work. An alternative workaround would be to explicitly wrap your optimizer with a LossScaleOptimizer before passing it to `Model.compile`.

---

@k-w-w, I think this occurs since LSO subclasses the `DelegatingTrackableMixin`, and both the inner optimizer and the LSO is saved in a checkpoint. Is it possible to raise a better error message in this case?

**Comment by sebastian-sz** [comment]
@reedwm 
Thank you for your response. That workaround is indeed possible.
