### ISSUE TITLE
Saving & loading a keras.layers.RNN with a custom cell with multiple inputs, states, and outputs throws an exception

### ISSUE THREAD

**Issue by dniku** [keras-team/keras#15794]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): `v2.7.0-0-gc256c071bb2 2.7.0`
- Python version: `3.7.12`
- Bazel version (if compiling from source): n/a
- GPU model and memory: n/a
- Exact command to reproduce: [Colab](https://colab.research.google.com/gist/dniku/f387f1f31ae20e045329523391ace807/keras_rnn_layer_saving_bug.ipynb)

**Describe the problem**.

Saving & loading a `keras.layers.RNN` with a custom cell with multiple inputs, states, and outputs throws `Layer "rnn" expects 3 input(s), but it received 2 input tensors.`. Please see the Colab link for more details and a reproducing example.

I have investigated the problem a little and it seems that `keras.layers.RNN` does some magic with `self.input_spec`, and some of that magic is broken when loading the model. In the gist that I linked, cell 4 contains an `if debug` check. Setting `debug = True`, one can see that when the model is being loaded, `keras.layers.RNN.__call__()` is called _twice_: the first time with `KerasTensor` and the second time with `tf.Tensor`. The first call (with `KerasTensor`) forwards the inputs to `Layer.__call__()`, which does something incorrect to `self.input_spec`, leaving an extra `None` at index `1`. It seems that the root of the problem is somewhere there.

**Comment by jvishnuvardhan** [comment]
@dniku I can reproduce the issue when saving the model with `h5` format. However, there is no issue if you save the model in `tf` format. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/9cc88d13715457c417cf8e64df39918e/keras_rnn_layer_saving_bug.ipynb). Thanks!

we will check why this is an issue with `h5` format. Thanks!

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
