### ISSUE TITLE
tf.compat.v1.keras.backend.get_session gives erroneous deprecation warning

### ISSUE THREAD

**Issue by drasmuss** [keras-team/keras#15792]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GPU model and memory: N/A
- Exact command to reproduce: See https://colab.research.google.com/gist/drasmuss/3be97c8968acee0c5476dba394f8a113/33182.ipynb

**Describe the problem**.

As requested [here](https://github.com/tensorflow/tensorflow/issues/33182#issuecomment-994134417), I am re-opening this issue from the Tensorflow repository here. History/discussion can be seen in that issue.

**Describe the current behavior**.

Accessing `tf.compat.v1.keras.backend.get_session` gives a deprecation warning telling you to use `tf.compat.v1.keras.backend.get_session`.

**Describe the expected behavior**.

Accessing `tf.compat.v1.keras.backend.get_session` should not give a deprecation warning (since we're explicitly accessing the compat.v1 namespace). Or it should direct the user to the correct function, if `tf.compat.v1.keras.backend.get_session` is not the right access point, rather than telling the user to use the namespace they're already using.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

https://colab.research.google.com/gist/drasmuss/3be97c8968acee0c5476dba394f8a113/33182.ipynb

**Comment by sanatmpa1** [comment]
I am able to reproduce the issue and I am getting the erroneous warning even after using `tf.compat.v1.keras.backend.get_session`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/fa73dba013dcb85a0cc56af1225f11bd/33182.ipynb). Thanks!

**Comment by SuryanarayanaY** [comment]
@drasmuss ,

I have checked the code with TF2.13v and the reported deprecation warning is no more.Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/9c5bb20e66fc352edff231be09312b7f/33182_2-13.ipynb).


Also We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
