### ISSUE TITLE
Saving a keras.layers.RNN with a custom cell substitutes custom initial states with zeros

### ISSUE THREAD

**Issue by dniku** [keras-team/keras#15796]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): `v2.7.0-0-gc256c071bb2 2.7.0`
- Python version: `3.7.12`
- Bazel version (if compiling from source): n/a
- GPU model and memory: n/a
- Exact command to reproduce: [Colab](https://colab.research.google.com/gist/dniku/3ab9d3ecf8430ba639c7fa0577d9ff65/keras_rnn_layer_initial_state_bug.ipynb)

**Describe the problem**.

When attempting to save a `keras.layers.RNN` with a custom cell and explicitly defined `initial_states`, a call is made to `get_initial_state()` on the cell, even though the documentation for `keras.layers.RNN` [states](https://github.com/keras-team/keras/blob/353cb10af7c0c7d435b31129c5970fcabe3fc961/keras/layers/recurrent.py#L224) the following:

> A RNN cell is a class that has:
> ...
> A `get_initial_state(inputs=None, batch_size=None, dtype=None)` method that creates a tensor meant to be fed to `call()` as the initial state, **if the user didn't specify any initial state via other means**.

(emphasis mine)

In addition, the source code seems to have the same intention, only [calling](https://github.com/keras-team/keras/blob/353cb10af7c0c7d435b31129c5970fcabe3fc961/keras/layers/recurrent.py#L887-L888) `get_initial_state()` if `initial_state is None`.

Notably, changing the saving format from SavedModel to HDF5 seems to alleviate the issue on this particular simple case, but if the model has multiple inputs or states, a different problem is triggered: https://github.com/keras-team/keras/issues/15794.

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to reproduce this issue in TF v2.7.0 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f7297f1e467a0b2e80aebf33af17d4d5/untitled16.ipynb) for reference.Thanks!

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
