### ISSUE TITLE
text.tokenizer not removing filters char from text

### ISSUE THREAD

**Issue by sachinprasadhs** [keras-team/keras#15845]
**Describe the problem**.

Moving this issue from https://github.com/tensorflow/tensorflow/issues/49459

Describe the problem clearly here. Be sure to convey here why it's a bug in Keras or why the requested feature is needed.

**Describe the current behavior**.

The filter parameter of `tf.keras.preprocessing.text.Tokenizer` does not seem to filter out characters included in the "filters" paramter. those characters have an index in keys of .get_config(). Is this expected?

The description of the "filters parameters reads " a string where each element is a character that will be filtered from the texts.".
Hence I would not expect these characters to have been given an index, (perhaps they all could be given one OOV index)

**Describe the expected behavior**.

The characters included in the filters parameter would not be having different indices in the tokenizer. Either all have one oov index or none.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Attached colab [Gist](https://colab.research.google.com/gist/sachinprasadhs/8cc5dbf4676d5072bf52777261dd0884/15845.ipynb)
```
import tensorflow as tf 

char_tokenizer = tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True, char_level=True,
    document_count=0, 
)

char_tokenizer.fit_on_texts(['a%$#^ *'])
print(char_tokenizer.get_config()['index_word'])
```
`>> {"a": 1, "%": 2, "$": 3, "#": 4, "^": 5, " ": 6, "*": 7}` 

Despite these special characters being included in the filters parameter, they are not filtered out and have been given an index.

Expected behaviour
`>> {"a": 1}`

**Comment by qlzh727** [comment]
Triage notes: Assign to Matt for preprocessing related issues.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
