### ISSUE TITLE
drop_connect_rate in efficientnet is not documented

### ISSUE THREAD

**Issue by magicaltoast** [keras-team/keras#15911]
**URL(s) with the issue:**.
https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/
https://keras.io/api/applications/efficientnet/
**Description of issue (what needs to be changed):**.
In the [tutorial](https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/
) drop_connect_rate parameter is mentioned. But there is not mention of it in the [API reference](https://keras.io/api/applications/efficientnet/
)

**Comment by gowthamkpr** [comment]
@magicaltoast As you can see [here](https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/applications/efficientnet.py#L211), `EfficientNet()` is defined as a function in which various parameters are set to constant and in [here](https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/applications/efficientnet.py#L540), `EfficientnetB0()` is being defined which returns `EfficientNet()` which contains `drop_connect_rate` argument which is set to 0.2 by default and since `drop_connect_rate` argument  is not directly defined in `EfficientnetB0()`, it is not mentioned in the document.
