### ISSUE TITLE
Feature/documentation request: Temporal Fusion Transformers for Time Series Forecasting

### ISSUE THREAD

**Issue by yhpeng6** [keras-team/keras#16070]
TensorFlow version (you are using): TensorFlow version: 2.7.0

Describe the feature clearly here. Be sure to convey here why the requested feature is needed. Any brief description about the use-case would help.
The [Temporal Fusion Transformers for Interpretable Multi-horizon Time Series Forecasting](https://arxiv.org/abs/1912.09363) and [point transformer](https://github.com/qq456cvb/Point-Transformers) are effective method to conduct time-series forecasting recently based on attention mechanism. These features can be used for time-series forecasting and replace the LSTM in time-series forecasting tasks, such as [weather prediction](https://keras.io/examples/timeseries/timeseries_weather_forecasting/) 

I think it is necessary to update this advanced method for time-series forecasting and provide an option method for LSTM. 

Will this change the current api? How?
No, add the document examples.

Who will benefit from this feature?
The researchers who used the LSTM time-series forecasting before and want to try transformer in recent research.

**Comment by rchao** [comment]
Thanks for the request. Mind checking if https://keras.io/examples/timeseries/timeseries_classification_transformer/ can work for the case or it's different?

**Comment by yhpeng6** [comment]
Thanks for the reply.
I think it is similar in encoding part, but different in decoding part.
It also provide a guidance.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
