### ISSUE TITLE
Cannot checkpoint EfficientNetB1 in mixed precision.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras#16129]
One can create a `tf.train.Checkpoint` of EfficientNetB1 in mixed precision, but it's impossible to load it back in FP32.

**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): Google Colab
- TensorFlow version (use command below): v2.8.0-0-g3f878cff5b6
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GPU model and memory: Tesla T4 15109MiB
- Exact command to reproduce:

Exact command consists of three steps:

##### Step 1. Save the model in FP16:
```python
import tensorflow as tf

policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)
model = tf.keras.applications.efficientnet.EfficientNetB1()
ckpt = tf.train.Checkpoint(weights=model.weights)
ckpt.save("my_checkpoint/ckpt")
```

##### Step 2. Restart runtime
```python
### RESTART RUNTIME ###
import os
os.kill(os.getpid(), 9)
```

##### Step 3. Try to load back the weights -> Error:
```python
import tensorflow as tf
model = tf.keras.applications.efficientnet.EfficientNetB1()
checkpoint = tf.train.Checkpoint(weights=model.weights)
checkpoint.restore("my_checkpoint/ckpt-1").assert_consumed()
```

**Describe the problem**.
1. Mixed precision is a valuable tool, but the checkpoints should be policy agnostic. I think I should be able to train remotely on FP16 supporting GPU and perform eval locally on much smaller GPU in FP32.
2. The problem above does not exist for other architectures like `tf.keras.applications.MobileNetV3Small` or `EfficientNetV2B1`, I'm not sure why EfficientNetB1 is an exception.

**Describe the current behavior**.
Currently one cannot load a checkpoint trained in mixed precision.

**Describe the expected behavior**.
One should be able to load a checkpoint regardless of Policy the checkpoint was created in.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.
- Do you want to contribute a PR? (yes/no): if pointed in the right direction.

**Standalone code to reproduce the issue**.
[Colab Link](https://colab.research.google.com/drive/1LDlULIUn5Dd4wZtAaeZ5b12AMH5n8rUT?usp=sharing)

**Source code / logs**.
```python
InvalidArgumentError: tensor_name = weights/0/.ATTRIBUTES/VARIABLE_VALUE; expected dtype float does not equal original dtype half
tensor_name = weights/1/.ATTRIBUTES/VARIABLE_VALUE; expected dtype float does not equal original dtype half [Op:RestoreV2]
```

**Comment by chenmoneygithub** [comment]
Hi, thanks for reporting the issue! Generally model variables' type should not be changed by setting the global policy, if it is getting changed, it means when we are creating the variable we use the backend type. That is to say, the reason for not seeing error in `MobileNetV3Small` and `EfficientNetV2B1 ` is that the model variables' type is not changed by setting global policy.

As a summary, there are two things:
- Global policy should not affect the pre-trained model variable's type: this is what Keras can fix.
- Being able to load fp16 weights into fp32: this issue is out of the box of Keras, could you report this issue to Tensorflow, and see if they have plans for it?

Thanks!

**Comment by sebastian-sz** [comment]
Thank you for the answer @chenmoneygithub. Althought, I'm not sure I understand, all concepts:

> the reason for not seeing error in MobileNetV3Small and EfficientNetV2B1 is that the model variables' type is not changed by setting global policy.

Sorry I don't think I follow - can you tell me what is the difference in MobileNetV3 or EfficientNetV2, compared to standard EfficientNet that the model's variables dtype is changed by setting global policy?

>Being able to load fp16 weights into fp32: this issue is out of the box of Keras (...)

The issue seems to be affecting only EfficientNetB1 models. It is possible to load basic variable from fp16 into fp32:
```python
# Create variable in fp16
import tensorflow as tf
policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)
variable = tf.Variable(1.0)
ckpt = tf.train.Checkpoint(variable=variable)
ckpt.save("my_checkpoint/ckpt")

### RESTART RUNTIME ###
import os
os.kill(os.getpid(), 9)

# Load back in fp32
import tensorflow as tf
variable = tf.Variable(0.0)
checkpoint = tf.train.Checkpoint(variable=variable)
checkpoint.restore("my_checkpoint/ckpt-1").assert_consumed()
print(variable)  # 1.0
```
As I mentioned, this works also for MobileNetV3 and other Keras models. I'm not sure why EfficientNetV1 breaks in this workflow.

**Comment by chenmoneygithub** [comment]
The problem is when we are creating a `tf.Variable`, there could be multiple ways on how we determine its dtype. That is to say, in the EfficientNetV1 model, the dtype is determined by Keras backend, which is affected by global policy.

In this code snippet you provided:
```python
# Create variable in fp16
import tensorflow as tf
policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)
variable = tf.Variable(1.0)
ckpt = tf.train.Checkpoint(variable=variable)
ckpt.save("my_checkpoint/ckpt")
```

If you print out the `variable`, you can see it is still of dtype float32, which is the same scenario as MobileNetV3, i.e., variable type is not affected by global policy.
