### ISSUE TITLE
Unexpected outputs from MaxPooling2D layer

### ISSUE THREAD

**Issue by kelvinlyy** [keras-team/keras#16158]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.12
- Bazel version (if compiling from source):
- GPU model and memory: using CPU
- Exact command to reproduce: 

```
input_shape = (10,10,32,256)
x = keras.layers.Input(input_shape[1:])
layer_stack = [
keras.layers.MaxPooling2D(pool_size=(2,2), padding="same", strides=(2,2)),
]
layer_input = x
for layer in layer_stack:
  y = layer(layer_input)
  layer_input = y

model = keras.Model(x,y)
model.summary()
import numpy as np
x = np.random.rand(*input_shape)
x[:] = np.NaN
res = model.predict(x)
```

**Describe the problem**.
MaxPooling2D layer does not give correct results for NaN inputs.

**Describe the current behavior**.
MaxPooling2D layer outputs a matrix of large negative values, i.e. `-3.4028235e+38` when a matrix of NaN is passed as inputs.

**Describe the expected behavior**.
Normally in max pooling, maximum value of patches of an input is output. And in the case of NaN matrix as inputs, outputs should be a matrix of NaN.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

https://colab.research.google.com/drive/13SEcY5Lzj9fLQTv-JSNWA7cgnirNWnh6?usp=sharing#scrollTo=gZUgM5985nJs

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/05520958153453cfad9e8c83f1b59de2/untitled244.ipynb).

**Comment by maybeLee** [comment]
I can also reproduce this bug. In the meanwhile, MaxPooling1D also has this issue while MaxPooling3D will output inf.

**Comment by fchollet** [comment]
My question would be: where do the NaNs get converted to numerical values? It is at the level of the TF MaxPool op? Keras behavior should be consistent with TF behavior.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
