### ISSUE TITLE
Pixel-Adaptive ConvolutionalLayer

### ISSUE THREAD

**Issue by old-school-kid** [keras-team/keras#16231]
If you open a GitHub issue, here is our policy:

It must be a bug, a feature request, or a significant problem with the documentation (for small docs fixes please send a PR instead).
The form below must be filled out.

**Here's why we have that policy:**.

Keras developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

**System information**.

TensorFlow version (you are using): 2.8
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.
PAC are different from normal convolution in a way that PAC has filter weights multiplied with a spatially-varying kernel that depends on learnable, local pixel features. This shouldnt be confused with LocallyConnected2D which has completely unshared filter weights.
[The paper](https://arxiv.org/abs/1904.05373) has already 131 citations and official PyTorch implementation can be found [here](https://github.com/NVlabs/pacnet).

When replaced with normal convolution in pre trained networks authors claim to have better performance. The more exciting and interesting use case is segmentation where they perform much better and faster than CRF. 

cc @LukeWood should this be added to Keras-CV instead?

**Will this change the current api? How?**
Yes. A new layer will be added. 

**Who will benefit from this feature?**
Anyone who uses keras for CV works. 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): Yes

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
