### ISSUE TITLE
Problems to handle variable length input, using generator?

### ISSUE THREAD

**Issue by Nafees-060** [keras-team/keras#16246]
I am dealing with the multiple issues in order to handle variable length input and using generator. I have posted the problem on [stack overflow](https://stackoverflow.com/questions/71492073/tensorflow-keras-problems-to-handle-variable-length-input-using-generator) in detail. I am eagerly looking the solutions for these problems. I am not very much sure to receive any helpful answer from there. That's why I am posting here.

// System specification
- Python 3.9.10 
- Tensorflow version: 2.8.0-dev20211222

- Keras version: 2.6.0

**Comment by tilakrayal** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from **keras-team/keras-core** to **keras-team/keras.**
Consequently, This issue may not be relevant to the `Keras 3 `code base. After the migration is successfully completed, feel free to reopen this issue at **keras-team/keras** if you believe it remains relevant to the `Keras 3` code base. 
If instead this issue is a bug or security issue in legacy **tf.keras**, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about `Keras 3,` please take a look at https://keras.io/keras_core/announcement/. Thank you!
