### ISSUE TITLE
Inconsistent behavior between tf.nn.leaky_relu and keras.layers.LeakyReLU when input is infinity and alpha is 0

### ISSUE THREAD

**Issue by maybeLee** [keras-team/keras#16289]
Please refer this link for more details:
https://github.com/tensorflow/tensorflow/issues/55188

In short, when giving `keras.layers.LeakyReLU` a `-np.Inf` array and set the `alpha=0.0`. `keras.layers.LeakyReLU` will output 0. For comparison, `tf.nn.leaky_relu()` will output `nan` instead.

Following the equation of `LeakyReLU`:
```
f(x) = alpha * x if x < 0
f(x) = x if x >= 0
```
When `alpha=0` and `x=-Infinity`, the times of 0 and `-Infinity` should be **_indeterminate_**, that means that the result can be anything. Here are some links that support this argument:
https://www.quora.com/What-is-0-times-infty-Why-isn%E2%80%99t-it-defined
https://www.youtube.com/watch?v=bSZiEZzwB7Q
I also try such multiplication in NumPy and it indeed outputs nan:
```
import numpy as np
0*(-np.Inf)
```

Therefore, the output of `LeakyReLU` should be `nan` as `tf.nn.leaky_relu` does.

I further check the reason why `keras.layers.LeakyReLU` outputs 0 and find out that it actually does not perform the 0*Infinity operation when the alpha=0
https://github.com/keras-team/keras/blob/dd0f1f480613ceffd994658e5632d54c660d1e73/keras/backend.py#L4964

```
  dtype = getattr(x, 'dtype', floatx())
  if alpha != 0.:  # this branch will not covered
    if max_value is None and threshold == 0:
      return tf.nn.leaky_relu(x, alpha=alpha)

    if threshold != 0:
      negative_part = tf.nn.relu(-x + threshold)
    else:
      negative_part = tf.nn.relu(-x)

  clip_max = max_value is not None
```

Therefore, I guess it is a bug in `keras.layers.LeakyReLU`

**Comment by sachinprasadhs** [comment]
I was able to reproduce the reported behavior.

```
import numpy as np
import tensorflow as tf
input_shape = (1, 3, 3, 3)
x = np.random.rand(*input_shape)
x *= -np.Inf
layer = tf.keras.layers.LeakyReLU(alpha=0.0)
output = layer(x)
list(output.numpy())

[array([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=float32)]
```

**Comment by LukeWood** [comment]
@maybeLee would you be willing to contribute a fix for this?

**Comment by maybeLee** [comment]
Hi,
A pr has been created: https://github.com/keras-team/keras/pull/16295
Please see if it is fine.

**Comment by LukeWood** [comment]
Note from triage:

the long chain of if statements in the layer is here for performance reasons, but it may be fixed now.  in this case the bug will get fixed when we remove the logic.

**Comment by tilakrayal** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from **keras-team/keras-core** to **keras-team/keras.**
Consequently, This issue may not be relevant to the `Keras 3 `code base. After the migration is successfully completed, feel free to reopen this issue at **keras-team/keras** if you believe it remains relevant to the `Keras 3` code base. 
If instead this issue is a bug or security issue in legacy **tf.keras**, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about `Keras 3,` please take a look at https://keras.io/keras_core/announcement/. Thank you!
