### ISSUE TITLE
Unique identifier for models

### ISSUE THREAD

**Issue by pbischoff** [keras-team/keras#16336]
**System information**.

TensorFlow version (you are using): 2.7.1
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

Adding a unique identifier, e.g. some form of a hash string to the model. This would help in tracking model development as it would be possible to save predictions together with the UID and track whether or not predictions have significantly changed for new models.  
The UID should be updated every time `.compile()` or `.fit()` is called to assure that both changes in the configuration but also changes in the weights after retraining trigger a new identifier.

**Will this change the current api? How?**

The current api won't be affected. The UID could be accessibly as a new model attribute (e.g. `model.signature`).

**Who will benefit from this feature?**

Production users and organisations interchaning models or using models developed by third parties. 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by gadagashwini** [comment]
@pbischoff, 
Thanks for proposing new feature request. 
Can you take a look at this guideline for contributing to [Keras](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) and follow the same? Thanks!

**Comment by pbischoff** [comment]
@gadagashwini thank you for your response. I did not add a candidate solution as I wanted to receive feedback on whether or not such feature makes sense or not first.  

Without having thought it through completely, I'd add an attribute like `self.identifier` to the Model class in `keras/engine/training.py`. A new method (e.g. `_set_identifier()`) could hash something like the current datetime or comibination of the model configuration and the current weights. Adding keyword arguments (e.g. `update_identifier=False`) to the `compile()` and the `fit()` method could enable users to set a new identifier when the model is trained or recompiled.  

Happy to talk about more details but would also appreciate feedback on the overall idea of having model id within keras and not relying on external model registrys! Thank you!

**Comment by fchollet** [comment]
Thanks for the proposal -- overall this feature seems very specific to your use case. A "model ID" could mean different things in different contexts (some people may want to use `id()` from Python). In your case you want to track model configuration and model state, rather than instance identity, and you're making the assumption that model state can only be changed via `compile()` or `fit()` (perhaps this is the case in your code, but in the general case there are many ways to modify model state, e.g. `model.layers[N].kernel.assign(V)`).

I would recommend maintaining your own model identification logic rather than adding a new Keras API.
