### ISSUE TITLE
Value error: Input 0 of layer "sequential" is incompatible with the layer: expected shape = (None,2566,256,1), found shape = (32,128,1)

### ISSUE THREAD

**Issue by Shaaniaa** [keras-team/keras#16347]
gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    gaussblur = cv2.GaussianBlur(gray, (5, 5), 2)
    smallthres = cv2.adaptiveThreshold(gaussblur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 9, 2.8)
    ret, final_image = cv2.threshold(smallthres, 70, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    cv2.imshow("BW", final_image)
    final_image = cv2.resize(final_image, (128, 128))
    
    final_image = np.reshape(final_image, (1, final_image.shape[0], final_image.shape[1],1))
    pred = model.predict(final_image)
    
    print(number_dict[np.argmax(pred)])
   cv2.putText(frame,number_dict[np.argmax(pred)], (10, 50), cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 1)
    cv2.imshow("Frame", frame)

HI i am getting value error on 4th last line which is pred = model.predict(final_image) and i dont know how to solve this error. Please help!

**Comment by TusharJ3011** [comment]
First, the dimension of the final image you are resizing in the line 
final_image = cv2.resize(final_image, (128, 128)) 
should be (2566, 256) as the input layer is of shape (None, 2566, 256, 1) <br>
Secondly, instead of resizing the image, you have to just increase the dimensions of the image to make it match the expected shape so, the following codes:
final_image = np.expand_dims(final_image, axis=0)  // To make the shape as (1, 2566, 256)
final_image = np.expand_dims(final_image, axis=-1) // To make the shape as (1, 2566, 256, 1)
should work if you replace these two lines with your the code:
final_image = np.reshape(final_image, (1, final_image.shape[0], final_image.shape[1],1))
the expand_dims method is used to do the task generally, so I recommend you to use this.

**Comment by Shaaniaa** [comment]
**I want to add that i am referencing this code https://github.com/AmanDesai10/Indian-Sign-Language-Recognition/blob/main/digit_recognition.py**

**I am getting this error after adding your lines in code**

Exception has occurred: ValueError
cannot reshape array of size 87000 into shape (1,1,290,1)
  File "[C:\Users\Dell\OneDrive\Documents\1-4-22\\digit_recognition.py]()", line 41, in <module>
    final_image = np.reshape(final_image, (  1, final_image.shape[0], final_image.shape[1],1))

**Comment by tilakrayal** [comment]
@Shaaniaa ,
While trying to execute the code i was facing issue `OSError: No file or directory found at model-try.h5.` Requesting to please provide the required dependencies to execute the code without fail.Thanks!

**Comment by Shaaniaa** [comment]
Hi first run digit_train.py file then digit_recognition.py and there in 4th last line it is model-mix-1.h5 
and the 4th last line is: classifier.save("model-mix-1.h5")
Make sure to change the path according to your directory 
Thanks.

**Comment by tilakrayal** [comment]
@Shaaniaa ,
I try to execute the code as mentioned and facing issue `OSError: No file or directory found at model-try.h5` while executing the `digit_recognition.py`.Can you please confirm if `model-mix-1.h5` and `model-try.h5` are same?Also requesting you to please provide the sequence of steps.Thanks!
