### ISSUE TITLE
Can not download MobileNetV2 96*96 alpha=1.4 - 404

### ISSUE THREAD

**Issue by FTPam** [keras-team/keras#16452]
```
2022-04-22 20:56:20.891050: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-22 20:56:21.366607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2155 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.4_96_no_top.h5

  line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

```https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.4_96_no_top.h5```

[[This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.4_96_no_top.h5</Details>
</Error>](https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.4_96_no_top.h5)](https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.4_96_no_top.h5)

**Comment by chunduriv** [comment]
@FTPam,

This error is due to unavailability of checkpoint.

 Currently for input size `96`, the available checkpoints for `MobileNetV2` are below

- mobilenet_v2_1.0_96
- mobilenet_v2_0.75_96
- mobilenet_v2_0.5_96
- mobilenet_v2_0.35_96

For `alpha` : `1.4`, currently supported input size is `224`. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/baeb50622a56463d5c7795b25070babf/16452.ipynb) for reference. 

For more details, please refer this [here](https://github.com/keras-team/keras/blob/master/keras/applications/mobilenet_v2.py#L44-L71). Thanks!

**Comment by old-school-kid** [comment]
@FTPam I believe the weights were populated directly from the checkpoints provided by the research team and there was no such model checkpoints provided by them.
