### ISSUE TITLE
Discretization layer, output_mode 'count'

### ISSUE THREAD

**Issue by ric97** [keras-team/keras#16483]
I would like to use this layer (below) in output_mode count, that seems like (from the doc) it can compute a sort of histogram.

`d = tf.keras.layers.Discretization(num_bins=100, output_mode='count')`

The error reported is the following:
`('Keyword argument not understood:', 'output_mode')`

How could I solve it?

**Comment by tilakrayal** [comment]
@ric97 ,
 In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.

**Comment by BertSam** [comment]
Hello, in the same optic, i'd like to use the Discretization layer with output_mode="count" to transform my data into an histrogram and all of that whithin a keras model. However, I have issus with the supported output rank. I'm trying to fing a workaround, but I also have somelimitation because of the supported input rank from the Conv2D layer.

See  a bit of my code and the error bellow:

```python
from tensorflow.keras.layers import Input, Activation, MaxPooling2D, Flatten, Conv2D, Dense, BatchNormalization, Discretization
from tensorflow.keras.models import Model


# weights init
keras_kernel_initializer = 'lecun_uniform'

# discretizer def
bins = [10., 27., 40., 51., 63., 75., 86., 99.] 
discretizer = tf.keras.layers.Discretization(bin_boundaries=bins,output_mode="count")

# param. def
x_out = Activation('softmax',name='output_softmax')(x)
ks = 3
f1 = 10

# Building the model 

input_shape = (16,100)
x = x_in = Input(shape=input_shape)

x = discretizer(x)

x = Conv2D(filters=f1, kernel_size=ks, padding='same', kernel_initializer=keras_kernel_initializer, name='conv2d_1')(x)
x = Activation('relu', name='relu_1')(x)
x = MaxPooling2D(name='pool_1')(x)

.
.
.

x_out = Activation('softmax',name='output_softmax')(x)

model = Model(x_in,x_out)
```
![image](https://user-images.githubusercontent.com/36937265/181552937-348cd656-151e-4306-ba60-0d035f1dd2df.png)
