### ISSUE TITLE
Some application_tests are disabled

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras#16540]
This was why:

https://github.com/keras-team/keras/pull/16528

was not caught in the original PR.

Relevant links:
- https://github.com/sayakpaul/keras/blob/patch-1/keras/applications/applications_load_weight_test.py#L135-#L139
- https://github.com/sayakpaul/keras/blob/2f54af1c18c0b46f3ab0d29cd96427352e023b09/keras/applications/applications_test.py#L183

**Comment by sachinprasadhs** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
