### ISSUE TITLE
Add types to keras functions/classes/methods

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#16691]
**System information**.

TensorFlow version (you are using): 2.9.1
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

Currently, when using an IDE (e.g. pycharm in my case), there is not types checks/type help when using keras functions, methods and classes instanciation. 

**Will this change the current api? How?**
No change in the api and behavior

**Who will benefit from this feature?**
Everyone using an IDE/mypy

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): Yes 
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): Progressively adding types to the codebase. 

I don't think that we can use mypy to check in the CI if the types we're adding are corrects, because 1) it has too many false positives, 2) requires a significant amount of code to be typed before giving useful errors.

If you are interested we can use something like typeguard in the CI only to check if our types are correct.

**Comment by gabrieldemarmiesse** [comment]
I made a small PR that should serve as exemple.

**Comment by gabrieldemarmiesse** [comment]
To be clear, this issue is only about typing the public API, not the whole codebase.

**Comment by gadagashwini** [comment]
Hi @gabrieldemarmiesse, Associated PR got merged can we close this issue. Thank you!

**Comment by gabrieldemarmiesse** [comment]
Hi, i only typed a small part of the public api. I believe this issue must stay open as long as the public api is not typed

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
