### ISSUE TITLE
minval can be greater than maxval in tf.keras.initializers.RandomUniform

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#16969]
minval should be less than maxval. However, when minval is greater than maxval, the code works.
```
import tensorflow as tf
results={}
try:
  minval = 10
  maxval = -6
  seed = 124
  arg_class = tf.keras.initializers.RandomUniform(minval=minval,maxval=maxval,seed=seed,)
  arg_input = [9,6,7,]
  results["res"] = arg_class(arg_input)
except Exception as e:
  results["err"] = "Error:"+str(e)
```

**Comment by tilakrayal** [comment]
@cheyennee,
The output of the minval and maxval was working as expected in `tf.keras.initializers.RandomUniform`. Also we change the min and max values the output was different in both the cases. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/fad95bd0bc78be5d631e143d82c7f12d/untitled561.ipynb).

**Comment by cheyennee** [comment]
@tilakrayal  In other API, when minval is greater than maxval, it will throw an exception. I dont know why tf.keras.initializers.RandomUniform doesnt throw an exception, although it works as expected.

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensoflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8cd1c82577ee3e4f8857ec844dc56afa/untitled584.ipynb).

**Comment by old-school-kid** [comment]
@gadagashwini @cheyennee 
Logically, yes it should throw an error. But i tried it multiple times and it initializes values in range `[minval, maxval]` or `[maxval, minval]` whichever holds. 
I would be happy to send a PR, in case we think it is rquired.

**Comment by SuryanarayanaY** [comment]
@cheyennee , @old-school-kid ,

The function `tf.keras.initializers.RandomUniform ` internally relies on `tf.random.uniform` .Both these APIs raises error when the `dtype` is `int`. However with float dtype the implementation not validating this values but these values seems taken as a range and the outputs are generated within this range.Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/bb16a0717b24e2d39e18d420624dbcac/16969.ipynb).

Logically this should throws an error but implementation is otherwise taken care as range for output.I am not sure this is intended or not but for uniformity the behaviour should be same for int and float data types. But for performance reason this validation might be skipped as implementation is taken care of that in another way.

If you believe this validation is important and willing to propose a PR please feel free to do and let Team review and comment on it. Thanks!
