### ISSUE TITLE
2.10.0: not ready for pep517 build spec?

### ISSUE THREAD

**Issue by kloczek** [keras-team/keras#16981]
Looks like `keras` is not ready for pep157 build procedure.
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
ERROR Source /home/tkloczko/rpmbuild/BUILD/keras-2.10.0 does not appear to be a Python project: no pyproject.toml or setup.py
```
🤔

**Comment by tilakrayal** [comment]
@kloczek,
Could you please provide the build source you are trying to install. Also please try to install the latest stable v2.9.0 from [here](https://github.com/tensorflow/tensorflow/tree/v2.9.0) and let us know if you are facing the same issue. Thank you!

**Comment by kloczek** [comment]
> @kloczek, Could you please provide the build source you are trying to install. Also please try to install the latest stable v2.9.0 from [here](https://github.com/tensorflow/tensorflow/tree/v2.9.0) and let us know if you are facing the same issue. Thank you!

I'm usimg Source tar ball autogenerated from git tag.
https://github.com/keras-team/keras/archive/refs/tags/v2.10.0.tar.gz

**Comment by kloczek** [comment]
Here is result with v2.9.0
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
ERROR Source /home/tkloczko/rpmbuild/BUILD/keras-2.9.0 does not appear to be a Python project: no pyproject.toml or setup.py
```

**Comment by kloczek** [comment]
BTW on https://pypi.org/project/keras/ latest version is 2.10.0.

**Comment by ianstenbit** [comment]
@qlzh727

**Comment by ianstenbit** [comment]
Hi @kloczek,

TensorFlow and Keras both use their own build process, which does not follow the 517/setup.py paradigm.
It may not be feasible to add support for Pep517 due to the inclusion of a Bazel `BUILD` rule, which is a reserved keyword in 517.

(As an example error when trying to build with a `setup.py`: `error: could not create 'build': File exists`.)

Is there some use case that you're unable to achieve due to this?

**Comment by kloczek** [comment]
> (As an example error when trying to build with a `setup.py`: `error: could not create 'build': File exists`.)

pep517 has nothing to do with setup.py or `setuptools` genrally. `setuptools` and setup.py may be used but it is not needed/is not essential. If you want you want you may use any other pep17 backend like `poetry`, `hatch`, `whey`, `flit`, `bento` and many other (and `setuptools` as well)

PEPs are documents with some standards of fetures and processes which python modules should fillow.
https://peps.python.org/pep-0517/
I don't think that it is any PEP ducument about Bazel.

**Comment by ianstenbit** [comment]
Thanks for following up -- I recognize what PEP517 is, and we use `setuptools` to support it on other packages. However, given that Keras and TF use a separate build process, I'm not sure I understand what the problem is with not adopting pep517.

Can you please clarify what use case is prevented by this?

**Comment by kloczek** [comment]
It prevents package `keras` module using pep517 build procedure because there is no setyp.py or pyproject.toml file in source tree.
`setuptools` cannot be used as well because there is no setup.py file.

**Comment by SuryanarayanaY** [comment]
Hi @kloczek ,

The `setup.py` file is located at [here](https://github.com/keras-team/keras/blob/master/keras/tools/pip_package/setup.py).

Even for tensorflow also the `setup.py` lies under tensorflow/tools/pip_package/setup.py only.

I am interested to know is this is issue for Keras only or Tensorflow also. Please check and confirm if this is still an issue.

Thanks!

**Comment by kloczek** [comment]
So why that file is not in root direcory of the project like in case of of all python modules source trees? 🤔

**Comment by haifeng-jin** [comment]
We use the following script to build the package (@qlzh727 may confirm this):
https://github.com/keras-team/keras/blob/v2.12.0/keras/tools/pip_package/build_pip_package.sh

@kloczek Would this be good enough for doing everything you need? or any specific workflow is still not supported?

**Comment by kloczek** [comment]
pep517 has nothing to do with pip. Usimg that standard is possible to build, installl module without pip.
Really .. please provide pep571 build procedure support https://peps.python.org/pep-0517/

PS. I have ATM +1.1k packaged modules as rpm packages. 100% of them are pep517 compliant.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
