### ISSUE TITLE
TypeSpec `tf.keras.layers.Input` fails to propagate the name property 

### ISSUE THREAD

**Issue by nmatare** [keras-team/keras#17113]
**System information**.
```
import tensorflow as tf
tf.__version__
2.8.2
```

**Describe the problem**.

Specifying a keras input layer with TypeSpec fails to propagate the layer name.

Patching the hidden attribute `_name` works only for the current session. Otherwise, de(serializing) the model fails with the layer defaulting to the `None` name.

This is true of dense, ragged, and sparse tensors.

**Describe the current behavior**.

```
type_spec = tf.TensorSpec(name='test', shape=(None, None, 2))
input1 = tf.keras.layers.Input(type_spec=type_spec)

assert input1.name is None
```

**Describe the expected behavior**.

```
type_spec = tf.TensorSpec(name='test', shape=(None, None, 2))
input1 = tf.keras.layers.Input(type_spec=type_spec)

assert input1.name == 'test'
```

**Comment by sushreebarsa** [comment]
@nmatare I tried to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/edbad638fd6791af852c7426417fd81a/untitled719.ipynb#scrollTo=P89jqIbqgzyk) here and confirm the same?
Thank you!

**Comment by nmatare** [comment]
Confirmed! The name should not be `None`, it should be "test".

**Comment by hertschuh** [comment]
@nmatare 

It is easy to change the code to propagate the `name` argument to the `InputLayer`. The `InputLayer` would then have that name, which would for instance be visible in the model summary (the name of the layer is on the left):

```
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 test (InputLayer)           [(None, None, 2)]                 0         
```

However, with that change in place, the test as you wrote it would still fail. In fact if you do `tf.keras.layers.Input(..., name="test")` today, it also fails.

That's because `Input` is not an actual class. It is a function, and under the hood it creates an `InputLayer`. But [what is returned](https://github.com/keras-team/keras/blob/v2.10.0/keras/engine/input_layer.py#L442) is not the `InputLayer` itself but a Keras tensor representing the output of the `InputLayer`, which won't have the name.

Would that still work for your use case? By the way, what is your use case for this, what is the use for the name in the end?

**Comment by nmatare** [comment]
Unfortunately, this seemingly insignificant name issue causes a lot of down stream effects. I've hacked around them for some, but I decided to file a bug because the solutions started to get too involved.

Three issues I've encountered with the None name problem:

1. It breaks the name of the tensor. (The value assigned by TensorFlow in the graph) And so in order to get an expected name, say if you have to reference that tensor later, you have to create another layer to rename the tensor. This can get pretty convoluted for complex architectures.

2. It breaks the serializer. If you save the tensor and you deserialize it in another session, the intervals will break as it's expecting a byte or string type and not none.

3. The only way to create ragged or sparse tensors is with the type_spec param, and however much you can defeat this with the Layer solve for dense tensors, you arrive back here for nonstandard tensors.

I hope that helps!

**Comment by bjessen** [comment]
Just for fun, we need to patch 2 points in the `tf.keras.layers.Input` function:
[setting the name property](https://github.com/keras-team/keras/blob/b80dd12da9c0bc3f569eca3455e77762cf2ee8ef/keras/engine/input_layer.py#L398): 
`'name': name if name else type_spec.name`


[pushing it back the name into the returned tensor](https://github.com/keras-team/keras/blob/b80dd12da9c0bc3f569eca3455e77762cf2ee8ef/keras/engine/input_layer.py#L443)
<pre>
outputs = input_layer._inbound_nodes[0].outputs
if isinstance(outputs, list) and len(outputs) == 1:
   output = outputs[0]
else:
   output = outputs
output._name = input_layer.name
return output
</pre>

but... feels hackish. Not mentioning that I'm assuming that `_name` will be available and writable.
That said, @nmatare if you're desperate enough, you can create a patched `Input` and monkey patch the original one in `tf.keras.layers` before defining your model.

**Comment by hertschuh** [comment]
@nmatare 

- Oh so it looks like you're using Tensorflow in "TF1" mode (using `Session`)
- Also, just to clarify, this issue is unrelated to `TypeSpec`, it applies to `keras.Input` and naming more generally

Questions for you:
- About 2., what do you mean by serialization? How are you saving your model?
- Does @bjessen 's suggestion work? If we found a proper way to assign the name of the output, would it actually solve your problems? The reason I'm asking is that the returned value of `tf.keras.layers.Input` is a "Keras tensor", which is just an intermediate to build the model. But the graph you manipulate in a `Session` is something different with different tensors.

Thanks!

**Comment by hertschuh** [comment]
@nmatare ,
If this is a feature request for Tensorflow 1 (TF1) specifically, we're not adding new features in Keras for TF1.
I'm closing this now, let me know if you have further questions.
