### ISSUE TITLE
Why do you depend on tf-nightly and not a regular tensorflow release?

### ISSUE THREAD

**Issue by yurivict** [keras-team/keras#17248]
It's hard to chase nightly releases in the ports context.

**Comment by tilakrayal** [comment]
@yurivict,
The **tf-nightly** pip package is built and released to [PyPI](https://pypi.org/project/tf-nightly/) every night (barring any build failures). As a result, you can see an [almost once-per-day version update history](https://pypi.org/project/tf-nightly/#history). 
TF-nightly has the latest features close to the HEAD of the master branch of [github.com/tensorflow](https://github.com/tensorflow/tensorflow). Therefore, if you want the latest features, improvements and bug fixes, such as the ones committed after the last stable tensorflow release , you should use `pip install tf-nightly`. 
But the downside is that because tf-nightly releases are not subject to the same strict set of release testing as tensorflow, it will include bugs that will be fixed later.  Also, since it's built from HEAD, it'll reflect intermediate development status such as incompleteness in features.

```
python3 -m pip install tf-nightly
# Verify install:
python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```

The tensorflow pip package is released by a semantic-version-based schedule. A new version is pushed out approximately once 2-6 months. Due to the comprehensive set of release testing jobs, the quality is higher than tf-nightly.

**Comment by yurivict** [comment]
But why do you, the keras project, need to depend on the less stable version of TF with the newest features?
When users choose to install a particular revision of keras, they implicitly choose stability. Also a fixed Keras version should only depend on features in a fixed TF release. Newest and latest features would remain unused anyway.

**Comment by tilakrayal** [comment]
@yurivict,
As mentioned the tf-nightly pip package is built and released to [PyPI](https://pypi.org/project/tf-nightly/) every night (barring any build failures). As a result, you can see an [almost once-per-day version update history](https://pypi.org/project/tf-nightly/#history).

If you choose tf-nightly it will change the features every night. So we request the community to choose tensorflow stable version which is compatible with the Keras rather than tf-nightly. Thank you!
