### ISSUE TITLE
Computing gradients for KerasTensors and allowing other operations

### ISSUE THREAD

**Issue by DavidLandup0** [keras-team/keras#17389]
**System information**.

TensorFlow version (you are using): 2.11
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

I was doing a Forward-Forward Algorithm (Hinton, https://www.cs.toronto.edu/~hinton/FFA13.pdf) implementation in TensorFlow to share it as an interactive demonstration, and hopefully encourage discussions on backprop alternatives. This is a non-standard operation ("goodness" function using intermediate ReLU activations), but uses exclusively components of TF/Keras that already exist, and should conceptually work.

Though, there seems to be an issue that prevents FFA from being implementable in TF since KerasTensors don't support various operations.

 Any loss function that wants to calculate gradients on intermediate outputs wouldn't work because functional APIs (both the Functional API and Functional Subclassing API) convert to `KerasTensor`, for which gradients aren't computable with `GradientTape`, and the Subclassing API doesn't have an explicit structure laid out for each model.

> This effectively makes implementing loss functions (the "goodness function" as noted in the paper) that depend on the intermediate activations/outputs impossible.

For FFA - we want to compute the sum of the squares of ReLUs, which can't be done on a `KerasTensor`.

For reference, here's the code: https://github.com/DavidLandup0/TF-Forward-Forward-Algorithm

#### Functional API

When writing custom loss functions (that make use of intermediate activations), `KerasTensor`s (such as when using the Functional API), can't compute gradients: https://github.com/tensorflow/tensorflow/issues/46194#issuecomment-827036146

This results in a:

```
AttributeError: 'KerasTensor' object has no attribute '_id'
```

For:

```
tape.gradient(some_loss, model.trainable_weights)
```

#### Subclassing API

Using the Subclassing API, there's no inherent structure that can be inferred (due to the arbitrary code that can be executed in the `call()`) function, so intermediate layer activations can't be accessed, as there are no incoming nodes for any layer. This makes sense:

```
Layer relu has no inbound nodes.
```

#### Functional Subclassing API

Functional Subclassing API (clear structure that comes from the defined inputs and outputs,  suffers from the same issue:

```
AttributeError: 'KerasTensor' object has no attribute '_id'
```

**Will this change the current api? How?**

Since `KerasTensor`s are internal, no API change for end-users would occur.

**Who will benefit from this feature?**

The research community and those who want to customize their models, while making use of TF/Keras' amazing ecosystem and balance between high-level and low-level APIs.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

@haifeng-jin @fchollet

**Comment by DavidLandup0** [comment]
Relevant other issues:

- https://github.com/keras-team/keras/issues/17176
- https://github.com/tensorflow/tensorflow/issues/48531

**Comment by hertschuh** [comment]
@DavidLandup0 ,

`KerasTensor` is a temporary construct. Its purpose is to connect the dots while building a functional model. Basically, it tracks the connections between layers, etc. Once the model is connected, it does not serve any purpose. The way it works, it does look like you're creating a graph of arbitrary operations, but the graph connecting `KerasTensor`s is a separate thing from the graph of Tensorflow operations that is created when running the model.

And there are indeed limitations with `KerasTensor`. Making `KerasTensor` a subclass of `tf.Tensor` would probably be beneficial in some ways, but would be a major rework of the whole `KerasTensor` system.

> Subclassing API

In this case, the model is not a functional model, so the `input` and `output` are not populated since they are not used to connect the layers or operations.

**That being said, I think what you're trying to do is achievable.**

If you want a `GradientTape`, you'll need to do this outside of the model and in the training loop. Then, in the training loop you can modify the gradients the way you want before applying them via the optimizer. I was able to do something similar to what this [colab](https://colab.sandbox.google.com/gist/tilakrayal/7b6386e1bf710ea29e5e1f9e4657c0f3/48531.ipynb#scrollTo=HbcxNS5SgJZi) was trying to do, but it seems like it's very different from what you're trying to do with FFA.

I was looking at your [notebook](https://github.com/DavidLandup0/TF-Forward-Forward-Algorithm/blob/main/FFA.ipynb) and the part that fails (the last cell).
- `relu_activations = model.get_layer('relu').output`. If I understand correctly, you're using `.output` as if it was a snapshot of the last result of the last pass on this layer. But that's not the case. And that's unrelated to `KerasTensor`. There is nothing in Tensorflow that will take snapshots of the last pass for you. The easiest way to access this intermediary result would be to return it alongside the main model output. You can make it a `tuple` or a `dict` or whatever.
```python
class FF(tf.keras.Model):
    def __init__(self):
        super(FF, self).__init__()
        self.flatten = layers.Flatten()
        self.d1 = layers.Dense(128)
        self.relu = layers.Activation('relu', name='relu')
        self.d2 = layers.Dense(10, activation="softmax")

    def call(self, x):
        x = self.flatten(x)
        x = self.d1(x)
        relu_output = self.relu(x)
        x = self.d2(relu_output)
        return x, relu_output
```
- `with tf.GradientTape() as tape:` You're using a grading tape, but then you're not using the tape. If FFA doesn't use gradients at all, then just remove this line altogether.
- `model.trainable_weights = model.trainable_weights + 0.01* np.array(positive_goodness)`. Variables work differently, you'll have to use [`tf.Variable.assign_add`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) or `assign_sub` to achieve this. Something like:
```python
for var, pos, neg in zip(model.trainable_weights, positive_goodness, negative_goodness):
  var.assign_add(0.01 * pos - 0.01 * neg)
```

I hope this helps.

**Comment by hertschuh** [comment]
@DavidLandup0 ,
Closing the issue, let me know if you have further questions.
