### ISSUE TITLE
ImageDataGenerator Issue: "height_shift_range" shifts the image horizontally and "width_shift_range" shifts the image vertically

### ISSUE THREAD

**Issue by Sarthak3003** [keras-team/keras#17398]
This is a sample code where I used ```height_shift_range``` and it shifted the image horizontally

![img 1](https://user-images.githubusercontent.com/80020340/211006920-b33f16c7-fbce-45b6-b977-2ae654fe8062.jpg)

And this is when I use ```width_shift_range```

![image](https://user-images.githubusercontent.com/80020340/211007203-2fd21d79-d75b-48ae-9192-e80284bcf4a7.png)

**Comment by tilakrayal** [comment]
@Sarthak3003,
Could you please provide the code in the text format rather than image format, it will be helpful for us to analyse and debug the issue. Thank you!

**Comment by Sarthak3003** [comment]
@tilakrayal ,
Here is the code.


img = load_img('aug.jpg')
data = img_to_array(img)

samples = expand_dims(data, 0)
datagen=ImageDataGenerator(width_shift_range=[-50,50])
iterator=datagen.flow(samples,batch_size=1)
for i in range(9):
	pyplot.subplot(330 + 1 + i)
	batch = iterator.next()
	image = batch[0].astype('uint8')
	pyplot.imshow(image)
pyplot.show()

**Comment by tilakrayal** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from **keras-team/keras-core** to **keras-team/keras.**
Consequently, This issue may not be relevant to the `Keras 3 `code base. After the migration is successfully completed, feel free to reopen this issue at **keras-team/keras** if you believe it remains relevant to the `Keras 3` code base. 
If instead this issue is a bug or security issue in legacy **tf.keras**, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about `Keras 3,` please take a look at https://keras.io/keras_core/announcement/. Thank you!
