### ISSUE TITLE
Feature extraction in pretrained model: different result from keras 2.3 to keras 2.4

### ISSUE THREAD

**Issue by AmericaBG** [keras-team/keras#17435]
I'm extracting features from a pretrained keras model (VGG16).The task is simple but I obtain different features (nx4096) when I run the code on keras 2.4.1 and tensorflow 2.3.0 or  keras 2.3.1 (tensorflow backend) y tensorflow 2.2.0.

The differences in the features are huge and when I use the different extracted features in a classifier, I obtain very much better results with those obtained on keras 2.3.1.

Could someone explain me why?

I write the code in case it is useful:
```
from keras.preprocessing import image
from keras.applications.vgg16 import VGG16
import tensorflow.keras
from keras.applications.vgg16 import preprocess_input
import numpy as np
from sklearn.cluster import KMeans

import matplotlib.pyplot as plt
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import decode_predictions
from keras.models import Model
from pickle import dump

model = VGG16(weights='imagenet')#, include_top=False

model = Model(inputs=model.inputs, outputs=model.layers[-2].output)

model.summary()

trainstack=np.load('.../All_imgs.npy')
trainstack=np.transpose(trainstack,[2,0,1,3])
trainstack=preprocess_input(trainstack)
trainstacklabel=np.load('.../All_labels.npy')
    
img_data = preprocess_input(trainstack)
vgg16_feature_list=[]

for i in range(trainstack.shape[0]):
    
    v =img_data[i,:,:,:]
    v=v[np.newaxis,...]
    vgg16_feature = model.predict(v)
    print (vgg16_feature.shape)
    vgg16_feature_np = np.array(vgg16_feature)
    vgg16_feature_list.append(vgg16_feature_np.flatten())

np.save('.../features.npy',vgg16_feature_list)

```
Thank you very much in advance!

**Comment by tilakrayal** [comment]
@AmericaBG,
When you create a model of your own which uses a keras application it loses precision since the computation is too expensive. On the other hand the output of the **keras.application** model when used as-is doesnot have to go through that problem. Also you can see there is a microscopic difference in the results though. You can still decrease the number by changing the [mixed precision policy](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/set_global_policy). Thank you!
