### ISSUE TITLE
Unexpected behavior of `trainable` attribute

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18092]
**System information**.

- TensorFlow 2.11, 2.12
- OS. Linux

**Describe the problem**.

This issue is originated from [this](https://stackoverflow.com/q/76167270/9215780) post. The `trainable` feature is behaving unpredictably depending on how we define the model. For example, I want to freeze a model first and then unfreeze some layers. But depending on how I define the model, the unfreezing method is not working with trainable features. 

See the following two model definision. Both models are initiated and kept frozen. 

```python
def get_model_a():
    keras.backend.clear_session()
    # Load pretrained model
    model = tf.keras.applications.mobilenet_v2.MobileNetV2(
        input_shape=None,
        alpha=1.0,
        weights='imagenet',
        classifier_activation=None
    )
    model.trainable = False
    return model


def get_model_b():
    keras.backend.clear_session()
    inputs = keras.layers.Input(shape=(224, 224, 3))
    base_model = keras.applications.mobilenet_v2.MobileNetV2(
        input_tensor=inputs,
        weights="imagenet",
        alpha=1.0,
        classifier_activation=None
    )
    base_model.trainable = False  # this is important
    model = tf.keras.Model(
        inputs, base_model.output
    )
    # model.trainable = False # won't work! why?
    return model

# unfreeze some layers 
# model_a = unfreeze( get_model_a(), target_layer=[layer1, layer2] )
# model_b = unfreeze( get_model_b(), target_layer=[layer1, layer2]  )

# NOT OK
# model_a.summary
Total params: 3,538,984.0
Trainable params: 0.0
Non-trainable params: 3,538,984

# OK
# model_b.summary
Total params: 3,538,984
Trainable params: 55,632
Non-trainable params: 3,483,352
```

**Reproducible code**

Here is the [gist](https://colab.research.google.com/drive/1S7Vc16rj3KeJG5oEuq0oHWmmaSL8Ufxm?usp=sharing).

**Comment by Frightera** [comment]
This seems like a bug, when I try to print if the selected layers are trainable, they are indeed unfrozen:

![image](https://user-images.githubusercontent.com/46622558/236073661-83de2387-7597-45da-b8b1-392e92b3e5f7.png)

Probably coming from here:

https://github.com/keras-team/keras/blob/fa4b7a3bb4883282e58d034e02808dbd3d1b8cac/keras/engine/base_layer.py#L1303-L1320

In your first example you set `model.trainable = False` so `trainable_weights` property becomes an empty list and shows incorrect information in `model.summary()` etc.

**Comment by innat** [comment]
Right. In the first example, 

```python
# with model attributes [shows bug]
model.trainable = False
    
# with layer attribute, works
for layer in model.layers:
   layer.trainable = False
```

From the [doc](https://keras.io/guides/transfer_learning/), 


```python
inner_model = keras.Sequential(
    [
        keras.Input(shape=(3,)),
        keras.layers.Dense(3, activation="relu"),
        keras.layers.Dense(3, activation="relu"),
    ], name='inner_model'
)
model = keras.Sequential(
    [
        keras.Input(shape=(3,), name='input'), 
        inner_model, 
        keras.layers.Dense(3, activation="sigmoid", name='dense'),
    ], name='model'
)
print_model_params(model)
Total params: 36.0
Trainable params: 36
Non-trainable params: 0.0
```
```python
model.trainable = False
print_model_params(model)
Total params: 36.0
Trainable params: 0.0
Non-trainable params: 36

inner_model.trainable = True
print_model_params(model)
Total params: 36.0
Trainable params: 0.0
Non-trainable params: 36

for layer in model.layers:
    if layer.trainable:
        print(layer.name)
inner_model
print(model.trainable_variables)  # []
```

**Comment by tilakrayal** [comment]
@innat,
Could you please confirm whether the PR #https://github.com/keras-team/keras-cv/pull/1746 are related to this issue. Also i tried on tf-nightly, there was little difference from the v2.12 gist. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/df803a5b4ca0399856e2bdcc906626c2/trainable_attributes_keras.ipynb). Thank you!

**Comment by innat** [comment]
@tilakrayal Thanks for checking. 

> Could you please confirm whether the PR #https://github.com/keras-team/keras-cv/pull/1746 are related to this issue.

No. You can completely ignore that PR. 

>  Also i tried on tf-nightly, there was little difference from the v2.12 gist. 

I've tried with TF 2.11, 2.12, and 2.14.0-dev20230506. My report is same and unchanged. 


**issue**

In the above gist, we freeze the whole model first and later pick some layers (say 5) to unfreeze those. We define that model in two different ways (in gist, `get_model_a` and `get_model_b`). Now, at the end, `model.summary` is not identical for both model (after unfreeze some layers of this two model). 

[Gist.](https://colab.research.google.com/drive/1S7Vc16rj3KeJG5oEuq0oHWmmaSL8Ufxm?usp=sharing)

**Comment by ianstenbit** [comment]
Hey @innat -- thanks for the issue!

This is actually working as intended, but the behavior is a bit complex. Let me explain a bit :)

For `model_a`, we expect all weights to be non-trainable because _the model itself_ is not trainable. If any Keras layer (including a model) is non-trainable, then all of its children are necessarily non trainable. If we want to make sub-layers trainable, we have to make the parent trainable too.

In `model_b`, the `base_model` doesn't actually exist in the resulting model. This is a result of how `get_model_b` is implemented.  `get_model_b` creates a functional model which traces through the graph of the `base_model` but doesn't actually _call_ the `base_model`, so the state of the `base_model` is bypassed by the resulting model, as the `base_model` is just treated like a list of layers, not a model.

In order to use the `base_model` as as true Keras model, we need to _call_ it instead of extracting its output. Below, I've written a new version, `get_model_c`, which does exactly this.

```
def get_model_c():
    keras.backend.clear_session()
    inputs = keras.layers.Input(shape=(224, 224, 3))
    base_model = keras.applications.mobilenet_v2.MobileNetV2(
        weights="imagenet",
        alpha=1.0,
        classifier_activation=None
    )
    outputs = base_model(inputs)
    base_model.trainable = False  # this is important
    model = tf.keras.Model(
        inputs, outputs
    )
    return model
```

With this model, you'll find that the `trainable` state of `base_model` is preserved in the resulting `model_c`, and unless you update it to `trainable=True`, all weights of `model_c` will be non-trainable, which is the intended behavior because the `base_model` itself is not trainable.

A great way to visualize the difference between `model_b` and `model_c` is by calling `keras.utils.plot_model(model_{b/c}` and seeing that in `model_b`, all of the underlying layers of `base_model` are copied over as Keras layers, whereas in `model_c`, the `base_model` is treated as one layer, whose state is persisted.

**Comment by innat** [comment]
@ianstenbit 
Thanks for the details answer. I think it would be nice if your answer could be documented in keras-io (in FAQ). 

---

In the gist, after unfreezing the `mode_a`, the model summary returns 0.0 trainable params but if we interate over the layers manually we can see the selected layers become trainable. WDYT?

```python
selected_layers = [
    'expanded_conv_depthwise_relu',
    'expanded_conv_depthwise',
    'block_13_pad',
    'block_2_project_BN',
    'block_11_expand'
]
unfreeze(model_a, selected_layers)

print_model_params(model_a) 
Total params: 3,538,984.0
Trainable params: 0.0
Non-trainable params: 3,538,984

for layer in model_a.layers:
    if layer.trainable:
        print(layer.name)
expanded_conv_depthwise
expanded_conv_depthwise_relu
block_2_project_BN
block_11_expand
block_13_pad
```

**Comment by innat** [comment]
@ianstenbit 
Any thoughts on this?

**Comment by ianstenbit** [comment]
@innat yeah, for `model_a`, because the model itself isn't trainable, the trainability of the sublayers isn't taken into account.

There is a good example [here](https://keras.io/guides/transfer_learning/#recursive-setting-of-the-trainable-attribute) on KerasIO which talks through the behavior of layer trainability, and mentions that an untrainable parent layer makes child layers untrainable.

If there's something lacking in the description there, please feel free to open a PR on KerasIO!
Thanks!

**Comment by innat** [comment]
@ianstenbit 
[Here](https://github.com/keras-team/keras/issues/18092#issuecomment-1544503977), as you notice the `print_model_params(model_a)` returns 0 trainable params but if you iterate over the layers, you would get `layer.trainable` is True. The number of trainable params is not counted in model summary.

**Comment by ianstenbit** [comment]
> @ianstenbit [Here](https://github.com/keras-team/keras/issues/18092#issuecomment-1544503977), as you notice the `print_model_params(model_a)` returns 0 trainable params but if you iterate over the layers, you would get `layer.trainable` is True. The number of trainable params is not counted in model summary.

Maybe I'm misunderstanding the question, but this behavior seems correct to me. For `model_a`, the model itself isn't trainable, so we'd expect the number of trainable params to be 0.
