### ISSUE TITLE
Is it not posible to make recurrent neural networks that work with sparse tensors in keras?

### ISSUE THREAD

**Issue by vrunm** [keras-team/keras#18253]
I'm writing a neural network to process medical text entries an classify them into diferent categories in python3. The idea would be to use a LSTM layer followed by a Dense layer to do so. I have a large dataset which I codify in a per word basis into one-hot vectors to feed it as inputs to the network, this results in a lot of memory wasted on zeroes which means that an sparse representation of the data is necesary.

This is the code for the model:
```
import tensorflow as tf

in_shape=(8, 4581, 2126) 
out_size=200

data= tf.sparse.SparseTensor(indices=[[0,0,0]],values=[1],dense_shape = in_shape)

X_i = tf.keras.Input(shape= tf.shape(data)[1:], sparse=True) #shape=(None,)

X = tf.keras.layers.LSTM(in_shape[-1])(X_i)

X = tf.keras.layers.Dense(out_size)(X_i)
    
X = tf.keras.layers.Activation('sigmoid')(X)

model = tf.keras.Model(X_i, X)
```
4581 is the max length of the text entries i have been testing in

2126 is the number of words in the vocabulary already with far more prunnig than I'm comfortable with (since I need to classify medical texts into medical categories technical terms may be key to make a good prediction but appear very few times)

8 is the number of entries I can work with without sparse vectors and no memory problems

However when creating the model I get the following error:

    TypeError Traceback (most recent call last) ~/Henv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)

    548 try:

    --> 549 str_values = [compat.as_bytes(x) for x in proto_values]

    550 except TypeError:

    ~/Henv/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in <listcomp>(.0)

    548 try:

    --> 549 str_values = [compat.as_bytes(x) for x in proto_values]

    550 except TypeError:

The complete error message is quite massive, that was the start of the message.

`TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("inputs:0", shape=(None, 3), dtype=int64), values=Tensor("inputs_1:0", shape=(None,), dtype=float32), dense_shape=Tensor("inputs_2:0", shape=(3,), dtype=int64)). Consider casting elements to a supported type.`

The error happens in the LSTM layer.

I tried to make it a simple NN only using a dense layer (adjusting the input size accordingly) to see if the problem was general and not due to the LSTM layer but it worked correctly. (Unfortunately I can't not use a RNN)

I tried to use other RNN layers like SimpleRNN and GRU but both gave the same error.

Small scale implementations with dense tensor worked properly (bigger ones give memory problems), it's only when going to sparse tensors that the problem arises. I used [this](https://www.tensorflow.org/guide/sparse_tensor) as a "guide" to make the change.

Since the LSTM layer not liking sparse tensors seemed to be the problem I tried to add a dense layer before (dense layers output standard tensors). Didn't work, same error (but now in the new dense layer).

**Comment by NicholasCJL** [comment]
Replicated on keras 2.12.0 with tensorflow 2.12.0

The issue first arises in this call in the LSTMCell class: https://github.com/keras-team/keras/blob/5f9d052566f92821b323dabb111eb4679624ddfb/keras/layers/rnn/lstm.py#L279

which fails when the `ContextValueCache` tries to generate the dropout mask, which calls `tf.ones_like(inputs)` which does not support `SparseTensors`.

In the case of first passing the input into a `Dense` layer, the issue arises here in the `Dense` class:
https://github.com/keras-team/keras/blob/5f9d052566f92821b323dabb111eb4679624ddfb/keras/layers/core/dense.py#L243-L244

The class explicitly checks if the input is a `SparseTensor` if its rank is 2 or `None`, but your input tensor here is of rank 3. The `tf.tensordot` operation here fails due to that.

As an aside, you probably do not need the same number of LSTM cells as your vocabulary size. That will greatly reduce the size of your LSTM layer. 

Additionally, you probably do not need to convert your input to a `SparseTensor` if memory is your concern. Take a look at the `Embedding` layer to project your high dimensional input into a significantly lower number of dimensions. This will let you increase the size of your vocabulary without running into memory issues too.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.12 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/453fece0b0ba6a48b408b63a48ea4802/untitled1216.ipynb).

**Comment by vrunm** [comment]
The functionality works with dense vectors. The issue arises with sparse vectors. I would like to implement the RNN using sparse vectors.

**Comment by hertschuh** [comment]
Varun,

Just in general, sparse tensors have limited support, meaning that very few Keras layers and Tensorflow operations will work with them. RNNs in particular are not supported.

As an alternative, would you be able to use ragged tensors instead of sparse tensors? Ragged tensors have broader support.

Thanks,
Fabien

**Comment by vrunm** [comment]
Sure I will check out this functionality using ragged tensors for RNNs.
