### ISSUE TITLE
LSTM layer trained on GPU -> cannot load on CPU (No OpKernel was registered to support Op 'CudnnRNN' )

### ISSUE THREAD

**Issue by lbortolotti** [keras-team/keras#18504]
Hi.

I'm training a model with a LSTM layer, which gets trained on GPU, and for which I believe the "cuda optimized" implementation is automatically being used at train time.

If I save this model as a TF savedmodel, upon loading I get the following error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node StatefulPartitionedCall/lstm_1/CudnnRNN}} with these attrs: [rnn_mode="lstm", dropout=0, seed=0, is_training=true, direction="unidirectional", T=DT_FLOAT, seed2=0, input_mode="linear_input"]
Registered devices: [CPU]
```

tf.keras does not exhibit the same behaviour - I suspect it's automatically dealing with falling back to a non-Cudnn version of the RNN layer?

Code to reproduce:

# 1: Train + save code (run with GPU available)

## NB: Switching the keras import to tf.keras makes the model load work correctly!
```
import os

os.environ["KERAS_BACKEND"] = "tensorflow"

import numpy as np

import keras_core as keras
# from tensorflow import keras # If I switch to this keras implementation, the model load works correctly!

window_size = 500
X = np.zeros((1024, window_size, 1))
Y = np.zeros((1024, window_size, 1))

n_layers = 2
n_units = 256
n_epochs = 2
batch_size = 32

# MODEL
x_in = keras.layers.Input(shape=(window_size, 1))

x = x_in

for _ in range(n_layers):
    x = keras.layers.LSTM(n_units, return_sequences=True, stateful=False, activation='tanh')(x)

y = keras.layers.Dense(1, activation='linear')(x)

model = keras.models.Model(inputs=x_in, outputs=y)

model.compile(optimizer=keras.optimizers.Adam(), loss=keras.losses.mean_squared_error)

model.summary()

print(f'X shape: {X.shape}')

model.fit(X, Y, epochs=n_epochs, batch_size=batch_size)

model.save('lstm_model.keras')

import tensorflow as tf

module = tf.Module()
module.model = model

# batch size = 1 in inference, variable length
SHAPE = (batch_size, window_size, 1)


# SHAPE = (1, None, 1)
@tf.function(autograph=True, input_signature=[tf.TensorSpec(shape=SHAPE, dtype=tf.float32)])
def fn(x):
    outputs = model(x)
    return outputs


module.fn = fn

tf.saved_model.save(module, 'lstm_model.tf', signatures={'serving_default': module.fn})
```

# 2: Load model code (run without GPU available)

```
import numpy as np
import tensorflow as tf

model = tf.saved_model.load('lstm_model.tf')

batch_size = 32
window_size = 500

X = np.zeros((batch_size, window_size, 1))

Y_pred = model.fn(X)
```

# Versions

Python 3.10
TF 2.14.0rc1
keras-core 0.1.7

**Comment by grasskin** [comment]
Thank you for your report, as a temporary workaround you could save your model as a .keras model and then reload it on your cpu. You can then export this using saved model.

Could you take a look @qlzh727, thank you!

**Comment by qlzh727** [comment]
@sampathweb

**Comment by qlzh727** [comment]
Sorry for the very late reply.  I think this issue is caused by RNN implemention in TF backend, which is bit different from the existing tf-keras. We should port the existing tf keras implementation to the new keras, which will solving this issue. 

There are multiple issue related to this root cause, and I think @sampathweb will try to fix that when he have more cycle.,

**Comment by qlzh727** [comment]
As the current walkaround (as @grasskin suggested), you can save your model and load back on CPU devices, which then will be able to export as proper saved model.

**Comment by fchollet** [comment]
Revisiting this: the issue here is that TF `SavedModel` is a low-level format that includes device-related information (in this case, kernels that are only registered for GPU). As such it cannot move across devices in the general case (though in practice the LSTM and GRU layers are the only ones that will show this issue).

Legacy tf.keras was going out of its way to pave over this limitation, but this is no longer a good idea in the multi-backend setting. As such I recommend the workaround mentioned in this issue: just save your model as a `.keras` file (which can move across devices), reload it on CPU, and export it to `SavedModel` there.
