### ISSUE TITLE
Use of  tf.keras.backend.ctc_batch_cost

### ISSUE THREAD

**Issue by emi-dm** [keras-team/keras#18575]
Hi guys!! Is possible to use  keras.backend.ctc_batch_cost in new Keras?

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

Could you please try the below imports and let us know if helps.

```
import keras_core as keras
from keras.src.backend import ctc_batch_cost
```

**Comment by emi-research-dl** [comment]
Hi @SuryanarayanaY !! I couldn't import the package. When I've executed it, it threw me this error:

`ImportError: cannot import name 'ctc_batch_cost' from 'keras_core.src.backend' `

I don't know if you referred to Keras instead of Keras Core in the import.

Thanks in advanced!

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

I have installed `keras_core` and imported it as `keras`. It is success in colab. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/e44f2f354e223d541c6afe41adaf9d6c/18572.ipynb).

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

I have tested the same tutorial with the suggested change above. In colab import `from keras.src.backend import ctc_batch_cost` is success but I got a new error at the line `model = keras.models.Model()`, which we need to look into.

Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/64be1b5cd3354a1764f31624d76d76ab/18575_captcha_ocr.ipynb) here with the environment details. 

I suggest you to check the environment details or try to install a fresh environment . For local installation please refer the instructions [here](https://github.com/keras-team/keras#local-installation).

Meanwhile we will  have a look into the root cause of the error raised here.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

It seems in Colab when I use `from keras.src.backend import ctc_batch_cost` its actually installing from pre-imported keras version i.e keras 2.13v.

If I uninstall keras explicitly and then installed keras_core then `from keras_core.src.backend import ctc_batch_cost` its not working. Sorry for the confusion created because of this.

**Comment by emi-research-dl** [comment]
Yeah! @fchollet Will all the functions of the old Keras backend be moved to Keras 3.0?

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

It seems this API is deprecated in Kears3 version. I don't think it will be moved back into kears3 for now.

https://github.com/keras-team/keras/blob/63dc12d51565d0077eb2239f6219d4b51e117853/keras/legacy/backend.py#L652-L654

**Comment by foxik** [comment]
Hi all, in two-weeks-old Keras 3.0.2, a backend-agnostic CTC loss was added as `keras.losses.CTC` (with `keras.ops.ctc_loss` low-level ops), see the release notes https://github.com/keras-team/keras/releases/tag/v3.0.2.

**Comment by SuryanarayanaY** [comment]
Hi @foxik ,

As mentioned in above comment you can find `keras.backend.ctc_batch_cost` implemneted as `keras.ops.ctc_loss` 

https://github.com/keras-team/keras/blob/a762b418bfc162d16b92670d938d53c28ad2766c/keras/ops/nn.py#L1820
