### ISSUE TITLE
[Tensorflow] Multi-GPU training error: Unrecognized data type: x=<tensorflow.python.distribute.input_lib.DistributedDataset

### ISSUE THREAD

**Issue by crohkohl** [keras-team/keras#18621]
Running a distributed training with the `tf.distribute.MirroredStrategy` leads to the following error:

```
Unrecognized data type: x=<tensorflow.python.distribute.input_lib.DistributedDataset object at 0x7fdf4e4b6200> (of type <class 'tensorflow.python.distribute.input_lib.DistributedDataset'>)
  File "/usr/local/lib/python3.10/dist-packages/keras_core/src/trainers/epoch_iterator.py", line 145, in __init__
    raise ValueError(
  File "/usr/local/lib/python3.10/dist-packages/keras_core/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/qpsw.python/src/qpsw/dl/recipes/base.py", line 630, in _train_imp
    model.fit(self.ds_train, steps_per_epoch=self.num_steps_per_epoch,
```

The versions are as follows:
```
>>> tf.__version__
'2.14.0'
>>> keras_core.__version__
'0.1.7'
```

Single GPU training is working fine.

It seems also the examples here are not fully correct:

https://keras.io/guides/distributed_training/

They do not use the dataset distribution for multi gpu training suggested here:

https://www.tensorflow.org/api_docs/python/tf/distribute/DistributedDataset

**Comment by fchollet** [comment]
Thanks for the report.

Note that you do not need to distribute the dataset yourself, because we do it for you when you use a `tf.distribute` strategy.

We can allow you to pass a `DistributedDataset`, however. There are only a few minor issues with the process. It seems that `DistributedDataset` does not pass the check `isinstance(dataset, tf.data.Dataset)`, which is rather unfortunate. In addition, it seems that `DistributedDataset` does not correctly implement the `tf.data.Dataset` API. For instance, its `cardinality` method is not a method but a property.

I have pushed a change to make it possible to pass a `DistributedDataset`, you can check it out at HEAD.

**Comment by crohkohl** [comment]
Thanks. I did not notice converting the old code base! This part works now as intended using both variants.
