### ISSUE TITLE
Manual Installation Keras

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras#18652]
Hi, when installing Keras manually (GitHub) it does not install correctly and I think it is mixed with the previous version of Keras (inside TF, tf.keras).

The steps I followed are:

1. Clone the repository
2. Create an environment named keras-torch (python 3.9)
3. pip install -r requirements.txt
4. python3 pip_build.py --install
5. Set variable KERAS_BACKEND=torch
6. Deactivate environment, activate it and import Keras

It seems that Keras does not contain TorchModuleWrapper and does not recognize the environment variable.

![image](https://github.com/keras-team/keras/assets/140513018/fa235ff1-11dd-4df9-be82-e119a87c2e49)

**Comment by sampathweb** [comment]
We now have `keras-nightly`, so you don't have to clone the repo to install it.  
To get the latest `keras` install - `pip install -U keras-nightly`

please note that Keras doesn't automatically install all its dependencies since there could be varying local env (CPU, GPU..).  So install the dependencies in the requirements **first**, then install `keras-nightly`.  Otherwise `tf-nightly` or `tensorflow` might overwrite the `keras`.  This problem will go away from next week when `tf-nightly` also will get the latest `keras-nightly`.

**Comment by sampathweb** [comment]
for setting backend, use `export KERAS_BACKEND=torch`.  If that doesn't work, please re-open the issue.  To keep it for all your experiments, save this export in `~/.bash_profile` or `~/.bashrc` depending on your local setup.

**Comment by emi-research-dl** [comment]
Hello @sampathweb , the problem still persists after following your steps!

![image](https://github.com/keras-team/keras/assets/140513018/2e7fcde8-745f-4407-8809-4760aa7c9ab7)
