### ISSUE TITLE
Many-to-many spatio-temporal sequence prediction 

### ISSUE THREAD

**Issue by Renat2001** [keras-team/keras#18758]
Is there any implementation of applying **Convolutional LSTMs** for **spatio-temporal forecasting** problem. As input I have sequences of images - each sequence consists of 4 frames. I want to create a model that predicts next 16 frames for given 4 ones. Please, do not consider https://keras.io/examples/vision/conv_lstm/ as this article is about predicting same amount of frames when in my case is **different timesteps** prediction.

**Comment by grasskin** [comment]
Hi @Renat2001, I don't think we have any implementations of what you mention but you should be able to modify the example for general convolutional LSTM's. There are a couple ways to do it. The standard solution is to train the model to predict the next frame from the four previous frames. If you then need 16 frames call your model 16 times. Otherwise if you only care about 4 frames as input and 16 frames output you could do something like this:

- The example dataset used is https://www.cs.toronto.edu/~nitish/unsupervised_video/ which "contains 10,000 sequences each of length 20 showing 2 digits moving in a 64 x 64 frame." The dataset you need should grab the first 4 frames as training data (x) and the last 16 as target (y). Consider using https://keras.io/api/data_loading/timeseries or modifying the `create_shifted_frames` function. Something like
```python
def create_data_frames(data):
    x = data[:, 0 : 4, :, :]
    y = data[:, 4 : , :, :]
    return x, y
```
- Modify the model to return 16 frames. The last `ConvLSTM2D` layer returns shape (None, None, 64, 64, 64) if you do `model.summary()`. In practice, our shape will be `(batch_size, 4, 64, 64, 64)`. Note the 4 because we are passing 4 frames each time. We need our output to be `(batch_size, 16, 64, 64, 1)`. 16 output frames and only 1 channel (black and white images). One possible solution is to add up the output along the time dimension, modify the final `Conv3D` layer to return 16 timesteps, and then reshape to the right output. Something like:
```python
x = keras.ops.sum(x, axis=1, keepdims=True)
#  Or in Keras2:
#  tf.math.reduce_sum(x, axis=1, keepdims=True)
x = layers.Conv3D(
    filters=16, kernel_size=(3, 3, 3), activation="sigmoid", padding="same",
)(x)
x = layers.Reshape((16, 64, 64, 1))(x)
```

This would apply to the example dataset but you can modify it for your usecase.
