### ISSUE TITLE
input_shape and output_shape of the InputLayer return a tuple wrapped in a list, a opposed to just a tuple like in other layers.

### ISSUE THREAD

**Issue by norbertnica** [keras-team/keras#18784]
Is this an intended behaviour and, if yes, why?

I've seen it breaking a custom keras-based package where layers were fused post-training based on shapes.

**Comment by norbertnica** [comment]
```
import tensorflow as tf

x = tf.keras.Input((128,128,3))
c = tf.keras.layers.Conv2D(64, kernel_size=1)

m = tf.keras.Model(inputs=x, outputs=c(x))
for layer in m.layers:
	print(layer.input_shape)
	print(layer.output_shape)
```

Output of the print statement

> [(None, 128, 128, 3)]
[(None, 128, 128, 3)]
(None, 128, 128, 3)
(None, 128, 128, 64)

**Comment by SuryanarayanaY** [comment]
Hi @norbertnica ,

In Keras3, the layer don't have attributes `input_shape` or `output_shape`. Please refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f86d7c2406cb4533e1c1515f72b2e80b/18784.ipynb).



> I've seen it breaking a custom keras-based package where layers were fused post-training based on shapes.

Could you provide more context on this since if it fails with tf.keras it will fail with keras3 also.

**Comment by norbertnica** [comment]
Sorry, should've posted in keras 2 tf-keras legacy repo, got confused by the migration.
