### ISSUE TITLE
Enhance tf.keras.utils.to_categorical with Advanced Preprocessing

### ISSUE THREAD

**Issue by GDMarkou** [keras-team/keras#18964]
## Issue Description
Request for enhancement of the `tf.keras.utils.to_categorical` method in TensorFlow Keras to include additional functionalities for advanced data preprocessing.

### 1. Preprocessing of Diverse Data Types
- Extend support to preprocess strings, lists of integers with gaps, and negative integers.

### 2. Combining Infrequent Classes
- Enable class combination based on criteria such as minimum absolute frequency, minimum relative frequency, and a maximum number of categories.

### 3. Custom Schemas for Class Combination
- Introduce functionality for users to define custom schemas for class combination.

### 4. Class Dropping Feature
- Implement the option to exclude specific classes during preprocessing.

### 5. PCA on One-Hot Encoded Matrix
- Facilitate PCA implementation directly on the one-hot encoded matrix for feature reduction.

## Motivation
The enhancements aim to expand the utility of `to_categorical` for handling complex data types and enable advanced data manipulation directly within TensorFlow Keras, catering to diverse machine learning applications.

## Contribution and Collaboration
My team and I have implemented some of these features as part of an assignment in our master's program. We are interested in contributing our work to the TensorFlow community. Below, we provide you with the .ipynb file which contains our suggestions and improvements on the `to_categorical` function.

[Improved_TC.zip](https://github.com/keras-team/keras/files/13714016/Improved_TC.zip)

**Comment by SuryanarayanaY** [comment]
Hi @GDMarkou ,

If you have implemented some features please feel free to contribute with pull request. Team will happily review it. Please check [CONTRIBUTING.md](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for more details on contribution guidelines.

Thanks!

**Comment by mattdangerw** [comment]
Thanks for filing!

I think for `to_categorical`, we would like to keep this a simple function that just takes indices and categorically encodes them. If you take a look at our preprocessing layers, https://keras.io/api/layers/preprocessing_layers/, we have a number of offerings for feature preprocessing, but we would shoot for a organized set of `Layer`s rather than a util with a bunch of options.

I think `StringLookup` and `IntergerLookup` would meet some of the features requested below. As for dropping classes entirely, or just infrequence ones, that is probably best done as custom preprocessing code per model, as that would be hard to generalize.

Things like `PCA` are a bit out of scope for Keras, though `sklearn` will have great features here.
