### ISSUE TITLE
Question about Tensorflow compatibility 

### ISSUE THREAD

**Issue by chenmoneygithub** [keras-team/keras#18996]
Hi team! 

I have a few questions about the Tensorflow compatibility, could you help clarify? 

1. In future Tensorflow versions (I assume it's starting from 2.16), will TF depend on Keras 3 instead of tf-keras? 
2. If 1 is correct, does it mean tf-keras will be a frozen package?
3. Will `from tensorflow import keras` or `tf.keras` keep working? This is not the best practice, but MLflow (the package I am maintaining now) needs to keep the backward compatibility, so `from tensorflow import keras` will be the simplest solution. 

Thanks for the help! 

Best,
Chen Money

**Comment by sushreebarsa** [comment]
@chenmoneygithub Starting from TensorFlow 2.16, TF will indeed depend on Keras 3 instead of tf-keras. This marks a significant shift in the relationship between the two libraries.  tf-keras will likely become a frozen package in the future. This means it will stop receiving active development and remain primarily for backward compatibility with older codebases.  Use of `from tensorflow import keras `appears to be a practical approach for maintaining backward compatibility within MLflow but for long-term use it won't be recommended as tf-keras becomes further deprecated, relying solely on it may limit future flexibility and access to newer Keras features.
Thank you!

**Comment by haohuanw** [comment]
from my experiences (i am porting over my models to keras 3)

1. tf works as is, i think the minimum required tf version is ~2.12
2. tf.keras and keras cannot be imported at the same time (meaning that your code should either do all `tf.keras` or all `keras.`)
3. you can still mix tf code in keras3 (eg. calling `tf.boolean_mask` or some other ops). only `tf.keras` need to be changed

**Comment by sampathweb** [comment]
@chenmoneygithub - Thanks for raising this issue.

1. Starting in TF 2.16, Keras 3 will be installed with TensorFlow.  But TF will also remain compatible with `tf-keras` and users can switch via env. variable `TF_USE_LEGACY_KERAS=1` and installing `tf-keras` pip package.

> does it mean tf-keras will be a frozen package?
2. We will continue to release a `tf-keras` version that's aligned with TensorFlow version for users wanting to use Keras 2.

3. `from tensorflow import keras` will use Keras 3 from TF 2.16 unless the env variable is set, which will then import `tf_keras` package (keras 2).

**Comment by chenmoneygithub** [comment]
@sampathweb Thanks for the clarification!

**Comment by SuryanarayanaY** [comment]
Hi @chenmoneygithub ,

Could you please confirm whether we can mark it as resolved ?

**Comment by SuryanarayanaY** [comment]
Hi @chenmoneygithub ,

This is already documented [here](https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility). Could you please check and confirm if still missing any info there. Thanks!
