### ISSUE TITLE
Is possible use and serialize torch loss function 

### ISSUE THREAD

**Issue by emi-dm** [keras-team/keras#19084]
Hey guys, is it possible to use and serialize the torch loss function with Keras?

For example, Train a Keras model with a custom torch loss function and save/load it. 

I want to use Keras with Monai loss functions and save the models. I will use Trainer Pattern for this, so only the order of logits and preds change when passing it to the compute_loss method.

Thanks in advance!

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

I hope this was discussed here at #[18686](https://github.com/keras-team/keras/issues/18686). Are we still missing anything there ?

**Comment by emi-research-dl** [comment]
@SuryanarayanaY  Do you know if a detailed example like the question exists? I think it would be interesting to learn more about the integration of torch loss functions with Keras

**Comment by innat** [comment]
For layer (nn.) 
https://keras.io/api/layers/backend_specific_layers/torch_module_wrapper/

**Comment by SuryanarayanaY** [comment]
Hi @emi-dm ,

You may use custom training loop for training,saving and reloading the model with Keras3 as mentioned in above issue.

But if you are looking to pass a torch loss function directly to model.compile and then using model.fit() for training you will get `TypeError` like below.



> TypeError: Cannot serialize object CrossEntropyLoss() of type <class 'torch.nn.modules.loss.CrossEntropyLoss'>. 
> To be serializable, a class must implement the `get_config()` method.



Teste a model with torch loss function passed to model.fit(), attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/96f90deb13729232afbb6e9ae0c6dec3/19090_custom_optimzer-loss-_in_torch.ipynb) for same.

This is because Keras3 expects all custom classes implements `get_config()` method, which may not be case with torch classes.

Escalating to dev team for their comments. Thanks!

**Comment by fchollet** [comment]
> This is because Keras3 expects all custom classes implements get_config() method, which may not be case with torch classes.

Native torch objects are not going to be serializable by Keras by default since they lack `from_config()` and `get_config()`.

The solution is to wrap them in a class that has these methods. `TorchModuleWrapper` does this for Modules. For loss functions, you can simply create your own `keras.losses.Loss` subclass with a `get_config()` method, that calls the torch loss in its `__call__` method. How does that sound?

**Comment by emi-dm** [comment]
Sounds great @fchollet, thank you very much. It would be great if this sort of thing could be included in a small part of your new book
