### ISSUE TITLE
How to save/load GraphSAGE model with keras ?

### ISSUE THREAD

**Issue by HripsimeS** [keras-team/keras#19082]
Hello @sachinprasadhs @SuryanarayanaY 

Please find the python script below. To run the part 1, it seems the model in baseline is missing (the name "model" is not defined).
https://github.com/Yaxin-Cui/Graph-Neural-Network/blob/main/code/graphstellar_updated.py

To try fix this issue, I tried to save the trained model in the part 0 with two options to see which one works efficient. 
**model.save("model.keras")**  or **model = keras.models.load_model("model.h5")**

And after loading the model in part 1 with these lines:
**model = keras.models.load_model("model.keras")** or model = **keras.models.load_model("model.h5")**

In case of **h5** format I received the following error 
![error-H5](https://github.com/keras-team/keras/assets/42246765/105e91b9-2969-42a3-9c72-2a3432f3c2c6)

And in case of **keras** format I received the following error 
![error-keras](https://github.com/keras-team/keras/assets/42246765/5fb8c50e-897b-496b-af13-dc0f25c5d2eb)

Can you please help to see how to fix the issues or maybe if there is other way to save this model, which one can be the best.

**Comment by SuryanarayanaY** [comment]
Hi @HripsimeS ,

We won't debug the code from third party libraries.Please submit minimal code snippet  in the form of colab gist to reproduce the issue without third party library dependencies. 

However I can provide some pointers here.

Keras3 supports only `.keras` saving format. From the error log this might be due to the presence of custom objects in the model that are not explicitly serialized/deserialized by overriding the `get_config()` and `from_config()` methods. You need to check this [tutorial](https://keras.io/guides/serialization_and_saving/#custom-objects) for more details on custom objects.

Alternatively you may try installing [tf-keras](https://github.com/keras-team/tf-keras) package and set environment variable `os.environ["TF_USE_LEGACY_KERAS']="1"`.
