### ISSUE TITLE
The master branch commit doesn't update in Codecov

### ISSUE THREAD

**Issue by james77777778** [keras-team/keras#19264]
Please refer to: https://app.codecov.io/gh/keras-team/keras/commits

Due to this issue, the codecov report is noisy.

**Comment by haifeng-jin** [comment]
It is because the dependent bot updated the codecov GitHub action version from v3 to v4.
https://github.com/keras-team/keras/pull/19129/files#diff-2702f6f7d10a1bffbc8596d1a9925b1234bc4c7a6ff4c21ca6b34c13aa75780eL83-R83

V4 stopped supporting tokenless upload.
I will figure out if adding back the token would fix it.

**Comment by james77777778** [comment]
> It is because the dependent bot updated the codecov GitHub action version from v3 to v4. https://github.com/keras-team/keras/pull/19129/files#diff-2702f6f7d10a1bffbc8596d1a9925b1234bc4c7a6ff4c21ca6b34c13aa75780eL83-R83
> 
> V4 stopped supporting tokenless upload. I will figure out if adding back the token would fix it.

After #19312 , the new commits are still missing from https://app.codecov.io/gh/keras-team/keras/commits
Consequently, the codecov report remains noisy...
Ex: https://app.codecov.io/gh/keras-team/keras/pull/19313 (a report of the PR after the fix)

**Comment by haifeng-jin** [comment]
We do not have a good fix yet. Probably, I should just downgrade it to v3.

**Comment by adamjstewart** [comment]
FYI, [TorchGeo](https://github.com/microsoft/torchgeo) has also been fighting against codecov for a while now. `codecov-action@v3` only works a fraction of the time, and `codecov-action@v4` doesn't work at all due to the token requirements. There are dozens of issues related to this, but https://github.com/codecov/feedback/issues/126 has the most detailed discussion. We're at the point where we're considering abandoning codecov entirely, but if the Keras team finds a better solution let me know.
