### ISSUE TITLE
Categorize Code Examples by Backend

### ISSUE THREAD

**Issue by emi-dm** [keras-team/keras#19265]
Hi!!! I want to ask if it would be possible to categorize the code examples by backend in the documentation. It would be great to search for torch or jax specific examples simply by backend.  

Likewise, I would like to ask what is the purpose of the "keras.config.set_image_data_format('channels_first')" method.

Thank you very much!

**Comment by sachinprasadhs** [comment]
@innat , Thanks for your input.

@emi-dm , Regarding categorizing code examples according to the backend is not we are aiming for.
We are basically working towards making all the examples listed to work on all the backends we support.
Majority of the examples we migrated to Keras 3 works well on all the backends.

Only limited set of examples due to the dependency on TensorFlow is restricted to tensorflow backend, which will be made available for all the backends once the specific dependency is resolved in future.

All the V3 examples which does not have env set for any specific backend like below should work fine for all backends(PyTorch,, TensorFlow, JAX).
`os.environ["KERAS_BACKEND"] = "tensorflow"`
