### ISSUE TITLE
Model graph traversal with Keras 3?

### ISSUE THREAD

**Issue by rachthree** [keras-team/keras#19278]
Hello, Keras 3 looks really cool! I have a utility that traverses a TF Keras model graph with `keras < 3`, using `model.inputs[i].node`. From there it uses `node.outbound_layer.outbound_nodes`. It appears that `keras.src.engine` and its `Node` has been removed in Keras 3, and so a `KerasTensor` no longer has a `node` attribute. Is there an equivalent way to traverse a model graph in Keras 3, or must I use `tf-keras`?

Thanks!

**Comment by mattdangerw** [comment]
@rachthree thanks for the issue!

I think because you are relying on private functionality to Keras, some changes are expected here from 2->3, but this should still be doable. Here's the code for functional walking through the graph. https://github.com/keras-team/keras/blob/master/keras/ops/function.py#L124-L161 shows walking the graph for call, and there is a lot of other functionality in this file `map_graph`, that shows how to build a graph of nodes.

`keras_tensor._keras_history[0].inbound_nodes` might get you at nodes.

In general, I don't think this sort of walking the graph in this way will be stable, as there is a lot of private details here we might change in the future.

**Comment by rachthree** [comment]
Thank you so much for your response, @mattdangerw ! I'll see what I can use from the code you linked, but I understand that implementation and behavior could change in the future.

Noting here in case anyone else is looking for something similar: As an alternative, I tried installing `tf-keras` then used `TF_USE_LEGACY_KERAS=1` [as suggested by these TF release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1) to restore previous Keras behavior. Not ideal since using already-available utilities like the [one linked above](https://github.com/keras-team/keras/issues/19278#issuecomment-2005103169) is preferable, but it does work.
