### ISSUE TITLE
Keras 3 + TF 2.16 Incorrect model with TextVectorization in SavedModel format contains float input type instead of string type

### ISSUE THREAD

**Issue by rkazants** [keras-team/keras#19396]
### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, TextVectorization
from tensorflow.keras.models import Model

vocabulary = ['hello', 'there', 'random', 'vocab', 'check']
length = 64

text_input = Input(dtype=tf.string, shape=(1,), name='text_input')
vectorize_layer = TextVectorization(vocabulary=vocabulary, output_mode='int', name='vectorization_layer',
                                    output_sequence_length=length)(text_input)
model = Model(inputs={'text_input': text_input}, outputs=[vectorize_layer])

input_data = np.array([['hello here and there']], dtype=str)
model({'text_input': input_data})

tf.saved_model.save(model, 'my_model')
loaded_model = tf.keras.layers.TFSMLayer('my_model', call_endpoint="serving_default")
loaded_model(input_data)
```

### Relevant log output

```shell
ValueError: could not convert string to float: 'hello here and there'
```

Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/bcface2dd3959545e755c62f2ee439ce/untitled1786.ipynb).
Originally, I reported this bug in TF issue https://github.com/tensorflow/tensorflow/issues/64443. According to TF team investigation, this looks Keras issue. Please take a look.

Best regards,
Roman

**Comment by SuryanarayanaY** [comment]
Hi @rkazants ,

Thanks for reporting. I have tested the code snippet with `Keras3` and it indeed raising the `error` as reported by you. Same works fine with `Keras2` APIs. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/8ab8c423576538ba42ae0f04e7f792db/19396.ipynb) for reference. Needs investigation.

**Comment by fchollet** [comment]
There are two issues here:

1. `tf.saved_model.save()` does not preserve the input dtype of a Keras model. That's ok though, you can work around it by using `model.export()`, which is the preferred solution. Like this:

```python
model.export('my_model')
```

3. When reloading the `TSMLayer`, you need to provide a dtype, otherwise the default dtype float32 is used. Like this:

```python
loaded_model = tf.keras.layers.TFSMLayer('my_model', call_endpoint="serving_default", dtype="string")
```

With these 2 changes, your model can be saved and reloaded correctly.

If you want the first issue to get fixed, you could file an issue with the TF repo. We have no control over what `tf.saved_model.save()` does.
