### ISSUE TITLE
optimizers.Adam no longer accepts tf.Variable

### ISSUE THREAD

**Issue by RocketRider** [keras-team/keras#19760]
When trying to call Adam with a tf.Variable I get the following error:

```
  File "site-packages\ray\rllib\algorithms\impala\impala_tf_policy.py", line 230, in optimizer
    optim = tf.keras.optimizers.Adam(self.cur_lr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages\keras\src\optimizers\adam.py", line 62, in __init__
    super().__init__(
  File "site-packages\keras\src\backend\tensorflow\optimizer.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "site-packages\keras\src\optimizers\base_optimizer.py", line 124, in __init__
    raise ValueError(
ValueError: Argument `learning_rate` should be float, or an instance of LearningRateSchedule, or a callable (that takes in the current iteration value and returns the corresponding learning rate value). Received instead: learning_rate=<tf.Variable 'lr:0' shape=() dtype=float32, numpy=0.0005>
```
Tested with Keras 3.3.3.

The issue was first reported here: https://github.com/ray-project/ray/issues/45050

**Comment by fchollet** [comment]
This is normal. You could simply cast the TF Variable to a float.

Passing the TF Variable directly might give you the impression that updates to the TF Variable would be reflected on the learning rate, which isn't the case. In order to dynamically update the learning rate, you should use a `LearningRateSchedule` or a Callback that sets the learning rate.
