### ISSUE TITLE
Autocompletion/hints fail for keras.Variables 

### ISSUE THREAD

**Issue by mahnehsilla** [keras-team/keras#19846]
There isn't any methods listed when one does:

```python
v = keras.Variable(keras.random.normal((1,2,3))
v.<Tab>
```

But if I open the python runtime some methods appear: `assign`, etc.

Should there be auto completion on these methods?

**Comment by mehtamansi29** [comment]
Hi @mahnehsilla - 

There is auto complete methods are there for the keras.Variables. Here is the [gist](https://colab.sandbox.google.com/gist/mehtamansi29/84746eb9489c8b8772b44b416172812a/19846-autocompletion-hints-fail-for-keras-variables.ipynb) attached for the reference.
In colab if you just type "v." and wait a sec and colab is showing all the method related to keras.Variables.

**Comment by mahnehsilla** [comment]
it seems keras nightly does not have Variable anymore? i was testing but can't confirm.

**Comment by mahnehsilla** [comment]
That's quite crazy, but if instead of
`from keras import Variable`

I do

`from keras.src.backend import Variable`

it does show all the hints!

Do you know why @fchollet ?

**Comment by harshaljanjani** [comment]
Hello @ghsanti,
Since the docstrings already provide sufficient information to infer the types, I don't believe any of the layers have type annotations yet. Having said that, adding explicit type hints could be nice and improve the developer experience.
Would it be possible for the collaborators to kindly look into whether this is under consideration? @mehtamansi29
