### ISSUE TITLE
Are `ops.shape` vs `KerasTensor.shape` equivalent for most purposes?

### ISSUE THREAD

**Issue by aka-santi** [keras-team/keras#19880]
In this [example from the docs](https://keras.io/examples/generative/vae/), you use the code:

```python
        batch = ops.shape(z_mean)[0]
        dim = ops.shape(z_mean)[1]
```
i.e `ops.shape` to get the tensor shape.

I find `z_mean.shape[0]` more readable, and the python runtime seems to show the same tuple output:

```
>>> keras.ops.shape(a)
(1, 2, 3)
>>> a.shape
(1, 2, 3)
```

Are these methods fully equivalent? Is there any reason to prefer `ops.shape(keras_tensor)` over `keras_tensor.shape` ?

**Comment by fchollet** [comment]
In general, you should always use `ops.shape` to ensure cross-backend compatibility.

The return of `x.shape` depends on the type of `x`:

| Type of x    | `x.shape` |
| ----------- | ------- |
| `KerasTensor`  | tuple of `int` or `None`   |
| `torch.tensor` | `torch.size` (which is a wrapper around a tuple of `int`) |
| `jax.array`    | tuple of `int`   |
| `tf.tensor`    | `TensorShape` (which is a wrapper around a tuple of `int`  or `None`) |

Meanwhile `ops.shape` always returns a tuple of `int`. With two exceptions:
- In the case of the TensorFlow backend, when the shape is dynamic, some entries may be `tf.int` scalars instead of Python ints.
- In the case of a `KerasTensor`, when the shape is dynamic, some entries may be `None`.

**Comment by aka-santi** [comment]
Thank you @fchollet, if you don't mind a minor request:

* It'd be great to have some guide / document on best practices for multi-backend support.
* It'd be great to add the `copy code` button to all examples in the docs (using Clipboard API form the browser, I think.)

**Comment by mehtamansi29** [comment]
Hi @aka-santi-

Here you can find more description and example regarding [backend-specific-layers](https://keras.io/api/layers/backend_specific_layers/).
