### ISSUE TITLE
[Help] Where is the trace/history of operations that led to a KerasTensor stored?

### ISSUE THREAD

**Issue by aka-santi** [keras-team/keras#19881]
Hi, learning Keras 3 here.

PS: actually I think I found it, any extra tricks are welcome otherwise close it. 

I am assuming that the outputs of a `Model` instance, i.e `myModel.outputs` can then be passed onto more layers (as if we hadn't instantiated it in the first place), and returned from a new `Model`, and this wires them together.

```python
>>> a.__getstate__()
{'shape': (None, 1, 2, 4), 'dtype': 'float32', 'sparse': False, 'name': 'keras_tensor_2', 'record_history': True, '_keras_history': KerasHistory(operation=<Dense name=dense_1, built=True>, node_index=0, tensor_index=0)}
>>> a._keras_history
KerasHistory(operation=<Dense name=dense_1, built=True>, node_index=0, tensor_index=0)
```

----

I assume that Keras keeps track of the operations applied from the input to the output, this is clear in functional models at least where one wires up the network. (see code below.) 

This "history" of operations for a Keras tensor must somehow be all located in the output Keras tensor, but I do not see any attributes for inspecting this?

```python
import keras
a = keras.layers.Input((1,2,3))
a = keras.layers.Dense(4)(a)
```

There isn't any method within `a` that allows inspection of the "history of operations up to a"

How do you do this, and is it documented anywhere?

**Comment by miticollo** [comment]
I asked to me a similar question. And to find the answer you must read the source code. So let's go to examine the last stable Keras version (at the moment of writing 3.3.3).

If you use the [Functional API](https://keras.io/guides/functional_api/) your model is `Functional`. A `Functional` model [is a](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/models/functional.py#L26) `Function`.

## What is a Keras `Function`?

Well, [this comment](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/node.py#L11-L14) is a good definition of it.

## How does `Functional` model trace `Nodes` and `Operation`?

During `Functional` model construction its `__init__()` method [calls](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/models/functional.py#L162) `Function` constructor. The latter [calls](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/function.py#L77-L79) [`map_graph()`](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/function.py#L201-L319).
Under the hood this method uses [`_keras_history`](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/node.py#L116-L135)&mdash;a `KerasTensor` attribute&mdash;to work.

This should **answer your question** you can explore [these _private_ fields](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/function.py#L80-L83).

## But why `Operation`? I only used `keras.Layers`!

A `Layer` [is an](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/layers/layer.py#L60) `Operation` but vice versa is not true. When you write `keras.layers.Dense()` you implicitly invokes a `__call__()`. This method [comes from](https://github.com/keras-team/keras/blob/f6c4ac55692c132cd16211f4877fac6dbeead749/keras/src/layers/layer.py#L724-L887) `keras.Layer`. In particular, it [calls](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/layers/layer.py#L842-L846) [`Operation.__call__()`](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/operation.py#L31-L56). During DAG construction you don't pass data so every layer returns a symbolic tensor ([`KerasTensor`](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/backend/common/keras_tensor.py#L8-L12)). Then the last `__call__()` method [invokes](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/operation.py#L52) [`symbolic_call`](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/operation.py#L58-L70) that create a new [`Node`](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/node.py#L8).

## What happens during forward propagation?

Well, the `__call__()` from `Operation` class is always invokes. But this time the `call()` method (without underscores) [is invoked](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/ops/operation.py#L56). For example look [the `call` method](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/layers/core/dense.py#L149-L155) from `Dense` layer.
Interesting! A `call()` method invokes other `keras.ops`. So you can see a `Layer` as _atomic_ `keras.ops`.

Even if this issue is closed I hope that it can answer your question.

**Comment by aka-santi** [comment]
@miticollo i didn't quite follow all that detail, as i just started with keras, but thank you, i hope to understand it soon.
