### ISSUE TITLE
Support for channels first data format with zeropadding1D

### ISSUE THREAD

**Issue by ROZBEH** [keras-team/keras#19984]
Hi Keras team,

It appears that the 1D ZeroPadding layer always assumes a channels-last data format. It would be beneficial to add support for cases where the data format is channels-first. Currently, the 1D ZeroPadding layer does not accept an input variable for data_format, unlike the ZeroPadding2D layer which includes this parameter.

https://github.com/keras-team/keras/blob/v3.3.3/keras/src/layers/reshaping/zero_padding1d.py

Thank you.

**Comment by grasskin** [comment]
Hi @ROZBEH, thank you for opening this issue. This could be a good standardization effort for our ZeroPadding layers, it does seem that our `ZeroPadding2D` and `ZeroPadding3D` have a `data_format` parameter that `ZeroPadding1D` doesn't. In general, we only have `data_format` parameters for reshaping layers that work on more than 1 dimension, likely from convention.

Is this something you have run into/you have a use case for? Have you had 1D data with `features` or `channels` as the second dimension instead of the third?

**Comment by ROZBEH** [comment]
Hi @grasskin , thanks for getting back to me.

Yes, this is something I ran into while working on a usecase like below. As you can see, Zeropadding1D, as it is today, pads the channels dimension when the data_format is channels_first but we would like to pad the feature dimension

```
x_in = tf.keras.layers.Input(shape=shape)
if data_format == "channels_last":
        x = tf.keras.layers.ZeroPadding1D(
            padding=2,
        )(x_in)
    else:
        # tensorflows zeropadding1d doesn't support channels first
        x = tf.pad(x_in, paddings=[[0, 0], [0, 0], [2, 2]])

x = tf.keras.layers.SeparableConv1D(
        filters=filters,
        kernel_size=kernel_size,
        strides=1,
        padding="valid",
        activation="relu",
        **separable_conv_params,
    )(x)
model = tf.keras.Model(x_in, x)
```

Thank you.
