### ISSUE TITLE
Reduce_sum and reduce_mean layers for Keras 3

### ISSUE THREAD

**Issue by fburgaud** [keras-team/keras#20085]
Good morning,
Tensorflow recently moved to Keras 3. Before 2.16 (I believe), it was on Keras 2, and was allowing steps like tf.reduce_sum in the composition of a model.
Now, everything has to be a Layer of custom Layer.
So, I do get that there are some alternatives, such as using a custom Layer or a Lambda, but reduce_sum/reduce_mean are useful functions (e.g. getting the average of a bunch of embeddings), and custom Layer or Lambda have their own limitations which make things a lot less frictionless (e.g. serializing/deserializing).
Would be nice to have real layers for those?

**Comment by ghsanti** [comment]
There are equivalents in Numpy. [See here.](https://keras.io/guides/migrating_to_keras_3/#numpy-ops)

**Comment by sachinprasadhs** [comment]
@ghsanti , Thanks for pointing it out.

@fburgaud , With the multi backend support in Keras 3, in order to follow similar naming convention and implementation among Numpy, PyTorch, Jax and TensorFlow it has been named as [ops.mean](https://keras.io/api/ops/numpy/#mean-function) and [ops.sum](https://keras.io/api/ops/numpy/#sum-function)
