### ISSUE TITLE
Floating point exception (core dumped) with onednn opt on tensorflow backend

### ISSUE THREAD

**Issue by Shuo-Sun20** [keras-team/keras#20335]
As shown in this [colab](https://colab.research.google.com/drive/1XjoAtDP4SC2qyLWslW8qWzqQusn9eDOu?usp=sharing), the kernel, not the program, crashes if the OneDNN OPT is on and the output tensor shape contains a zero dimension.

As discussed in tensorflow/tensorflow#77131, and also shown in the above colab, we found that the error disapeared after downgrading from keras 3.0 to keras 2.0.

Therefore, I think some errors are introduced when updating from keras 2.0 to keras 3.0.

**Comment by mehtamansi29** [comment]
Hi @Shuo-Sun20 -

Thanks for reporting the issue. But this issue because of  floating-point round-off approaches to different numerical result when trying to enable oneDNN optimizations with tensorflow. 

By changing this line `os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'` to `os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0' `will resolve the error. 

As this issue is more related to tensorflow-core [onednn](https://blog.tensorflow.org/2022/05/whats-new-in-tensorflow-29.html), so you can raise new issue in tensorflow repo.
