### ISSUE TITLE
Why can tf.range not be jit_compiled when used in a Keras model?

### ISSUE THREAD

**Issue by jhoydis** [keras-team/keras#20592]
I am running TF 2.18 and Keras 3.7 on a GPU using Python 3.12 on Ubuntu 22.04.

I would like to understand why this code throws an `OperatorNotAllowedInGraphError`:
```
class Model(tf.keras.Model):
    def call(self, x):
        for _ in tf.range(5):
            x += 1
        return x

model = Model()

@tf.function
def fun(x):
    return model(x)
fun(tf.cast(5, tf.int32))
```

while this version, where the `call` function is decorated,  works without any problem:

```
class Model(tf.keras.Model):

    @tf.function
    def call(self, x):
        for _ in tf.range(5):
            x += 1
        return x

model = Model()

def fun(x):
    return model(x)
fun(tf.cast(5, tf.int32))
```

Both code snippets work in TF 2.15.

**Comment by fchollet** [comment]
Using `for _ in x` where `x` is a tensor is disallowed when compiling.

The reason why it appears to work when you use the `tf.function` decorator is because that decorator does much more than compiling. In particular it applies a piece of software called Autograph to your function. Autograph copies your entire code to a temporary Python file (transpilation) and rewrites it in a minified / obfuscated format that is impossible for humans to read. In the process it rewrites lots of things about your code, in ways you may not have intended, which includes replacing `for _ in x` with a `tf.while_loop` operation (which makes it work with compilation).

This convenience (being able to use a Python `for` instead of `keras.ops.fori_loop` or something) comes at a heavy cost: it becomes impossible to debug your code in case something goes wrong. The stack traces are generated from the obfuscated temporary files generated by Autograph. Also, Autograph adds considerable overhead to the compilation process.

Overall Autograph has been one of the main factors that have caused the TF debugging experience to be extremely poor and TF to feel slow / unresponsive. Autograph is disabled across the whole Keras 3 codebase.

**Comment by jhoydis** [comment]
Thanks!
