### ISSUE TITLE
Convolution Grouping Feature

### ISSUE THREAD

**Issue by Sowasa** [keras-team/keras#3334]
cuda-convnet and Caffe have the feature of doing grouped convolutions.
So basically if you have 2 inputs and define 2 groups and N filters in your current layer, you will have 2*N output feature maps. 

https://github.com/BVLC/caffe/blob/master/src/caffe/layers/base_conv_layer.cpp#L117

I am using this feature extensively in Caffe and am wondering if there is an equivalent in Keras and if not, what the most efficient way to implement it would be. As far as I know, cudnn supports it as well. It would be great to have this feature supported in Keras.

**Comment by nouiz** [comment]
cudnn do not support this. This make it more complicated to support in
Theano. The cuda-convnet code have been wrapped in Theano Op in Pylearn2.
You could make a layer that use them and have a dependency on Pylearn2, but
only use that part of Pylearn2.

Otherwise, you will need to move that code from Pylearn2 to Keras or Theano.

**Comment by nouiz** [comment]
There is a PR in Theano to implement it. So it should be there shortly.

https://github.com/Theano/Theano/pull/5991

**Comment by 0x00b1** [comment]
Merged into Theano.

**Comment by ibmua** [comment]
It's part of CuDNN v7 now, so I'm guessing it will be implemented in the frameworks soon. In case of Theano it might already be by now, not sure.
