### ISSUE TITLE
Keras bindings for Deeplearning4j

### ISSUE THREAD

**Issue by chrisvnicholson** [keras-team/keras#4651]
This is a feature request: We'd like to build Keras bindings for Deeplearning4j, so that Keras could act as DL4J's Python API. Anyone interested in working with us on this is welcome to respond here for contact us at chris@skymind.io.

**Comment by wgy8283335** [comment]
Hi, I am interested in building Keras. I just wonder what exactly shall I do? Is there any request on skill before I work on it? And my email is below: wgy8283335@126.com. Welcome to contact me.

**Comment by souravsingh** [comment]
@chrisvnicholson I am interested in writing the Keras bindings for D4J

**Comment by chrisvnicholson** [comment]
Thanks for stepping up! So here's how we're thinking about this now:

The ideal approach would be calling a method like Keras.save in the cell of a notebook so that gives us the NN configuration, and a server sucks that config in and runs the training on the Deeplearning4j backend. That’s how Hadoop streaming works to run Mapreduce jobs from Python. They just connect over a standard out and we would too. 

So our main work right now will be to achieve feature parity with Keras on the Scala side. 

We just built support for Keras's functional API:

https://github.com/deeplearning4j/deeplearning4j/commit/9f103ff10ce2405ed16ffb8c6574aa16988bf1ac

**Comment by crockpotveggies** [comment]
@chrisvnicholson this can probably be succeeded by https://github.com/fchollet/keras/issues/6042

**Comment by kshitij12345** [comment]
@chrisvnicholson  is it still on? I would like to work on it as well!

**Comment by maxpumperla** [comment]
@kshitij12345 we're working on an autodiff module for nd4j right now. still a lot to do to get all the ops needed for a keras backend. Once we're ready to do so, integration should be straightforward and help appreciated.

I'll keep you posted! feel free to ping me for more info.

**Comment by agibsonccc** [comment]
@kshitij12345 yes this is ongoing. This was a bigger effort than we thought it would be. It turned out we basically had to implement basically "pytorch/tensorflow" including all the ops. The original plan is still in place. We plan on supporting this via our python interface jumpy: https://github.com/deeplearning4j/jumpy - we will likely finish this when our migration to the eclipse foundation is finished and 1.0 is out. That will be later this year.

**Comment by kshitij12345** [comment]
I would really love to be part of this development under guidance and
contribute to project. So please let me know if there's something that I
can work on till then I ll take a look at
https://github.com/deeplearning4j/jumpy and get a feel for it.

Thank You very much

**Comment by agibsonccc** [comment]
@kshitij12345 we  would love to have you, please join the deeplearning4j gitter: https://github.com/deeplearning4j/jumpy and take a look at snapshots. The main thing I've been wanting to clean up with jumpy is how it handles the jar file. A seamless default jar file (instead of the uber jar build instructions there) would be great. We already have import and samediff itself working. To be clear, this *will* involve some interaction with java though. The whole point of jumpy is to be a fast python interface (at the c level) to Java Native Interface up to the Java Virtual machine to run nd4j commands. The basics are there though. For some of the benefits and intent see: https://www.slideshare.net/agibsonccc/strata-beijing-2017-jumpy-a-python-interface-for-nd4j

The general idea here is to push something in to the spark ecosystem that's more purpose built for ndarrays specifically over the networking approach that spark currently uses (which eliminates any useful gains you would see from interacting with the gpu and the like)

**Comment by jmrozanec** [comment]
I would also be glad to join this effort! Just joined the deeplearning4j gitter. Is there anything we can start working on?

**Comment by agibsonccc** [comment]
Coordinate with @maxpumperla and @farizrahman4u in the gitter. Thanks for the interest!

**Comment by akshaysharma096** [comment]
Hey, I will also like to join the effort. Where can I start from?

**Comment by maxpumperla** [comment]
@akshaysharma096 I've created a public gitter channel to coordinate work on this. Maybe others want to join as well. It's a little early still, but we could use some momentum. :)

**Comment by maxpumperla** [comment]
https://gitter.im/deeplearning4j/dl4j-keras-backend

**Comment by akshaysharma096** [comment]
Sure @maxpumperla :) 

Thank you so much!

**Comment by gabrieldemarmiesse** [comment]
It's been quite a while since there were updates on this. I'm closing the issue but feel free to reopen if necessary.
