### ISSUE TITLE
Does TimeDistributed support variable input size?

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#6917]
It seems like TimeDistributed layer doesn't support variable-size inputs. 

In details, I have simple Convolutional layers only model called conv_model, which accepts variable-size inputs, specifically the variable number of rows. However, when I use TimeDistributed on conv_model, the code crashes.

`conv_input = Input((None, 32, 1), dtype='float')`
`conv1 = Conv2D(32, (3, 3), activation='relu')(conv_input)`
`conv_model = Model(inputs=conv_input, outputs=conv1)`

`input_sequence = Input(input_shape=(10, None, 32, 1))`
 `conv_sequence = TimeDistributed(conv_model)(input_sequence)`

Does the Time Distributed layer even support varying size inputs? If not, is there any fix for that?

Thanks!

**Comment by ericwu09** [comment]
I'm also interested in finding out; did you find a solution?

**Comment by fortu1tus** [comment]
No, I didn't, I just moved to tensorflow. It's more flexible in this regard.

**Comment by thawn** [comment]
I have the same problem. I have stacks of 10 grayscale images. For each image in the stack, I would like to apply a variable size Conv2D layer. Therefore I used TimeDistributed with a variable size Conv2D:
```python
i = Input((10,None,None,1))
x1 = TimeDistributed(Conv2D(32, (3,3), activation='relu', padding='same'))(i) 
```
A Conv2D layer alone accepts (None,None,1) as input_shape. Therefore, I would expect TimeDistributed to accept (10,None,None,1) as input_shape.

Unfortunately, I get a TypeError:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    520     try:
--> 521       str_values = [compat.as_bytes(x) for x in proto_values]
    522     except TypeError:

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in <listcomp>(.0)
    520     try:
--> 521       str_values = [compat.as_bytes(x) for x in proto_values]
    522     except TypeError:

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/util/compat.py in as_bytes(bytes_or_text, encoding)
     60     raise TypeError('Expected binary or unicode string, got %r' %
---> 61                     (bytes_or_text,))
     62 

TypeError: Expected binary or unicode string, got -1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-126-38ad0de5f2a5> in <module>()
      1 #x_train.shape[1:]
----> 2 model = build_model_dense( (10,None,None,1) , len_embedding=len_embedding)
      3 if len_embedding == 1:
      4     model.compile(loss=dice_loss, optimizer='adam')# metrics=[dice_coefficient])
      5 else:

<ipython-input-121-0df17b1a48bb> in build_model_dense(input_shape, len_embedding)
      5     i = Input(input_shape)
      6 
----> 7     x1 = TimeDistributed(Conv2D(32, (3,3), activation='relu', padding='same',input_shape=(None, None, 1)))(i)
      8     x1 = BatchNormalization()(x1)
      9 

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    617 
    618             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 619             output = self.call(inputs, **kwargs)
    620             output_mask = self.compute_mask(inputs, previous_mask)
    621 

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/keras/layers/wrappers.py in call(self, inputs, training, mask)
    206             # transformation in self._input_map.
    207             input_uid = _object_list_uid(inputs)
--> 208             inputs = K.reshape(inputs, (-1,) + input_shape[2:])
    209             self._input_map[input_uid] = inputs
    210             # (num_samples * timesteps, ...)

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in reshape(x, shape)
   1892         A tensor.
   1893     """
-> 1894     return tf.reshape(x, shape)
   1895 
   1896 

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py in reshape(tensor, shape, name)
   6195   if _ctx is None or not _ctx._eager_context.is_eager:
   6196     _, _, _op = _op_def_lib._apply_op_helper(
-> 6197         "Reshape", tensor=tensor, shape=shape, name=name)
   6198     _result = _op.outputs[:]
   6199     _inputs_flat = _op.inputs

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    511           except TypeError as err:
    512             if dtype is None:
--> 513               raise err
    514             else:
    515               raise TypeError(

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    508                 dtype=dtype,
    509                 as_ref=input_arg.is_ref,
--> 510                 preferred_dtype=default_dtype)
    511           except TypeError as err:
    512             if dtype is None:

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
   1105 
   1106     if ret is None:
-> 1107       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1108 
   1109     if ret is NotImplemented:

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    215                                          as_ref=False):
    216   _ = as_ref
--> 217   return constant(v, dtype=dtype, name=name)
    218 
    219 

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    194   tensor_value.tensor.CopyFrom(
    195       tensor_util.make_tensor_proto(
--> 196           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    197   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    198   const_tensor = g.create_op(

/sw/apps/python3/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    523       raise TypeError("Failed to convert object of type %s to Tensor. "
    524                       "Contents: %s. Consider casting elements to a "
--> 525                       "supported type." % (type(values), values))
    526     tensor_proto.string_val.extend(str_values)
    527     return tensor_proto

TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (-1, None, None, 1). Consider casting elements to a supported type.
```

**Comment by 491734045** [comment]
@thawn 
Did you find solution? This problem beset me for weeks.

**Comment by thawn** [comment]
@491734045 I used conv3d instead of TimeDistributed conv2d

**Comment by 491734045** [comment]
@thawn While the weights cannot be shared if using conv3d

**Comment by thawn** [comment]
Not 100% sure but I think that a 1*3*3 Conv3D should do the same as a time distributed conv2D.


Sent from my Smartphone. Please excuse possible typos due to speech input.
-------- Ursprüngliche Nachricht --------Von: Dengqing <notifications@github.com> Datum: 04.12.18  05:48  (GMT+01:00) An: keras-team/keras <keras@noreply.github.com> Cc: thawn <webmaster@korten.at>, Mention <mention@noreply.github.com> Betreff: Re: [keras-team/keras] Does TimeDistributed support variable input size? (#6917) 
@thawn While the weights cannot be shared if using conv3d

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/keras-team/keras","title":"keras-team/keras","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/keras-team/keras"}},"updates":{"snippets":[{"icon":"PERSON","message":"@491734045 in #6917: @thawn While the weights cannot be shared if using conv3d"}],"action":{"name":"View Issue","url":"https://github.com/keras-team/keras/issues/6917#issuecomment-443970082"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/keras-team/keras/issues/6917#issuecomment-443970082",
"url": "https://github.com/keras-team/keras/issues/6917#issuecomment-443970082",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [keras-team/keras] Does TimeDistributed support variable input size? (#6917)",
"sections": [
{
"text": "",
"activityTitle": "**Dengqing**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@491734045",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"keras-team/keras\",\n\"issueId\": 6917,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"keras-team/keras\",\n\"issueId\": 6917\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/keras-team/keras/issues/6917#issuecomment-443970082"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 232045933\n}"
}
],
"themeColor": "26292E"
}
]
