### ISSUE TITLE
why the outputs of predict() and predict_prob() are the same?

### ISSUE THREAD

**Issue by Bjoux2** [keras-team/keras#7390]
I built a CNN model and I used the predict() and predict_prob() methods on x_test set. 

```
y_test_pred = model.predict(x_test)

y_test_pred_prob = model.predict_proba(x_test)

print 'y_test_pred=', y_test_pred

print 'y_test_pred_prob=', y_test_pred_prob
```

the expected result for predict() is a vector with zeros and ones and for predict_prob() is a vector with probability values. 

However, I got the same results for predict() and predict_prob().

```
y_test_pred= 
[[  1.00000000e+00   4.67232875e-09]
 [  9.99997377e-01   2.60892352e-06]
 [  2.02931948e-02   9.79706764e-01]
 ..., 
 [  9.89197075e-01   1.08029414e-02]
 [  5.81803790e-04   9.99418259e-01]
 [  1.08823024e-05   9.99989152e-01]]

y_test_pred_prob=
[[  1.00000000e+00   4.67232875e-09]
 [  9.99997377e-01   2.60892352e-06]
 [  2.02931948e-02   9.79706764e-01]
 ..., 
 [  9.89197075e-01   1.08029414e-02]
 [  5.81803790e-04   9.99418259e-01]
 [  1.08823024e-05   9.99989152e-01]]
```
why?

**Comment by ozabluda** [comment]
Because `Sequential.predict() and Sequential.predict_proba()` are the same thing https://github.com/fchollet/keras/blob/e83041fcd0c4c51c39a1f442e184fcdece019bc8/keras/models.py#L1022 (although some people are unhappy that they produce slightly different results for them (https://github.com/fchollet/keras/issues/6616).
