### ISSUE TITLE
Using data tensors as data sources: action plan

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#7503]
We want to add the ability to feed TensorFlow data tensors (e.g. input queues) into Keras models. A few days ago I met with @athundt and we discussed his previous efforts to make it happen. Here is how we will handle it:

## First step [Update: done]

The following API:

```python
# Get data tensors
data_tensor, target_tensor = ...

# Build model on top of the data tensor
inputs = Input(tensor=data_tensor)
outputs = Dense(...)(inputs)
model = Model(inputs, outputs)

# Add internal loss
loss = loss_fn(target_tensor, outputs)
model.add_loss(loss)

# Compile without external loss
model.compile(optimizer='sgd', loss=None)

# Fit without external data
model.fit(epochs=10, steps_per_epoch=1000)
```

This is already 90% supported. What is missing is the `steps_per_epoch` argument (currently `fit` would only draw a single batch, so you would have to use it in a loop).

**NEEDED:**
- [Update: done] PR introducing the `steps_per_epoch` argument in `fit`. Here's how it works:
   - Based on arguments received, we determine whether training should be step-based (like in `fit_generator`) or sample-based (like in `fit` currently).
   - We have two independent code branches handling each mode.
- [Update: done] PR introducing a MNIST example of how to use data tensors for inputs and targets, following the code snippet above. It should use the MNIST data tensors built-in in TF.

## Second step

The following API:

```python
# Get data tensors
data_tensor, target_tensor = ...

# Build model on top of the data tensor
inputs = Input(tensor=data_tensor)
outputs = Dense(...)(inputs)
model = Model(inputs, outputs)

# Compile as usual
model.compile(optimizer='sgd', loss='mse')

# Fit by passing the target tensor
model.fit(y=target_tensor, epochs=10, steps_per_epoch=1000)
```

Main issue: in `compile`, we create placeholders for the targets. We need to discard them (cache them, actually) and use the provided target tensor instead.

Solution: a model recompilation step inside `fit` in order to cache the previous target placeholder and replace it with our target tensor.

**NEEDED**:
- PR adding support for a target tensor in the call to `fit` for a normally compiled model. Involves a recompilation step.

## Third step

The following API:

```python
# Get data tensors
data_tensor, target_tensor = ...

# Build model on top of placeholders
inputs = Input(shape=(...))
outputs = Dense(...)(inputs)
model = Model(inputs, outputs)

# Compile as usual
model.compile(optimizer='sgd', loss='mse')

# Fit by passing the data tensor and target tensor
model.fit(data_tensor, target_tensor, epochs=10, steps_per_epoch=1000)
```

It's not 100% clear at this point how we will handle it, but we will figure it out. Most likely this will involve building a new TF graph inside `fit`, running training with it, then transferring weight values back to the initial graph. I'll handle it.

CC: @athundt @Dref360 @colinskow @TimZaman

**Comment by TimZaman** [comment]
LGTM. @athundt, do you take the lead in steps (1) and (2)? It seems you've mostly nailed those already.

**Comment by Dref360** [comment]
Step 3 seems really "hacky". Could we ask the TF team if they are willing to handle feeding placeholder with Tensors?

For step 2, I was away for a while so I didn't keep up with @athundt 's PR. But since the `data_tensor` is already there, I see no problem doing : `model.compile(y=target_tensor, optimizer='sgd', loss='mse')`.

Would save one compilation, if you've already talked about it in the PR, ignore this.

**Comment by TimZaman** [comment]
@Dref360 
> Step 3 seems really "hacky".

Yes, it's a bit dirty. But I think Keras's API's do allow us to clean up the graph-surgery mess quite easily, in a way that it's a hack in principle, but it's a great one. We'll see when we get there.

> Could we ask the TF team if they are willing to handle feeding placeholder with Tensors?

We did; issue: https://github.com/tensorflow/tensorflow/issues/10837

> model.compile(y=target_tensor, optimizer='sgd', loss='mse').

On first glance, that sounds pretty sane to me! I don't recall anyone suggesting this?

**Comment by ahundt** [comment]
Sorry guys, I didn't see this until now because @ahundt is the account I actually use, I'm not sure I have access to the other one any more.

@Dref360 I submitted the request for the feature in tensorflow a couple months ago https://github.com/tensorflow/tensorflow/issues/10837.

The graph editing PR might be a good way to implement the underlying functionality for API 3 https://github.com/fchollet/keras/pull/7505

**Comment by PBehr** [comment]
Update 2 and 3 will lead to issues with distributed training. Tensorflow distributed finalizes the graph, so we get an error if we try to recompile the model. See https://github.com/fchollet/keras/issues/3997 for reference

**Comment by fchollet** [comment]
For distributed training you should be using the TensorFlow estimator API.
We are about to release an integration between the estimator API and Keras
models. It will be in TF 1.4.

**Comment by ahundt** [comment]
How should we handle validation data? When a model uses input tensors the data being loaded is pre-defined, so it likely needs to be instantiated a second time or perhaps something like https://github.com/fchollet/keras/pull/7505 would be needed to reconnect the input tensors.

Thoughts?

**Comment by N-McA** [comment]
Maybe this is planned, but support for the automatic validation features (running a test on the validation set after each epoch, early stopping, learning rate adjustment based on val scores) that Keras allows would be great through this API as well. That in the pipeline?

**Comment by fchollet** [comment]
Yes, that's still in the pipeline, as well as the ability to call
`fit`/`evaluate`/`predict` directly on data tensors for a model built on
top of placeholders. You'll probably have it by TF 1.6.

**Comment by ahundt** [comment]
Cool, thanks! I saw [the tf + keras estimator API](https://www.tensorflow.org/api_docs/python/tf/keras/estimator) is out with 1.4, perhaps there is an example somewhere?

**Comment by ahundt** [comment]
Found an [example of estimators in horovod](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist_estimator.py), and it seems to convert a keras model to tf you use [model_to_estimator](https://github.com/tensorflow/tensorflow/issues/8787#issuecomment-357306320).

**Comment by sekharvth** [comment]
@R-Miner I tried using the 3rd step where tensors are directly passed as input to the model. But it threw me an AttributeError saying that 'Tensor' object has no attribute 'ndim'. I'm running Keras 2.1.6 on top of Tensorflow 1.8 . 
@fchollet said that the issue would be most likely resolved by TF 1.6, but since there haven't been any further updates about that on this thread, I'm not sure if step 3 has been implemented.
It would be great to get an update regarding this.

**Comment by psoulos** [comment]
Is there a way to save and load models that use data tensors as data sources? I am able to create the original model and save it, but I'm not sure how to load the model. If I call load_model(), how do I correctly specify the input tensor? I found [this stackoverflow answer](https://stackoverflow.com/questions/49546922/keras-replacing-input-layer) for replacing the input tensor, but this creates a dangling input which prevents me from saving the model.

**Comment by TimZaman** [comment]
@psoulos you cannot. A model that you load in sadly is always created on top of placeholders. The only thing you can do is:
```python
x = $your_input_tensor
m1 = keras.$.load_model()
m2 = Model(inputs=x, outputs=m(x))
```

**Comment by psoulos** [comment]
@TimZaman Will that allow me to continue training without losing the state of my optimizer and configuration? Currently I'm re-creating the model architecture and calling `model.load_weights` but this makes it difficult to continue training.

**Comment by was84san** [comment]
I tried to use the third step but then I have this error 
"  When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 64, 64, 3)"

**Comment by was84san** [comment]
I tried to use the third step but then I have this error
" When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 32, 64, 64, 3)"

I used the following strategy to fit the model :


training_filenames = [.....]
dataset = tf.data.TFRecordDataset(training_filenames)
dataset = dataset.map(_parse_function_all)  # Parse the record into tensors.

dataset = dataset.batch(20)
iterator = dataset.make_initializable_iterator()
next_element= iterator.get_next()  
# here I have videos with their label in pair fashion but I use one first pair
# video will be next_element [0], label = next_element[1]
# since it is pair I will use only first pair for training and second pair for validation 
# train_video = next_element [0][:, 0]  val_videos = next_element[0][:, 1]
# same with labels


model = create_base_network()  
#input_dim = (None, 32, 64, 64 3) for the model above
# output dimension will be (None, 10) for the model above


sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(next_element_train[0][:, 0],   next_element_train[1][:, 0], validation_data=(next_element_train[0][:, 1],  next_element_train[1][:, 1]), epochs=10, steps_per_epoch=1000)

**Comment by was84san** [comment]
I tried to use the third step but then I have this error
" When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 32, 64, 64, 3)"

I used the following strategy to fit the model :

training_filenames = [.....]
dataset = tf.data.TFRecordDataset(training_filenames)
dataset = dataset.map(_parse_function_all) # Parse the record into tensors.

dataset = dataset.batch(20)
iterator = dataset.make_initializable_iterator()
next_element= iterator.get_next()

% here I have videos with their label in pair fashion but I use one first pair
% video will be next_element [0], label = next_element[1]

% since it is pair I will use only first pair for training and second pair for validation
% train_video = next_element [0][:, 0] val_videos = next_element[0][:, 1]
% same with labels

model = create_base_network()
% input_dim = (None, 32, 64, 64 3) for the model above
% output dimension will be (None, 10) for the model above

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(next_element_train[0][:, 0], next_element_train[1][:, 0], validation_data=(next_element_train[0][:, 1], next_element_train[1][:, 1]), epochs=10, steps_per_epoch=1000)

**Comment by was84san** [comment]
I tried to use the third step but then I have this error
" When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: (None, 32, 64, 64, 3)"

I used the following strategy to fit the model :

training_filenames = [.....]
dataset = tf.data.TFRecordDataset(training_filenames)
dataset = dataset.map(_parse_function_all) # Parse the record into tensors.

dataset = dataset.batch(20)
iterator = dataset.make_initializable_iterator()
next_element= iterator.get_next()
% videos will be next_element [0], labels = next_element[1]

% since it is pair I will use only first pair for training and second pair for validation
% train_video = next_element [0][:, 0] val_videos = next_element[0][:, 1]
% same with labels

model = create_base_network()
% input_dim = (None, 32, 64, 64 3) for the model above
% output dimension will be (None, 10) for the model above

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(next_element[0][:, 0], next_element[1][:, 0], validation_data=(next_element[0][:, 1], next_element[1][:, 1]), epochs=10, steps_per_epoch=1000)

So any one can tell me why I got this error? 
Is the third step of fitting the model working now in kerns? or still have issues

**Comment by nmiculinic** [comment]
Hmmm...how is this suppose to work with validation dataset? Is it possible to inject both via those API's or do I have to resort to tf magic?

**Comment by dillondaudert** [comment]
I wanted to leave a comment here so others could see, but as of tensorflow 1.9, the tf.keras package supports using tf.data.Datasets and tf.data.Iterators as inputs to Model.fit()/evaluate()/predict(). See the documentation [here](https://www.tensorflow.org/versions/r1.9/api_docs/python/tf/keras/Model#fit).

For instance, this works as of tf1.9:
```python 
import tensorflow as tf
import numpy as np
from tensorflow import keras

inputs = np.zeros((10, 3))
targets = np.zeros((10, 4))
dataset = tf.data.Dataset.from_tensor_slices((inputs, targets))
dataset = dataset.repeat(100)
dataset = dataset.batch(5)

x = keras.layers.Input(shape=(3,), name='input')
y = keras.layers.Dense(4, name='dense')(flat)

model = keras.Model(x, y)
model.compile(loss='mse', optimizer='rmsprop')

model.fit(dataset, epochs=1, steps_per_epoch=2, validation_data=dataset, validation_steps=2)
```

I'm not sure what the exact differences between `keras-team/keras` and `tensorflow/keras` are at this point, but it seems that tf.data.Dataset support is further along in the latter.

**Comment by was84san** [comment]
@ dillondaudert . So thats mean I can't use it with tensor flow 1.8 version.

**Comment by lminer** [comment]
@was84san seems to work if you call `.set_shape((YOUR SHAPE INCLUDING BATCH SIZE))` on the tensors you get from `.get_next()`

**Comment by was84san** [comment]
@Iminer , I did that and still have this error
AttributeError: "'Tensor' object has no attribute 'ndim'"

**Comment by ac1dxtrem** [comment]
What's the current support for Model.predict(some_data), if I have hard wired tf.data.Dataset iterator as an input tensor to my model? Namely, I have something similar to the following:

```
# dataset = Some tf.data.Dataset
dataset_iterator = dataset.make_one_shot_iterator()
input_tensor_x, input_tensor_y = dataset_iterator.get_next()
outputs = Dense(10)(inputs)
model = Model(inputs=[input_tensor_x], outputs=[outputs])
model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['categorical_accuracy'],
        target_tensors=[input_tensor_y]
)
```

How can I call model.predict(data_to_be_predictied) on such a model?

**Comment by manoskav** [comment]
Is it possible to feed Tensors in `fit()` when executing eagerly?
I mean, when executing non-eagerly, one can describe a data generating graph in TensorFlow and then feed the resulting Tensors of this graph in `fit()`. Then, the batch is generated by executing that graph.

For example, in non-eager mode

```
def trainingTensors():

        x_t = tf.compat.v1.random_uniform((128, 100), 0, 2, dtype=tf.int32)
	z_t = tf.compat.v1.random_normal((128, 100), mean=1.0,
						  stddev=0.3, dtype=tf.float32)
	X_train = x_t * z_t
	Y_train = tf.sign(z_t)
	
	return X_train, Y_train
```


```
X_train, Y_train = trainingTensors()
model = Model(...)
model.compile(...)
model_log = model.fit(X_train, Y_train,
			steps_per_epoch=5000,
			epochs=1000,
			verbose=1)
```

Is there any way to have similar behavior in eager mode?

P.S. First, they force you to describe graphs. You find it hard and you hate it with all of your soul. Then you love it. Then they kill what you love.
