### ISSUE TITLE
ValueError: Input 0 is incompatible with layer permute_1: expected ndim=3, found ndim=4

### ISSUE THREAD

**Issue by keiv-fly** [keras-team/keras#7962]
Permute does not work with 4 dimensions.
When I execute the following code:

```
from keras.models import Sequential
from keras.layers.core import Permute
m = Sequential()
m.add(Permute((2,1),input_shape=(8,8,4)))
```

I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-b0b480e25061>", line 1, in <module>
    m.add(Permute((2,1),input_shape=(8,8,4)))
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\models.py", line 442, in add
    layer(x)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\topology.py", line 558, in __call__
    self.assert_input_compatibility(inputs)
  File "C:\Users\Lenovo\Anaconda3\lib\site-packages\keras\engine\topology.py", line 457, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer permute_1: expected ndim=3, found ndim=4
```

I thought that permuting 4D arrays is allowed. Is it a bug?

PS: Before posting I updated keras and TensorFlow

**Comment by keiv-fly** [comment]
I found out that m.add(Permute((2,1,3),input_shape=(8,8,4))) works. It is not evident from the documentation that one should write numbers of all dimensions. Can the documentation be updated so that there is an example also with 4 dimensions?

**Comment by facaiy** [comment]
Not sure whether it is a bug. Because I found that `Permute` is more powerful than that its name implies. For tensorflow backend, it use [`transpose`](https://www.tensorflow.org/api_docs/python/tf/transpose) method which allows to reorder total axis, eg: [3, 1, 2]. Perhaps that is why `dims` is designed to keep the same size with `input_shape`.

https://github.com/fchollet/keras/blob/710898f759b9ec229f3513bb9f58fd032c1aaed6/keras/backend/tensorflow_backend.py#L1700-L1711

**Comment by KIC** [comment]
for 4D you need to specify all other indices than sample size: i.e. `tf.keras.layers.Permute((2, 1, 3))`
