### ISSUE TITLE
MobileNet initialization fails for small input_shape

### ISSUE THREAD

**Issue by jakubczakon** [keras-team/keras#8090]
Initializing MobileNet for small dimensions of input_shape fails with unclear error messages
Running
```python
from keras.applications.mobilenet import MobileNet
model = MobileNet(weights='imagenet', include_top=False, input_shape=(64, 64, 3))
```
produces misleading error
```python
ValueError: When setting`include_top=True`, `input_shape` should be (224, 224, 3).
```
That seems to signify that I have specified include_top=True
Also, from reading the code i thought that it should work for shapes larger than 32x32 but it seems that the lowest viable shape is 128x128.

**Comment by titu1994** [comment]
MobileNets have many different input size configurations, and so I had to bypass some of the default behaviour of the input shape checks. 

You are using an input shape of 64x64 but trying to load weights, where no weights for such an input size exist. The minimum is 128x128. 

I agree that the error message should be more informative, but the docs clearly states the valid sizes for weights = ImageNet are 128, 160, 192 and 224.

**Comment by jakubczakon** [comment]
Ok, thanks!

**Comment by Shiro-LK** [comment]
Hello I have the same problem but for the shape (128, 128, 3) is it normal ? 
With the inception model, I can change the input_shape and load the weight at the same time.

**Comment by yu4u** [comment]
I got the same error.
I agree that `rows` should be one of [128, 160, 192, 224] if `include_top=True`, but it is very useful (to me) if I can use arbitrary `rows` (>= 32) only for `include_top=False`.
I think this is possible by loading "nearest" model (or always load 224-model for any input_size >= 32) like this:

https://github.com/fchollet/keras/blob/master/keras/applications/mobilenet.py#L530

```
else:
    model_rows = min(filter(lambda x:x >= rows, [128, 160, 192, 224]))
    model_name = 'mobilenet_%s_%d_tf_no_top.h5' % (alpha_text, model_rows)
    weigh_path = BASE_WEIGHT_PATH + model_name
    weights_path = get_file(model_name,
                            weigh_path,
                            cache_subdir='models')
```

**Comment by DingkunLiu** [comment]
I don't fully understand, why mobile net can only use the imagenet weights for the 4 specified input shape even "include_top" has been set to false? Does convolution have anything to do with the input shape?

**Comment by ogencoglu** [comment]
@DingkunLiu MobileNet employs depth-wise convolutions. That's why.

**Comment by mthiemann** [comment]
The number of parameters for depth-wise separable convolutions doesn't depend on the image dimensions, so why doesn't Keras support this?

**Comment by gged** [comment]
add weights=None

**Comment by alyato** [comment]
@gged 
I use the `ResNet50` ,set the `weights=None` ,it doesn't  work.

> model = ResNet50(weight=None,include_top=False,input_shape=(48,48,3))

**Comment by plapa** [comment]
> @gged
> I use the `ResNet50` ,set the `weights=None` ,it doesn't work.
> 
> > model = ResNet50(weight=None,include_top=False,input_shape=(48,48,3))

In the last few days it has stopped working for me as well. Previously I would be able to use ResNet50 with shape (64, 64, 3) and include_top = False, but today I am not longer capable.

**Comment by apatsekin** [comment]
Just as an idea how to override this size exception: use input_tensor instead of input_shape:
`input_tensor = Input(shape=(IMAGE_SIZE, IMAGE_SIZE, 3))`
And set as a param for MobileNet as `input_tensor = input_tensor`

It will work with a notification that default weights a loaded. Although not sure the behavior is expected.

**Comment by iphton** [comment]
> MobileNets have many different input size configurations, and so I had to bypass some of the default behaviour of the input shape checks.
> 
> You are using an input shape of 64x64 but trying to load weights, where no weights for such an input size exist. The minimum is 128x128.
> 
> I agree that the error message should be more informative, but the docs clearly states the valid sizes for weights = ImageNet are 128, 160, 192 and 224.

input_shape: optional shape tuple, only to be specified if include_top is False (otherwise the input shape has to be (224, 224, 3) (with 'channels_last' data format) or (3, 224, 224) (with 'channels_first' data format). It should have exactly 3 inputs channels, and width and height **[should be no smaller than 32](https://keras.io/applications/#mobilenet)**. E.g. (200, 200, 3) would be one valid value.

**Comment by illfang** [comment]
I believe, the enforcement of the default input size has been introduced in https://github.com/keras-team/keras-applications/pull/62 to solve https://github.com/keras-team/keras/issues/10109 and https://github.com/keras-team/keras/issues/12013

The misleading error message results from a validation where NASNet now always passes `True` where other implementations pass the `include_top` value.

**Comment by mjkvaak** [comment]
I had a lot of trouble with this one. Finally I got NASNet working by installing with conda: `conda install -c anaconda tensorflow-gpu`. Also, I imported NASNet from keras.applications (`from keras.applications import NASNetMobile`), not from from keras.applications.nasnet (`from keras.applications.nasnet import NASNetMobile`), but I'm not sure if this makes any difference.

**Comment by Chadys** [comment]
Tried to use `NASNetLarge` today with `weights="imagenet"`, `include_top=False` and `input_shape=(225, 225, 3)`, and I get the same error with misleading message. 
```python
ValueError: When setting `include_top=True` and loading `imagenet` weights, `input_shape` should be (331, 331, 3).
```
Right now, the `NASNet` function calls `_obtain_input_shape`with `require_flatten=True`, so no matter the `include_top`value you use, this error will always happens if your `input_shape`is not the default one. Either the code needs to be updated to accept custom shape with imagenet weights, or the  error message and documentation (which make no mention on shape requirement depending on `weights` and not only on `include_top`) need to be updated.
