### ISSUE TITLE
Pansharpening (Multi-input)

### ISSUE THREAD

**Issue by reshadshuvo123** [keras-team/keras#8243]
I am doing a project based on Pansharpening where high spatial resolution panchromatic image (gray image) and low resolution multi-spectral image  (8 bands image) are merge to create pan-sharped image (high spatial resolution and high spectral resolution). 

Here I have two image : 

Pan = (21896, 1, 33, 33)  # Pan image shape
Multi-spectral image = (21896, 8, 33, 33)  # Multi-spectral image shpape

I want to feed these image to the following CNN because I have 2 inputs.

x = Convolution2D(64, 9, 9, input_shape=(?, 33, 33), activation='relu', init='he_normal')(inputs)  # here two input = (1, 33, 33) & (8, 33, 33)#

x = Convolution2D(32, 1, 1, activation='relu', init='he_normal')(x)
x = Convolution2D(8, 5, 5, init='he_normal')(x)
m = Model(input=inputs, output=x)
m.compile(Adam(lr=0.001), 'mse')

Can you please tell me how I can do this and what will be input in that case?. Thanks

**Comment by titu1994** [comment]
StackOverflow is more appropriate for such questions, since it is not bug related. 

In any case, given that you have exactly same number of in ages, and image size for the two types of images, you can simply concatenate the Pan and Multispectral images into a single vector of shape (N, 9, 33, 33) using numpy concatenate method. Then there is 1 input to the CNN of shape=(9, 33, 33)

**Comment by reshadshuvo123** [comment]
Thank you ..... I also have another case where image numbers are different.  In that what will be the solution. Thanks in advance
