### ISSUE TITLE
concatenate neural network with other ML algorithms

### ISSUE THREAD

**Issue by amaltarghi** [keras-team/keras#8314]
hi i have an  issue i need to use the embedding for encoding feature than concatenate the output with another machine learning algorithm instead of neural network it is possible ?

**Comment by VishnuDuttSharma** [comment]
The embedding layer in keras learns the weights during training phase, so it might not be possible to do what you directly. You can try following:
(1) Implement the other ML algorithm in keras and train the complete model. 
(2) Use other tools like gensim, t-SNE or encoder
(3) Depending upon the ML algorithm, you can train embedding layer first and then take a slice. For example, suppose I want to use SVM. First, I will train an embedding layer followed by a neural net. This will force the embedding layer to learn weights in a way so that there is a separation boundary between the output of embedding layer. Than use the embedding learned here to before SVM.

(2) and (3) are similar, only difference being that (2) is unsupervised representations learning while (3) is a supervised one.
