### ISSUE TITLE
multi_gpu_model 

### ISSUE THREAD

**Issue by elwardani** [keras-team/keras#8324]
First of all, I would like thank you about this great work.
I notice that the "multi_gpu_model" does not exploit the maximum of GPU computing available why?
![image](https://user-images.githubusercontent.com/30388040/32235003-2eadc196-be56-11e7-9a07-1a9346cf66c7.png)
best regards.

**Comment by AndrasEros** [comment]
Probably PCIe bandwidth. Could you please share your code that is resulting this workload? Also the header of this report since I can't reproduce it. If you change between GPUs when you have a large number of parameters (like after a main dense layer) than data transfer to other GPUs can become a bottleneck. You have 4 GPUs but you can be way much slower than a single GPU with a bad network design.

**Comment by elwardani** [comment]
I use examples of models keras like VGG16, InceptionV3 ... I also notice that for the first and second time, the execution took 4 hours for each but for the third time 14 hours!

**Comment by elwardani** [comment]
I use examples of keras models like VGG16, InceptionV3 ... I notice also that for the first and second epochs, the execution time took 4 hours for each one but for the third one it will take 14 hours!
![image](https://user-images.githubusercontent.com/30388040/32293113-17b3f9d0-bf3a-11e7-915f-5ad3e65f006d.png)

**Comment by dunnock** [comment]
When using multi_gpu_model batch is actually split by number of GPUs, therefore for fair perf comparison batch size should be 4 times bigger. I had similar issue and increasing batch size have helped.
