### ISSUE TITLE
ValueError: KerasClassifier doesn't support sample_weight.

### ISSUE THREAD

**Issue by abntu** [keras-team/keras#8448]
I want to use AdaBoostClassifier on CNN. I created a function called ‘create_model’ that define my model and compile it. Then I use KerasClassifier:

model = KerasClassifier(build_fn=create_model, epochs=2, batch_size=128, verbose=0, sample_weight=None)
bdt_discrete = AdaBoostClassifier( model, n_estimators=2, learning_rate=1.5,
algorithm=”SAMME”)
bdt_discrete.fit(X_train, y_train, sample_weight=None)
It gives the following error:
ValueError: KerasClassifier doesn’t support sample_weight.
Is there any solutions for the error:
###################################

File “/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py”, line 688, in runfile
execfile(filename, namespace)

File “/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py”, line 93, in execfile
builtins.execfile(filename, *where)

File “~adaboost_CNN3.py”, line 251, in
bdt_discrete.fit(X_train, y_train, sample_weight=None)

File “/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py”, line 413, in fit
return super(AdaBoostClassifier, self).fit(X, y, sample_weight)

File “/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py”, line 130, in fit
self._validate_estimator()

File “/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py”, line 431, in _validate_estimator
% self.base_estimator_.__class__.__name__)

ValueError: KerasClassifier doesn’t support sample_weight.
##########################
Please let me know if there are any advice.

**Comment by vivekk-ezdi** [comment]
Thats because the AdaboostClassifier only support those base_estimators which have a sample_weight in their fit() method.

Now although KerasClassifier supports sample_weight (`from Sequential.fit()`) by using the **kwargs in KerasClassifier.fit(), but scikit-learn uses a [signature detecting function](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/validation.py#L671) which checks the parameters available only in the KerasClassifier.fit()

This is what it returns:

```
from sklearn.utils.fixes import signature
print(signature(model.fit))
```
#  Output:    (x, y, **kwargs)

As you can see that the sample_weight is not present here, so AdaBoostClassifier will throw an error. One possible workaround is to extend the KerasClassifier class and then update the fit() method to add sample_weight there.

**Comment by fchollet** [comment]
> I am not sure what can be done in the source code of KerasClassifier or in AdaboostClassifier for that case to handle this.

You could change the signature of `KerasClassifier.fit()` to include `sample_weight` explicitly. Feel free to open a PR (with tests).
