### ISSUE TITLE
Feature Suggestion: Fit_generator current queue size

### ISSUE THREAD

**Issue by tRosenflanz** [keras-team/keras#8673]
Hello,

With continuous improvements to fit_generator it could be useful to expose number of batches that is currently generated inside the queue:
 Seeing that we are moving to multi-gpu training and each GPU is becoming more and more powerful, data generation can frequently become a bottleneck of training  but monitoring how different settings of queue_size and workers on the fit_generator effect the training speed is not straightforward. By exposing number of batches inside the queue user will be able to immediately see if current workers are not able to fill up the queue fast enough or if there is a significant variance between different steps of training. Best way to do that right now that I am aware of is to monitor Gpu utilization but that is somewhat ad hoc and can be effected by other issues on the system. 

 Thank you for continuous support to an awesome library.

**Comment by knathanieltucker** [comment]
I really like the suggestion here. 

Perhaps one way to do this would be in the get() methods of the OrderedEnqueuer and the GeneratorEnqueuer. 

In [line 758](https://github.com/keras-team/keras/blob/29ee89a0663c96f6476aa7145b4f27684442b779/keras/utils/data_utils.py#L748) it looks like we sleep if the queue is empty. If we simply record the amount of time we waited on the queue in the method and printed it out with the stop() method above, I think this would go a really long way. We could know the amount of downtime we forced ourselves to have because of an empty queue.
