### ISSUE TITLE
Image Data Generator memory error while fit

### ISSUE THREAD

**Issue by DableUTeeF** [keras-team/keras#8706]
I'm trying to use std_normalization and ZCA whitening but I cannot fit the data generator with 224*224 image.
It's show this.
Traceback (most recent call last):
  File "v1_first_train.py", line 197, in <module>
    train_datagen.fit(X)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 682, in fit
    sigma = np.dot(flat_x.T, flat_x) / flat_x.shape[0]
MemoryError
And this while I tried to fit it with 32*32 image.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 1036, in next
    x = self.image_data_generator.standardize(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 521, in standardize
    whitex = np.dot(flatx, self.principal_components)
ValueError: shapes (1,519168) and (3072,3072) not aligned: 519168 (dim 1) != 3072 (dim 0)

**Comment by zkself** [comment]
Hi, i have the same question .do you fix it?

**Comment by DableUTeeF** [comment]
No I have not.
But it work fine without ZCA whitening, featurewise/centerwise operation.

**Comment by csheaff** [comment]
Hello, same issue here. Even when I reduce the number of images to 1, I get the memory error when using ZCA whitening. My images are 384 x 384.

**Comment by znorman-harris** [comment]
I have the same issue. My input data is about 2.6 GB total [1509, 768, 768, 3] and the machine I am running on has 126 GB of RAM. Watching the resources as the fit method runs, it uses >25GB of RAM and then I get the memory error with more than 70 GB of RAM free. I still had the same error when switching to numy memmaps as input instead of the raw data. Even when I tried to fit the data generator on 100 of my samples instead of all of them, I still get the memory error with more than 100 GB of RAM free.

My solution to the problem was, assuming that the centers of my training data would contain information about most of my scenes, I sliced my arrays with x elements around the center. Here is my code snippet to fit the generator on a subset of the data. I use `**kwargs` in my class method to pass on all augmentation parameters to the ImageDataGenerator constructor which I then check after creating the generator if it needs to be fitted:

```python
    # fit our color transforms if needed
    for key in ['featurewise_center', 'featurewise_std_normalization', 'zca_whitening']:
      if key in kwargs:
        if kwargs[key]:
          # get our X and Y start/ends for subscripting, self.input_shape is [channels, rows, cols]
          fit_width = 50
          xDelt = (self.input_shape[1] - fit_width)//2
          yDelt = (self.input_shape[2] - fit_width)//2

          # subset our data so that we can fit it which returns 
          # dimensions [samples, fit_width, fit_width, channels] or [samples, channels, fit_width, fit_width]
          if K.image_data_format() == 'channels_last':
            sub = x[:, xDelt:-xDelt, yDelt:-yDelt, :]
          else:
            sub = x[:, :, xDelt:-xDelt, yDelt:-yDelt]

          print('Fitting data generator for color transforms...')
          self.data_generator.fit(sub, seed=seed)
          print('  Fittted!')
          print('')
          break
```

**Comment by denizn** [comment]
@csheaff Clay, did you find a solution to this one by any chance? I have 8 gbs of ram on a top end gpu, but it seems like it's not enough to process even a single image of 299x299 for ZCA whitening.

**Comment by csheaff** [comment]
@denizn It appears that there is a memory leak with this operation and there is no feasible solution: https://github.com/keras-team/keras-preprocessing/issues/55

**Comment by Nestak2** [comment]
The problem is not a memory leak, but that the zca-calculation takes very, very long, because it [uses][2] `linalg.svd()` which is computationally heavy even on matrices (n*m*3), n=m=100 (see [here](https://github.com/keras-team/keras-preprocessing/issues/55)). There are some approaches to calculate a quick approximation of the svd, like randomized svd by [scikitlearn][3], truncated svd by [irlb][4], Lanczos method svd, but they are not always numerically stable.

I think I have found another very simple approximation, that appears to give good enough results and is very quick! It helps in case you have a data matrix with shape (m x n), where m is much smaller than n - e.g. you have much less images (m=1000) than number of pixels (n=100 x 100 x 3 = 30000 pixel). In such a case keras would calculate the `linalg.svd(sigma)`, with `sigma.shape=(30000,30000)`, which is computationally too exhausting and takes forever. But in a good approximation, instead of calculating the svd on a (n x n) matrix you could calculate it on a (m x m) matrix, by just rotating the input data X or flipping the order of the `sigma` calculation to look like `sigma = np.dot(flat_x, flat_x.T) / flat_x.shape[0]`. With this approach the calculation takes only ca. 10 sec, if m=1000 and n=30000. The good thing is that the eigenvectors of the `linalg.svd(sigma)` are the same in both cases up to a factor, see [here][5], slide 30. You could test this on a dataset of yours or on the inbuilt cifer set with `from keras.datasets import cifar10`.

Unfortunately, I don't have the mathematical argumentation of this approach, but I have done visual inspections of the zca-images from both calculations and they look very similar: 

[![enter image description here][6]][6]
[![enter image description here][7]][7]

And below is the modified keras code for creating the zca calculations. You could use it to make modifications into your keras zca code, located [here][2]: There are only 2 modifications I have made that get activated if `zca_rotated=True`:

    from keras.datasets import cifar10
    import numpy as np
    from scipy import linalg
    
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()
    X = X_train[:1000]
    flat_x = np.reshape(x, (x.shape[0], x.shape[1] * x.shape[2] * x.shape[3]))
    
    # line below lets you choose if you want to calculate the standard zca, like in keras (=False)
    # or if you want to treat the input data X as rotated to simplify the calculation if X.shape[0]=m < X.shape[1]=n
    zca_rotated = True
    
    # normalize x:
    flat_x = flat_x / 255.
    flat_x = flat_x - flat_x.mean(axis=0)
    
    # 1ST CHANGE IN CALCULATION BELOW
    if zca_rotated == False:
        sigma = np.dot(flat_x.T, flat_x) / flat_x.shape[0]
    elif zca_rotated == True:
        sigma = np.dot(flat_x, flat_x.T) / flat_x.shape[0]
    
    u, s, _ = linalg.svd(sigma)
    s_inv = 1. / np.sqrt(s[np.newaxis] + 0.1) # the 0.1 is the epsilon value for zca
    principal_components = (u * s_inv).dot(u.T)
    
    # below is the calculation of the actual zca-image with the fitted parameters from above
    # 2ND CHANGE IN LINE BELOW
    if zca_rotated == False:
        whitex = np.dot(flat_x, principal_components)
    elif zca_rotated == True:
        whitex = np.dot(flat_x.T, principal_components)


  [1]: https://github.com/keras-team/keras-preprocessing/issues/55
  [2]: https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/image_data_generator.py#L938
  [3]: https://scikit-learn.org/stable/modules/generated/sklearn.utils.extmath.randomized_svd.html
  [4]: http://bwlewis.github.io/irlba/
  [5]: http://www.cs.cmu.edu/~aarti/Class/10701_Spring14/slides/PCA.pdf
  [6]: https://i.stack.imgur.com/AUdeD.png
  [7]: https://i.stack.imgur.com/1rBca.png

**Comment by maheshmechengg** [comment]
> No I have not.
> But it works fine without ZCA whitening, featurewise/centerwise operation.

Yes i was facing same with just 1362 image files & w/o ZCA whitening, featurewise/centerwise operation solved it.

Just wonder that If i try it in for loop for single image file still i get error of LAP 32bit processing limit.
