### ISSUE TITLE
Input features of imdb_fasttext example neither BOW nor bag-of-ngrams

### ISSUE THREAD

**Issue by AlexGidiotis** [keras-team/keras#8735]
I have read the original [paper](https://arxiv.org/pdf/1607.01759.pdf) and I believe it proposes that the input features to the model are in the form of bag-of-words/bag-of-ngrams. On the other hand the imdb_fasttext implementation appears to be using sequences of word tokens. 

Am I missing something here?

**Comment by ptresende** [comment]
I believe you are correct.

Fasttext uses character-level n-grams, which means that, for instance, for the word "where", the resulting vector will be the average of the following vectors:

[<wh, whe, her, ere, re>, <where>]

This is **not** what is being done in https://github.com/keras-team/keras/blob/master/examples/imdb_fasttext.py

Instead, in the example, the n-grams are being computed at word-level.

The example should either be fixed or removed, as it is wrong.

**Comment by AlexGidiotis** [comment]
Well I guess you can always tokenise at character level and compute the new n-grams.

To my understanding and since the data are not processed sequentially, the output of the embedding layer is equivalent to one that takes as input bags-of-ngrams. Correct me if I am wrong.

**Comment by ptresende** [comment]
I guess that's correct, but the IMDB dataset that is used in the example has each comment defined as a list of integers, each of which mapping to a word - this can be seen here: https://github.com/keras-team/keras/blob/master/keras/datasets/imdb.py

Given this, I don't think it's really possible to take that dataset as it's defined and make the example work, since the step of computing the n-grams for each word would have had to be done on top of the "raw" dataset.

I might be misunderstanding something, however, and please correct me if I'm wrong as well.

**Comment by AlexGidiotis** [comment]
Yes you are right, since the IMBD dataset provided with keras is already tokenised. The model works ok at a word level but it is not the same as the original fasttext version.
