### ISSUE TITLE
tensorflow-aarch64 with keras

### ISSUE THREAD

**Issue by SHFRGRP** [keras-team/keras#8817]
![screenshot_2017-12-17-15-05-30-239_ru iiec pydroid3](https://user-images.githubusercontent.com/31110466/34079317-cf205ac0-e33c-11e7-8042-cf8fe5217784.png)
![screenshot_2017-12-17-15-04-36-922_ru iiec pydroid3](https://user-images.githubusercontent.com/31110466/34079318-cf6c95f2-e33c-11e7-9b6b-1304337a0d4c.png)
![screenshot_2017-12-17-15-04-20-194_ru iiec pydroid3](https://user-images.githubusercontent.com/31110466/34079319-cfaa0220-e33c-11e7-9e4c-bfaf843b1401.png)

Hi! I want to use tensorflow library as backend of keras on my android device. I found and installed pydroid3, keras and tensorflow-aarch64. How can i use it? When i run code it throws exception "no module named tensorflow". Any ideas?

**Comment by gabrieldemarmiesse** [comment]
Hi,
Since this question is about the installation of Tensorflow, you should close the issue here and open the same one in the Tensorflow github repository. Keras assumes that you have Tensorflow installed. So you won't get a lot of help here. You'll have better luck with the Tensorflow community though.

I hope this helps.
