### ISSUE TITLE
Keras: implementation issue for CNN + LSTM with TimeDistributed layers for various input size

### ISSUE THREAD

**Issue by xujunpeng** [keras-team/keras#8846]
I have implemented a CNN+LSTM auto-encoder by using Keras. The code is similar as:

    ......
    x = self._conv_bn_relu(filters=64, kernel_size=(3,3))(x)
    x = MaxPooling2D((2, 2), padding='same')(x)  # 16x16
    # branches (LSTM-vertical)
    x = TimeDistributed(Bidirectional(LSTM(32, input_shape=(4, 64), return_sequences=True)))(x)
    x = self._conv_bn_relu(filters=64, kernel_size=(3,3))(x)
    x = UpSampling2D((2, 2))(x) # 32x32
    ......

For this setup, the network can only accepts input with fixed size, like (64x64), but I really want my network can accept various input size. Is there any method to do this?

Thanks,
X. P

**Comment by gabrieldemarmiesse** [comment]
Hi! 
You can do this using the reshape layer. The reshape layer support - 1 for size inference.
In your case, you need to call Reshape((-1,4,64)) and the backend will perform shape inference for you.
Btw, this question is more appropriate in stackoverflow or the keras google group. Github issues are more to report bugs in the keras codebase. 
Hope this helps!

**Comment by xujunpeng** [comment]
Hi gabrieldemarmiesse,

Thank you for your reply. But when I try Reshape layer when I set my input with None dimension, like:
input_img = Input(shape=(size, None, 3))
x = Reshape((3*size, -1, 1))(input_img)
Reshape layer will report errors like:
TypeError: long() argument must be a string or a number, not 'NoneType'

**Comment by gabrieldemarmiesse** [comment]
You're right.
Keras is trying to guess the shape in python. Because not all backends can do the shape inference at run time. That's why keras wants to know the exact input shape. If you use a backend that can do the shape inference (like tensorflow for example), you can bypass the keras shape inference and use the backend shape inference. like this:

x = Lamda(lamda a: K.reshape(a, (3*size, -1, 1)), output_shape=lambda a; (3*size, None, 1))(input_img)
