### ISSUE TITLE
Download directory should only be checked for writability if the file is not present

### ISSUE THREAD

**Issue by jonasrauber** [keras-team/keras#8900]
Keras automatically downlodas pretrained weights when creating applications, e.g. `keras.applications.inception_v3.InceptionV3(weights='imagenet')`. In principle, Keras checks whether the weights file is already present and only downloads it if not. If the directory with the already present weights file is however not writeable, it does redownload the weights to a temporary folder even though they are already downloaded and no write access is needed.

Keras should first check whether the file is already present. Only if not, it has to check for write access.

Having a read-only location for the weights is common when mounting the weights using read-only Docker volumes, for example.

I think a fix could be as simple as rearranging some lines in the `get_file` function in [data_utils.py](https://github.com/keras-team/keras/blob/master/keras/utils/data_utils.py#L178).

**Comment by gabrieldemarmiesse** [comment]
I'll make a PR about it. Thank you.

**Comment by gabrieldemarmiesse** [comment]
If you have any idea on how to make a folder read only and then allow writing again from python, that would help a lot to make the tests. I've been looking into `chmod`, but it doesn't behave as I expected. Thank you.

**Comment by jonasrauber** [comment]
@gabrieldemarmiesse `chmod` sounds right and should be able to do exactly that

**Comment by gabrieldemarmiesse** [comment]
Hi! 
Well, I noticed that I had to use chmod, but I can't quite make sense of the arguments. I'm not familiar with permissions in general.
What would be the chmod function call to make a directory read only, and the chmod function call to reset the permissions so that I can remove the directory afterwards. It would be very useful for the tests functions and PR are accepted way faster if they have good tests functions.
Thank you for all your help! I hope we can make this into keras!
