### ISSUE TITLE
Can't train LSTM weights on GPU

### ISSUE THREAD

**Issue by Yuren-Zhong** [keras-team/keras#8901]
This is the implementation of my model.
```
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM

model = Sequential()
model.add(Embedding(max_features, output_dim=256))
model.add(LSTM(128))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

```
This model can be successfully trained on CPUs, although it's slow. But if I install `tensorflow-gpu` to train the model on GPUs, `Segmentation fault (core dumped)` occurs while executing the line `model.add(LSTM(128))`.

python 3.6.4 is installed. I have tried keras 2.0.8 and keras 2.1.2, and both of them cause `Segmentation fault (core dumped)`.

I wonder why it occurs and if it's possible to fix it.

Thanks!

**Comment by gabrieldemarmiesse** [comment]
Hi! 
It's highly possible that the bug comes from Tensorflow. Keras can't produce segmentation faults because it's entirely written in python. And Tensorflow should throw an exception if you're doing something illegal. Can you close this issue here and open the same one in the tensorflow repository?
 Thank you.

**Comment by PathricLee** [comment]
i have the same problem, wonder how do you solve the problem?

**Comment by Yuren-Zhong** [comment]
@PathricLee I changed backend from tensorflow to theano. I suppose it's a bug in running tensorflow with GPU.
