### ISSUE TITLE
how to apply different weights' dense to RNN for each timestamp?

### ISSUE THREAD

**Issue by photon00** [keras-team/keras#8918]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by photon00** [comment]
as title,
I know that timedistributed wrapper could apply dense for each timestamp, however is with same weights. I want to apply same shaped dense, but with different weights for each timestamp, does anyone can help?

**Comment by DingkunLiu** [comment]
I think if you apply different weights for each timestamp, it is equal to fully connected layer.

**Comment by photon00** [comment]
@DingkunLiu 
thanks for your reply,
but i want fully connected only focus on each timestamp, and not contributed by another timestamp's features. Otherwise, fully connected layer seems cannot be apply on a 2D input?

**Comment by DingkunLiu** [comment]
I see. You need a (timestep*channel, channel_1) weight matrix and perform a partial matrix multiplication. I think you have to write your own custom layer with keras backend. Alternatively, you can check if attention model could match your case.

**Comment by DingkunLiu** [comment]
So you mean want a weight matrix with shape (timestep*channel1, channel2) and perform a partial matrix multiplication. I think maybe you have to write your own layer? You can check the LSTM implementation 2. LSTM has 4 different weight matrix and here is n, which intrinsically is the same. Alternatively, you can check attention model to see if it can meet your need.
发送自 Windows 10 版邮件应用

发件人: photon00
发送时间: 2017年12月31日 12:27
收件人: keras-team/keras
抄送: Dingkun.Liu; Mention
主题: Re: [keras-team/keras] how to apply different weights' dense to RNNfor each timestamp? (#8918)

@DingkunLiu
thanks for your reply,
but i want fully connected only focus on each timestamp, and not contributed by another timestamp's features. Otherwise, fully connected layer seems cannot be apply on a 2D input?

**Comment by photon00** [comment]
thx @DingkunLiu , 
do you know where can i find such example to implement this idea?

**Comment by photon00** [comment]
thx @DingkunLiu , 
do you know where can i find such example to implement this idea?
