### ISSUE TITLE
load_model crashing 

### ISSUE THREAD

**Issue by HeXu1** [keras-team/keras#8927]
hello:
      I'm using TensorFlow with keras. Then  I get a problem When i use load_model function . 
    
   when I run this “yolo_model = load_model("model_data/yolo.h5")”.
Then the out put is "2017-12-31 12:54:33.088567: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Process finished with exit code -1073740940 (0xC0000374)"

I'm thinking about whether it's a memory problem?
 Apologize for my poor English

**Comment by koreyoshi-wang** [comment]
I get the same question, on my computer and system is windows 10.
It's caused by your model data "yolo.h5".

solution is convert yolo.h5 from Darknet by yourself.
[How to](https://github.com/allanzelener/YAD2K)

If you get the following error:
_UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 80-81: truncated \UXXX_

solution is:
open file **Lib\site-packages\keras\utils\generic_utils.py** under your Python path.
Changing 
**code = marshal.dumps(func.__code__).decode('raw_unicode_escape')**
to
**code = marshal.dumps(func.__code__).replace(b'\\',b'/').decode('raw_unicode_escape')**

**Comment by koreyoshi-wang** [comment]
Hope this help

**Comment by HeXu1** [comment]
my problem has been handled，very appreciated！
