### ISSUE TITLE
LSTM layer producing seemingly incorrect output shape

### ISSUE THREAD

**Issue by brendon-ai** [keras-team/keras#8934]
I am trying to create a neural network that includes an LSTM layer followed by two dense layers. I am creating the model like so:

```
model = Sequential()
model.add(LSTM(10, input_shape=(None, 2), return_sequences=False))
model.add(Dense(4, activation='tanh'))
model.add(Dense(1, activation='tanh'))
```

I am providing training data where X is of shape (1, 229, 2) and Y is of shape (1, 229). This means (as far as I understand) that the training data is in a single batch, containing a sequence of length 229 time steps. For each time step, the input is a two-element array, and the output is a single number.

Unfortunately, this produces the error: `expected dense_2 to have shape (None, 1) but got array with shape (1, 229)`. This seems like the LSTM layer is returning the outputs for all of its time steps, but this is specifically not the case because `return_sequences` is `False`! And if I change it to `True`, I get a different error: `expected dense_2 to have 3 dimensions, but got array with shape (1, 229)`.

Does anybody know what I'm doing wrong? I'm not entirely sure the `input_shape` of (None, 2) is correct.

**Comment by tomastheod-ITI** [comment]
You can find out the expected input / output shape of layer k using `model.layers[k].input_shape` and `model.layers[k].output_shape`. Since LSTM is the first layer:
```
model.layers[0].input_shape
(None, None, 2)

model.layers[0].output_shape
(None, 10)
```
The input shape (None, None, 2) means that you have not specified the sequence length. So the input_shape=(None, 2) should be changed to (229, 2). However, this is not actually a problem.

The problem is that your model expects a target Y that is a single value for each training instance, not a sequence of 229 values, since you have chosen return_sequences=False. If you want to pass sequences as targets, you have to reshape Y into a 3D array of shape (samples, 229, 1), change return_sequences=True and use TimeDistributed:
```
model.add(LSTM(10, input_shape=(229, 2), return_sequences=True))
model.add(TimeDistributed(Dense(4, activation='tanh')))
model.add(TimeDistributed(Dense(1, activation='tanh')))
```

**Comment by brendon-ai** [comment]
@tomastheod-ITI I'm confused. The LSTM isn't supposed to take sequences as inputs during inference. It should presumably take a single element, return a single output, and update its internal state.

How would one train an LSTM without using sequences?

**Comment by brendon-ai** [comment]
Ah never mind, I'm switching to PyTorch.

**Comment by tomastheod-ITI** [comment]
@brendon-ai Take a look at the first figure http://karpathy.github.io/2015/05/21/rnn-effectiveness/

You can have sequences as input and only a single target for the whole sequence as output (many to one).
