### ISSUE TITLE
I would like suggestions for speeding up tests on travis. 

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#8990]
I'd like to do a PR to speed up the tests on travis. 

I already looked at the logs to see what tests are the longest to run, so far, it's installing the dependencies and running tests like ConvLSTM2D, rnns, separable conv, inception resnet...

I looked at the code and it looks pretty efficient to me, I've no idea how I could cut the running time by half (the target set in the request for contributions).

If someone would be kind enough to tell me what to look for or how to start, I would be happy to work on it and make a PR. 

Thank you in advance.

**Comment by fchollet** [comment]
Possible suggestions:

- Running layers/etc on small input tensors (e.g. using 2 samples instead of 1000).
- Some tests are more like integration tests than unit tests (they do extra stuff that may not be necessary to test what they are testing). For instance it is not always necessary to instantiate a model and call `fit`. Such tests could be simplified.

As you state the application tests are taking up a lot of time. @taehoonlee's recent PR helps (by running less tests). We could also making it so that application tests are only triggered by changes in certain files (layers, topology, applications). Other changes should not affect the sort of applications test we're running.

**Comment by taehoonlee** [comment]
@gabrieldemarmiesse, please refer to #9047 and #9059. And my idea is to skip `tests/keras/legacy/interface_test.py` or test it intermittently because the legacies are no longer updated. Is it reasonable @fchollet?

**Comment by gabrieldemarmiesse** [comment]
I thank you both for the suggestions. I'll look into it!
