### ISSUE TITLE
How to add our own new Keras backend?

### ISSUE THREAD

**Issue by muthiyanbhushan** [keras-team/keras#9060]
I would like to add my own backend for Keras. Is there a way to create new backend without changing the __init__.py file ?

**Comment by fchollet** [comment]
You have to fork the Keras codebase, add a new backend file in `backend`, and add a couple lines in `backend/__init__.py` to enable your new backend.

Alternatively, you could do some Python magic to automatically replace all methods in `keras.backend` with your methods, at startup time. But it would be hacky and potentially dangerous. And unlike with a fork, there would be no guarantees that the Keras codebase would work with your backend. That's why it's far safer to use a fork. That way you can make sure there is consistency between the codebase and the backend.

Adding a new backend is not something that users do often, so the overhead of editing `__init__.py` is not significant.
