### ISSUE TITLE
self.oov_token will be lost while in serializing(pickle.dumps)

### ISSUE THREAD

**Issue by brian41005** [keras-team/keras#9099]
it can be reproduced every time.

![image](https://user-images.githubusercontent.com/13401708/35058620-7b7521ce-fbf3-11e7-84f5-f40d71ac238e.png)
![image](https://user-images.githubusercontent.com/13401708/35058641-872955ee-fbf3-11e7-8582-91f7fbd571b6.png)

**Comment by fchollet** [comment]
You can manually set `tokenizer.oov_token = None` to fix this.

Pickle is not a reliable way to serialize objects since it assumes that the underlying Python code/modules you're importing has not changed. In general, *DO NOT* use pickled objects with a different version of the library that what was used at pickling time. That's not a Keras issue. In this case there's a simple fix (set the attribute) but in many cases there will not be.
