### ISSUE TITLE
How does the UpSampling layer work?

### ISSUE THREAD

**Issue by emoebel** [keras-team/keras#9113]
Dear Community,

How do the UpSampling* layers work? The documentation only says "Upsampling layer for 2D inputs.", which is not very precise.. Is it linear interpolation? Or is the upsampling operation learnable, like the upconvolution found in the literature (e.g. Fully Convolutional Networks paper from Long)?

Thanks,
 lazyleaf

**Comment by Dref360** [comment]
https://github.com/keras-team/keras/blob/8ed57c168f171de7420e9a96f9e305b8236757df/keras/layers/convolutional.py#L1552

**Comment by lazyleaf** [comment]
So there is not even interpolation? Huh! 
Is there a layer in keras to do bilinear interpolation? Is there something to do upconvolutions (ie learnable upsampling)? And if so, does it also exist for 3D images?

**Comment by rex-yue-wu** [comment]
1. `tensorflow` has bilinear upsampling layer, which does the work as you want
2. what you asked, i.e. `upconvolution`, can be easily thought as `UpPool+Conv`, whether `Conv` here is 2D or 3D really does not matter, because it is just a standard layer. In this way, you realize the learnable `upconvolution` layer in two stages. Though the 1st `UpPool` stage is deterministic, the 2nd `Conv` stage is learnable.

**Comment by lazyleaf** [comment]
ok thanks!
