### ISSUE TITLE
Keras predict_generator output differs every time

### ISSUE THREAD

**Issue by Golbstein** [keras-team/keras#9464]
in the last 2 months I was stucked with this issue and it drove me crazy until I realized my "probabilities" vector from predict_generator is simply wrong.

I'm using keras 2, and I've a **test** folder with sub-directories that contain images (not necessarily same amount of images)

then I import my model, load the weights and do this:

```
from keras.applications import ResNet50
model = ResNet50(include_top=True, weights=None, input_shape=(3,224,224),classes=N)
model.load_weights(model_path)
probs1 = model.predict_generator(batches, steps=batches.n/64, verbose=1)
probs2 = model.predict_generator(batches, steps=batches.n/64, verbose=1)

```
and I don't why but probs1 != probs2 when probs2 seems like the "correct" predictions.

P.S. batches.n/64 is not an integer

What should I do?

**Comment by MarcelBeining** [comment]
Hi, I just came across this when looking for another problem.
I know your question is one year old, but maybe it still helps answering:
I guess `batches `is a generator, otherwise it won't work, so you might have to make sure that the generator starts again at index zero!
So if `batches `is a `ImageDataGenerator `you can do
`batches.reset() `
inbetween the two predictions.
