### ISSUE TITLE
Keras Training Stops at First Epoch When using CNNs

### ISSUE THREAD

**Issue by asellam** [keras-team/keras#9476]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by asellam** [comment]
Hi Everyone, I am using keras with tensorflow backend to train a basic cnn on a laptop with an NVidia 960M (2GB of Memory), it ssems to be stuck on the first epoch. As i am new to keras i can't figureout why is this hapenning. Help me Please

**Comment by asellam** [comment]
This is only hapening when i install and use TensorFlow GPU

**Comment by sairajk** [comment]
- Since the code is not showing any error message it should be correct and must be running.  
- To track your model progress per batch set "verbose" argument in the fit method to be 1. 
- Use nvidia-smi/GPU-Z to monitor your GPU usage while running your program, this will give you an idea if the GPU is being used or not.
- Uninstall all tensorflow, tensorflow-gpu and keras. Update all packes you have. Just install tensorflow-gpu and then keras.

This is all I can suggest with the given information. See if it works.

**Comment by asellam** [comment]
Hi everyone
Thanks for answering sairajk, i actualy verbose 1 and it is not showing progress or any thing, and i also have a tool called dragon center on my laptop that monitors gpu usage, once the training starts it shows me about 50% of gpu usage for a fraction of second then it go back to zero almost instantly, it looks like a failure or something.
When i track memory usage using task manager i see memory usage growing a little bit sometimes 500 MB sometimes higher and then it stops.

**Comment by sairajk** [comment]
You can try tuning the hyperparameters and also experiment with various optimizers, I don't know if it would solve the problem or not but it's something you can try.
But I think there must be some error in the code, else you should have it running.

**Comment by FypTeamFast2019TumorDetection** [comment]
I faced this problem in Co-Lab provides limited memory upto(12 GB) in cloud which creates many issues while solving a problem. That's why only 300 images are used to train and test.when images was preprocessed with dimension 600x600 and batch size was set to 128 it Keras model freezed during epoch 1 .Compiler did not show this error.Actually the error was runtime limited memory which was unable to handle by CoLab because it gave only 12GB limited memory for usage. Solution to above mentioned problem was solved by changing batch size to 4 and reduce image dimension to 300x300 because with 600x600 it still not work.
Conclusively,Recommend Solution is Make Images dimension and Batch_size small until you get no error Run Again and Again until there will no run time error

**Comment by yeyewen** [comment]
@FypTeamFast2019TumorDetection  I faced the same problem，but making the batchsize small is not helpful. 
 I am using keras with tensorflow backend to train ICNet on a desktop with an NVidia 2080Ti . It was stuck on first 1 epoch.but the same code can run on my colleague's desktop. And I don't know why
