### ISSUE TITLE
Obtaining Cell States and the Forget Gate Layer for every timestep in LSTM using keras

### ISSUE THREAD

**Issue by PedroFerreiradaCosta** [keras-team/keras#9493]
Hi there!

I am trying to obtain the cell states and the forget gate layers for every timestep of my LSTM, but I'm a bit lost on the how. I seem to be able to obtain only the last cell state adapting the code used in: https://github.com/keras-team/keras/issues/7632

Here's the code:
```
seqlg = X_training.shape[1]
depth = X_training.shape[2]


x = Input(shape=(seqlg,depth))
z, sh, sc = LSTM(units=33, return_state=True,return_sequences=True)(x)
z = Activation('softmax')(z)

model1 = Model(input=[x],output=[z])
model2 = Model(input=[x],output=[z,sh,sc])
model1.compile(loss='categorical_crossentropy', 
optimizer='adam',metrics=['categorical_accuracy'])


history = model1.fit(X_training, Y_training)
Y, Sh, Sc = model2.predict(X_training)

```

X_training is shaped (800, 350, 33) -> (trials, timesteps, units)
and so is Y_training.

Thank you for the help!

**Comment by tushar-agarwal2909** [comment]
Hi
I have tried to do something similar but as much as I understand, it is not possible to get cell states at every time-step in keras LSTM layer right now. You may try to tweak the source code of RNN layers or request developers.

A way around this for the moment, that I used, is using GRU layer instead of LSTM layer. GRU layers are said to give a comparable performance as LSTM. In GRU, there is no cell state and so (return_sequences=True) returns the output at every time step (Note: hidden states and outputs both are equal for RNN layers).

There isn't any forget gate layers as far as I know. Forget gates just have weights.

I am new to all this so anybody please correct me if I am wrong.
Hope it helps.

**Comment by DavidDavidsonDK** [comment]
Hi
There is no trivial way to get lstm_cell gate ,,but it's not impossible

Here's the code:

#overide LSTM cell call function
```
class MY_LSTMCell(Layer):
    def call(self, inputs, states, training=None):
        #Do not change above code(or if you want)
        self.i = i   #keep i gate
        return h, [h,c]

#Define model
import keras
from keras.utils.generic_utils import CustomObjectScope

with CustomObjectScope({'LRP_LSTMCell': LRP_LSTMCell}):
    cell = My_LSTMCell(60)
    x = keras.Input((None,1))
    layer=RNN(cell)
    y = layer(x)
    y = Dense(5)(y)
    model = Model(inputs=x, outputs=y)
```
 #After tarining (or in training time )if you want to touch lstm_cell gate

inp = model.input                                           # input placeholder
func = K.function([inp, K.learning_phase()],[model.layers[1].cell.i)
data = array([0.1, 0.2, 0,3]).reshape((1,3,1))
x = func([data,1.]) 

#but doing this you get the activation of gate in last time stamp
#for to solve this you can feed the data skipping the last time stamp

inp = model.input                                           # input placeholder
func = K.function([inp, K.learning_phase()],[model.layers[1].cell.i)
data = array([0.1, 0.2]).reshape((1,2,1))
x = func([data,1.]) 

etc.
```
