### ISSUE TITLE
Using `oov_token` breaks Tokenizer by adding too-high indices to tokenized sequence

### ISSUE THREAD

**Issue by cpury** [keras-team/keras#9574]
I'm trying to tokenize a string by character. The new `oov_token` seems awesome, but it breaks my sequences. E.g. I have this:

```
tokenizer = Tokenizer(num_words=100, filters='', split='', char_level=True, oov_token='¬')
```

This will create sequences like this:

```
array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,  39.,   1.,  10.,   4.,   2.,   1.,  15.,   5.,   3.,
         3.,   8.,  14.,   9.,   5.,  18.,   7.,   1.,  39.,   1.,   4.,
         8.,   7.,   1., 429.,  14.,   9.,   2.,   4.,  51.,   9.,   5.,
        13.,  13.,  18.,   2.,   3.,   1.,  10.,   2.,   6.,   1.,  17.,
         2.,   8.,   7.,   2.,   1.,  18.,   4.,  12.,  15.,   1.,  10.,
         2.,   3.,   1.,   4.,  14.,   9.,   1.,  32.,   2.,   1.,  16.,
         2.,   8.,   2.,   9.,   2.,   3.,   1.,   9.,   5.,  17.,  74.,
        76.])
```

Note the `429`-indices which are way outside the scope of my 100 features.

This will break the model's embedding layer with a rather cryptic error message:

```
InvalidArgumentError (see above for traceback): indices[0,47] = 429 is not in [0, 100)
	 [[Node: embedding_2/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_2/embeddings/read, embedding_2/Cast)]]
```

Removing the `oov_token` argument from `Tokenizer` fixes the issue.

**Comment by FrancoSwiss** [comment]
Hey Max, did you ever get this solved?

I believe mine works with oov_token = 100

Greetings from Frankfurt

**Comment by FrancoSwiss** [comment]
You're absolutely right.

**Comment by hamishdickson** [comment]
Hey everyone, I've stumbled across too - from playing about it seems the index assigned for the `oov_token` is the next free index. So in @cpury s example there are probably words all the way up to position 428

Not looked into the code yet, but maybe that'll help someone work out an appropriate fix

**Comment by alooow** [comment]
Hi, I have also encountered this problem. A quick-and-ugly fix could be to overwrite the internal word_index in tokenizer. Minimal dummy example below:

**Original, unmodified code, using the Tokenizer**:
`num_words=5`
`tokenizer = Tokenizer(num_words=num_words, oov_token="<UKN>")`
`tokenizer.fit_on_texts(["The quick brown fox jumps over the lazy dog. The lazy dog jumps over a frog."])`
`print(tokenizer.word_index)`
`print(tokenizer.texts_to_sequences(["the dog jumps over the elephant"]))`

This will output:

`{'the': 1, 'jumps': 2, 'over': 3, 'lazy': 4, 'dog': 5, 'quick': 6, 'brown': 7, 'fox': 8, 'a': 9, 'frog': 10, '<UKN>': 11}`
`[[1, 2, 3, 1, 11]]`

The `elephant` wasn't encountered before, so it is an `<UKN>`. `<UKN>` is set, as mentioned by @hamishdickson , to the last  not taken index in fitting corpus (here it is `11`).  The `dog` is omitted, since it is not in the top `num_words-1` words used by the tokenizer. This is also an unexpected behavior mentioned in issue #9409, since a more natural solution would be to replace the `dog`  with the `<UKN>` token. 

**A quick-and-ugly fix: (very ugly as it overwrites the internal tokenizer word_index)**

Move all the values to make place for special characters. Omit the entries from the dictionary which
would have a value larger then `num_words`.  This will solve the `dog` problem described above. 
`special_tokens = 2`
`word_index = {k: v+special_tokens for k, v in tokenizer.word_index.items() if v<=num_words-special_tokens}`
Insert the special characters
`word_index["<START>"]=1`
`word_index["<UKN>"]=2`
set the word_index
`tokenizer.word_index = word_index`
`print(tokenizer.word_index)`
`print(tokenizer.texts_to_sequences(["the dog jumps over the elephant"]))`

will output:

`{'the': 3, 'jumps': 4, 'over': 5, '<START>': 1, '<UKN>': 2}`
`[[3, 2, 4, 3, 2]]`

Note that this solution will produce a dictionary of size `num_words`, including the `special_tokens` tokens. This is consistent with the tokenized data returned by some functions from keras.datasets  (for example `keras.datasets.imdb.load_data(num_words=self.num_words)`), which was something I needed (therefore the `<START>`  token, which is meaningless in the example below, but for which a value (value=1) is reserved in the mentioned `load_data` function .
