### ISSUE TITLE
How to verify if a model is valid by its architecture?

### ISSUE THREAD

**Issue by oxydron** [keras-team/keras#9769]
Is there any way to validate if the model architecture is valid, before run it and get a exception?
Would be nice if a model had a method like `model.is_valid() -> bool`.
This is interesting for people trying to generate random models in genetic algorithms or swarm.

**Comment by gabrieldemarmiesse** [comment]
If all the input sizes are defined, you'll get an exception in keras as soon as you connect the layers together (you won't actually be able to create the object model).

**Comment by oxydron** [comment]
Indeed this is what I'm doing right now, a `try..catch`.

**Comment by gabrieldemarmiesse** [comment]
It seems like the best option!

**Comment by gabrieldemarmiesse** [comment]
Could you please close the issue since there won't be a fix to this?

**Comment by oxydron** [comment]
Sorry I don't see how this is a good option, to use a exception control instead of a algorithm to do this.
I mean, in the end, exists a algorithm that can analyze every layer and its parameters to conclude the model validity.

**Comment by gabrieldemarmiesse** [comment]
You can take a try if you want to do this function yourself, but exceptions are the only way to know if an operation can't be done between two tensors. 

And the issue is not even at the keras level, it's at the backend level. So keras can't do it if Theano, tensorflow or CNTK can't do it. You might want to try to ask on the github page of the backend you are using, but it's very likely that the maintainers will tell you that they don't want to support it as it would require a lot of work on their end, and a try...catch actually works well in most cases.

In any case, keras can't do it, because the backends don't support it.

**Comment by oxydron** [comment]
Or maybe a tool that helps with it. I mean, with only the parameters it's possible to infer it. But I'll do what you said, write a tool for that.

**Comment by krenerd** [comment]
I just defined a function to manually compare the number of layers and output dimensions of each layer, but looking forward to an official feature by Keras. Any further solutions to this issue?
