### ISSUE TITLE
How to model a LSTM which accepts a history of multiple states and predict states (ndim=4)?

### ISSUE THREAD

**Issue by ltung** [keras-team/keras#9833]
Hi All,

I would like to predict a vector of 4 states, each states could be in red, orange, green, e.g.

t: [red, orange, green, red]
t+1: [orange, red, red, green]
t+2:
t+3:
.
.

I certainly could encode the colors using "to_categorical" to represent distinct color (3 colors). However, I am stuck at defining the LSTM model, since I have ~ 4000 samples and for each sample, I would like to look back past 500 steps to predict the next time. In LSTM, it could be:

(nb_samples, timesteps, features)

In the features, instead of a vector of number, in my case, it is a vector of statuses. So, for me, the dimension is like:

(4000, 500, 4, 3). 

model.add(LSTM(128, input_shape=(500, 4, 3)))
^^^^ error:
ValueError: Input 0 is incompatible with layer lstm_10: expected ndim=3, found ndim=4

Keras couldn't accept 4 dimension in the LSTM model. So, I am stuck and just wonder if anybody has any idea to approach this problem. Thanks.

**Comment by JialuCarolChen** [comment]
check out multi-state LSTM: 
paper: https://arxiv.org/abs/1702.03402
blogpost: https://towardsdatascience.com/multi-state-lstms-for-categorical-features-66cc974df1dc

**Comment by bdowe** [comment]
You can actually solve this problem using keras, but with a 3 dimensional model instead of a 4 dimensional model. Your feature matrix had the dimensions of (4000, 500, 4, 3), where 3 is the number of categories (or number of one-hot columns) and 4 is the number of color states per time step. 

Instead, you should represent each color state as it's own set of 3 one-hot encoded columns, and just concatenate all 4 sets of 3 one-hot columns together. So instead of [orange, red, red, green], you would have [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1] where 1, 0, 0 is orange, 0, 1, 0 is red (repeated twice), and 0, 0, 1 is green.

This would make the dimensions of your feature matrix (4000, 500, 12), where 12 is the number of features (4 x 3). Instead of adding a new dimension for the number of one-hot columns, you replace the states in each timestep (4) with the one-hot columns from all 4 states (4 x 3 = 12).
