### ISSUE TITLE
Is it a good idea to define the None in the input shape as placeholder ?

### ISSUE THREAD

**Issue by StevenLOL** [keras-team/keras#9927]
Hi, all

We know the first None in the actual input shape [None, None , 100]   denotes batch size and the second None is timestamp .

Can we create something like [batch_size_placeholder , timestamp_placeholder , 100]  in order to make it easy to understand ?

**Comment by rex-yue-wu** [comment]
No, you are wrong. In `input_shape=(None,None,100)`, the 1st `None` means the number of rows in a 4D tensor, and the 2nd `None` means the number of columns in a 4D tensor. The batch size is NOT included in `input_shape`, which actually make sense because a model has to be compatible with an arbitrary batch size that a user selected during training.
